# Indian Pines

In [1]:
from Source_Model_Utils import *
import scipy.io as sio

In [2]:
uIndian_pines = sio.loadmat('..\\..\\Indian Pines\\Indian_pines_corrected.mat')
gt_uIndian_pines = sio.loadmat('..\\..\\Indian Pines\\Indian_pines_gt.mat')
data_IN = uIndian_pines['indian_pines_corrected']
gt_IN = gt_uIndian_pines['indian_pines_gt']
print(data_IN.shape, gt_IN.shape)
data_IN = np.moveaxis(data_IN, 2, 0)
print(data_IN.shape, gt_IN.shape)

(145, 145, 200) (145, 145)
(200, 145, 145) (145, 145)


In [3]:
values,counts = np.unique(gt_IN, return_counts=True)
print(values,counts)
range_of_class = list(values)
if 0 in range_of_class:
    range_of_class.pop(0)
range_of_class

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16] [10776    46  1428   830   237   483   730    28   478    20   972  2455
   593   205  1265   386    93]


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

In [4]:
Acc_Table = Train(overlap_ratio_List = [50, 75, 85, 95],
                  range_of_class = range_of_class,
                  Cube_size= 25,
                  Data = data_IN,
                  Gt = gt_IN,
                  Train_Test_split = 80,
                  channel = 103,
                  epochs_list = [100, 100, 100, 100],
                  batch_size_list = [2, 4, 8, 16],
                  data_name = 'Indian_Pines',
                  Verbosity  = 1,
                  LR = 0.0001)

                     0             1
0  Test Accuracy Table  Indian_Pines
1      Data_Overlap_50          None
2      Data_Overlap_75          None
3      Data_Overlap_85          None
4      Data_Overlap_95          None


======================================== Data with overlap ratio of 50% will be trained =======================================


(75, 103, 24, 24, 1) (22, 103, 24, 24, 1) (75,) (22,)
Total samples per class: [0, 15, 8, 0, 7, 10, 0, 4, 0, 12, 24, 5, 0, 12, 0, 0], Total number of samples is 97.

unique classes in Ytest: [ 2  3  5  6  8 10 11 12 14], Total number of samples in Ytest is 22.
number of samples per class in Ytest: [3 2 2 2 1 3 5 1 3]

Xtrain => (75, 103, 24, 24, 1)
Xtest  => (22, 103, 24, 24, 1)
Ytrain => (75, 9)
Ytest  => (22, 9)

Model: "3D-SRNet"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (In

Train on 75 samples, validate on 22 samples
Epoch 1/100
74/75 [============================>.] - ETA: 0s - loss: 6.0804 - categorical_accuracy: 0.2027
Epoch 00001: val_categorical_accuracy improved from -inf to 0.13636, saving model to ..\..\Trained Models\Full_Model\Indian_Pines\Full_Model_best_Indian_Pines_overlap_ratio_50_percent.h5
75/75 [==============================] - 6s 82ms/sample - loss: 6.0534 - categorical_accuracy: 0.2000 - val_loss: 8.0386 - val_categorical_accuracy: 0.1364
Epoch 2/100
74/75 [============================>.] - ETA: 0s - loss: 5.3141 - categorical_accuracy: 0.2703
Epoch 00002: val_categorical_accuracy did not improve from 0.13636
75/75 [==============================] - 1s 12ms/sample - loss: 5.2940 - categorical_accuracy: 0.2800 - val_loss: 6.7805 - val_categorical_accuracy: 0.1364
Epoch 3/100
72/75 [===========================>..] - ETA: 0s - loss: 5.0527 - categorical_accuracy: 0.2639
Epoch 00003: val_categorical_accuracy did not improve from 0.13636
75

Epoch 24/100
74/75 [============================>.] - ETA: 0s - loss: 3.0104 - categorical_accuracy: 1.0000
Epoch 00024: val_categorical_accuracy did not improve from 0.45455
75/75 [==============================] - 1s 11ms/sample - loss: 3.0102 - categorical_accuracy: 1.0000 - val_loss: 4.8457 - val_categorical_accuracy: 0.4091
Epoch 25/100
72/75 [===========================>..] - ETA: 0s - loss: 2.9888 - categorical_accuracy: 0.9861
Epoch 00025: val_categorical_accuracy did not improve from 0.45455
75/75 [==============================] - 1s 11ms/sample - loss: 3.0037 - categorical_accuracy: 0.9733 - val_loss: 4.6547 - val_categorical_accuracy: 0.4091
Epoch 26/100
74/75 [============================>.] - ETA: 0s - loss: 3.0137 - categorical_accuracy: 1.0000
Epoch 00026: val_categorical_accuracy did not improve from 0.45455
75/75 [==============================] - 1s 11ms/sample - loss: 3.0120 - categorical_accuracy: 1.0000 - val_loss: 4.8681 - val_categorical_accuracy: 0.3636
Epoch 2

Epoch 49/100
72/75 [===========================>..] - ETA: 0s - loss: 2.7465 - categorical_accuracy: 1.0000
Epoch 00049: val_categorical_accuracy did not improve from 0.45455
75/75 [==============================] - 1s 11ms/sample - loss: 2.7461 - categorical_accuracy: 1.0000 - val_loss: 4.9929 - val_categorical_accuracy: 0.3182
Epoch 50/100
74/75 [============================>.] - ETA: 0s - loss: 2.7443 - categorical_accuracy: 1.0000
Epoch 00050: val_categorical_accuracy did not improve from 0.45455
75/75 [==============================] - 1s 11ms/sample - loss: 2.7441 - categorical_accuracy: 1.0000 - val_loss: 4.9212 - val_categorical_accuracy: 0.3636
Epoch 51/100
70/75 [===========================>..] - ETA: 0s - loss: 2.7405 - categorical_accuracy: 1.0000
Epoch 00051: val_categorical_accuracy did not improve from 0.45455
75/75 [==============================] - 1s 11ms/sample - loss: 2.7413 - categorical_accuracy: 1.0000 - val_loss: 5.0145 - val_categorical_accuracy: 0.3636
Epoch 5

Epoch 74/100
70/75 [===========================>..] - ETA: 0s - loss: 2.6352 - categorical_accuracy: 1.0000
Epoch 00074: val_categorical_accuracy did not improve from 0.45455
75/75 [==============================] - 1s 11ms/sample - loss: 2.6366 - categorical_accuracy: 1.0000 - val_loss: 4.8872 - val_categorical_accuracy: 0.4091
Epoch 75/100
72/75 [===========================>..] - ETA: 0s - loss: 2.6282 - categorical_accuracy: 1.0000
Epoch 00075: val_categorical_accuracy did not improve from 0.45455
75/75 [==============================] - 1s 11ms/sample - loss: 2.6280 - categorical_accuracy: 1.0000 - val_loss: 4.8489 - val_categorical_accuracy: 0.4091
Epoch 76/100
74/75 [============================>.] - ETA: 0s - loss: 2.6247 - categorical_accuracy: 1.0000
Epoch 00076: val_categorical_accuracy did not improve from 0.45455
75/75 [==============================] - 1s 11ms/sample - loss: 2.6246 - categorical_accuracy: 1.0000 - val_loss: 4.9269 - val_categorical_accuracy: 0.4091
Epoch 7

Epoch 99/100
70/75 [===========================>..] - ETA: 0s - loss: 2.5346 - categorical_accuracy: 1.0000
Epoch 00099: val_categorical_accuracy did not improve from 0.45455
75/75 [==============================] - 1s 11ms/sample - loss: 2.5342 - categorical_accuracy: 1.0000 - val_loss: 4.8776 - val_categorical_accuracy: 0.4091
Epoch 100/100
72/75 [===========================>..] - ETA: 0s - loss: 2.5297 - categorical_accuracy: 1.0000
Epoch 00100: val_categorical_accuracy did not improve from 0.45455
22/22 [==============================] - 0s 2ms/sample - loss: 4.8829 - categorical_accuracy: 0.4091
Test Accuracy = 0.4090909
22/22 [==============================] - 0s 8ms/sample

=============================== Confusion_matrix for data with overlap ratio of 50% is as below ===============================

[[0 1 0 1 0 1 0 0 0]
 [0 0 0 0 0 1 1 0 0]
 [0 0 0 2 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0]
 [2 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 5 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0

(224, 103, 24, 24, 1) (61, 103, 24, 24, 1) (224,) (61,)
Total samples per class: [0, 49, 14, 5, 13, 26, 0, 10, 0, 30, 71, 17, 9, 31, 5, 5], Total number of samples is 285.

unique classes in Ytest: [ 2  3  4  5  6  8 10 11 12 13 14 15 16], Total number of samples in Ytest is 61.
number of samples per class in Ytest: [10  3  1  3  6  2  6 15  4  2  7  1  1]

Xtrain => (224, 103, 24, 24, 1)
Xtest  => (61, 103, 24, 24, 1)
Ytrain => (224, 13)
Ytest  => (61, 13)

Model: "3D-SRNet"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_2[0][0]                    
________________________

Train on 224 samples, validate on 61 samples
Epoch 1/100
220/224 [============================>.] - ETA: 0s - loss: 5.8387 - categorical_accuracy: 0.2364
Epoch 00001: val_categorical_accuracy improved from -inf to 0.11475, saving model to ..\..\Trained Models\Full_Model\Indian_Pines\Full_Model_best_Indian_Pines_overlap_ratio_75_percent.h5
224/224 [==============================] - 6s 28ms/sample - loss: 5.8293 - categorical_accuracy: 0.2321 - val_loss: 6.4213 - val_categorical_accuracy: 0.1148
Epoch 2/100
220/224 [============================>.] - ETA: 0s - loss: 5.0241 - categorical_accuracy: 0.2955
Epoch 00002: val_categorical_accuracy did not improve from 0.11475
224/224 [==============================] - 1s 6ms/sample - loss: 5.0225 - categorical_accuracy: 0.2991 - val_loss: 6.1687 - val_categorical_accuracy: 0.1148
Epoch 3/100
212/224 [===========================>..] - ETA: 0s - loss: 4.8510 - categorical_accuracy: 0.3632
Epoch 00003: val_categorical_accuracy did not improve from 

216/224 [===========================>..] - ETA: 0s - loss: 3.0944 - categorical_accuracy: 0.9815
Epoch 00023: val_categorical_accuracy did not improve from 0.54098
224/224 [==============================] - 1s 6ms/sample - loss: 3.0963 - categorical_accuracy: 0.9821 - val_loss: 4.1409 - val_categorical_accuracy: 0.5246
Epoch 24/100
212/224 [===========================>..] - ETA: 0s - loss: 3.0641 - categorical_accuracy: 0.9764
Epoch 00024: val_categorical_accuracy improved from 0.54098 to 0.57377, saving model to ..\..\Trained Models\Full_Model\Indian_Pines\Full_Model_best_Indian_Pines_overlap_ratio_75_percent.h5
224/224 [==============================] - 1s 6ms/sample - loss: 3.0623 - categorical_accuracy: 0.9732 - val_loss: 4.0995 - val_categorical_accuracy: 0.5738
Epoch 25/100
220/224 [============================>.] - ETA: 0s - loss: 3.0127 - categorical_accuracy: 0.9773
Epoch 00025: val_categorical_accuracy did not improve from 0.57377
224/224 [==============================] - 1s

212/224 [===========================>..] - ETA: 0s - loss: 2.6733 - categorical_accuracy: 1.0000
Epoch 00046: val_categorical_accuracy did not improve from 0.67213
224/224 [==============================] - 1s 6ms/sample - loss: 2.6734 - categorical_accuracy: 1.0000 - val_loss: 3.9762 - val_categorical_accuracy: 0.5738
Epoch 47/100
220/224 [============================>.] - ETA: 0s - loss: 2.6746 - categorical_accuracy: 0.9955
Epoch 00047: val_categorical_accuracy did not improve from 0.67213
224/224 [==============================] - 1s 6ms/sample - loss: 2.6738 - categorical_accuracy: 0.9955 - val_loss: 3.9225 - val_categorical_accuracy: 0.6721
Epoch 48/100
216/224 [===========================>..] - ETA: 0s - loss: 2.6550 - categorical_accuracy: 1.0000
Epoch 00048: val_categorical_accuracy did not improve from 0.67213
224/224 [==============================] - 1s 6ms/sample - loss: 2.6545 - categorical_accuracy: 1.0000 - val_loss: 3.9430 - val_categorical_accuracy: 0.6557
Epoch 49/10

Epoch 71/100
220/224 [============================>.] - ETA: 0s - loss: 2.5039 - categorical_accuracy: 1.0000
Epoch 00071: val_categorical_accuracy did not improve from 0.67213
224/224 [==============================] - 1s 6ms/sample - loss: 2.5037 - categorical_accuracy: 1.0000 - val_loss: 3.8485 - val_categorical_accuracy: 0.6393
Epoch 72/100
216/224 [===========================>..] - ETA: 0s - loss: 2.4968 - categorical_accuracy: 1.0000
Epoch 00072: val_categorical_accuracy did not improve from 0.67213
224/224 [==============================] - 1s 6ms/sample - loss: 2.4965 - categorical_accuracy: 1.0000 - val_loss: 3.8760 - val_categorical_accuracy: 0.6230
Epoch 73/100
216/224 [===========================>..] - ETA: 0s - loss: 2.4915 - categorical_accuracy: 1.0000
Epoch 00073: val_categorical_accuracy did not improve from 0.67213
224/224 [==============================] - 1s 6ms/sample - loss: 2.4912 - categorical_accuracy: 1.0000 - val_loss: 4.0156 - val_categorical_accuracy: 0.573

Epoch 96/100
212/224 [===========================>..] - ETA: 0s - loss: 2.3627 - categorical_accuracy: 1.0000
Epoch 00096: val_categorical_accuracy did not improve from 0.67213
224/224 [==============================] - 1s 6ms/sample - loss: 2.3629 - categorical_accuracy: 1.0000 - val_loss: 3.8051 - val_categorical_accuracy: 0.6066
Epoch 97/100
220/224 [============================>.] - ETA: 0s - loss: 2.3576 - categorical_accuracy: 1.0000
Epoch 00097: val_categorical_accuracy did not improve from 0.67213
224/224 [==============================] - 1s 6ms/sample - loss: 2.3575 - categorical_accuracy: 1.0000 - val_loss: 3.8424 - val_categorical_accuracy: 0.6393
Epoch 98/100
212/224 [===========================>..] - ETA: 0s - loss: 2.3521 - categorical_accuracy: 1.0000
Epoch 00098: val_categorical_accuracy did not improve from 0.67213
224/224 [==============================] - 1s 6ms/sample - loss: 2.3520 - categorical_accuracy: 1.0000 - val_loss: 3.8219 - val_categorical_accuracy: 0.639

(639, 103, 24, 24, 1) (169, 103, 24, 24, 1) (639,) (169,)
Total samples per class: [6, 135, 36, 11, 33, 77, 4, 29, 4, 83, 216, 43, 21, 89, 11, 10], Total number of samples is 808.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 169.
number of samples per class in Ytest: [ 2 27  8  3  7 16  1  6  1 17 44  9  5 18  3  2]

Xtrain => (639, 103, 24, 24, 1)
Xtest  => (169, 103, 24, 24, 1)
Ytrain => (639, 16)
Ytest  => (169, 16)

Model: "3D-SRNet"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_3[0][0]                

Train on 639 samples, validate on 169 samples
Epoch 1/100
624/639 [============================>.] - ETA: 0s - loss: 5.7111 - categorical_accuracy: 0.2756
Epoch 00001: val_categorical_accuracy improved from -inf to 0.13018, saving model to ..\..\Trained Models\Full_Model\Indian_Pines\Full_Model_best_Indian_Pines_overlap_ratio_85_percent.h5
639/639 [==============================] - 9s 13ms/sample - loss: 5.7002 - categorical_accuracy: 0.2754 - val_loss: 6.1094 - val_categorical_accuracy: 0.1302
Epoch 2/100
632/639 [============================>.] - ETA: 0s - loss: 4.7821 - categorical_accuracy: 0.3892
Epoch 00002: val_categorical_accuracy did not improve from 0.13018
639/639 [==============================] - 2s 3ms/sample - loss: 4.7781 - categorical_accuracy: 0.3881 - val_loss: 5.3868 - val_categorical_accuracy: 0.0473
Epoch 3/100
616/639 [===========================>..] - ETA: 0s - loss: 4.5330 - categorical_accuracy: 0.5114
Epoch 00003: val_categorical_accuracy did not improve from

624/639 [============================>.] - ETA: 0s - loss: 2.9459 - categorical_accuracy: 0.9728
Epoch 00023: val_categorical_accuracy did not improve from 0.57396
639/639 [==============================] - 2s 3ms/sample - loss: 2.9454 - categorical_accuracy: 0.9734 - val_loss: 4.2275 - val_categorical_accuracy: 0.5444
Epoch 24/100
632/639 [============================>.] - ETA: 0s - loss: 2.9053 - categorical_accuracy: 0.9826
Epoch 00024: val_categorical_accuracy improved from 0.57396 to 0.59172, saving model to ..\..\Trained Models\Full_Model\Indian_Pines\Full_Model_best_Indian_Pines_overlap_ratio_85_percent.h5
639/639 [==============================] - 3s 4ms/sample - loss: 2.9045 - categorical_accuracy: 0.9828 - val_loss: 4.0893 - val_categorical_accuracy: 0.5917
Epoch 25/100
616/639 [===========================>..] - ETA: 0s - loss: 2.8828 - categorical_accuracy: 0.9789
Epoch 00025: val_categorical_accuracy did not improve from 0.59172
639/639 [==============================] - 2s

624/639 [============================>.] - ETA: 0s - loss: 2.5727 - categorical_accuracy: 1.0000
Epoch 00046: val_categorical_accuracy did not improve from 0.64497
639/639 [==============================] - 2s 3ms/sample - loss: 2.5737 - categorical_accuracy: 1.0000 - val_loss: 3.9808 - val_categorical_accuracy: 0.5740
Epoch 47/100
616/639 [===========================>..] - ETA: 0s - loss: 2.5679 - categorical_accuracy: 1.0000
Epoch 00047: val_categorical_accuracy did not improve from 0.64497
639/639 [==============================] - 2s 3ms/sample - loss: 2.5673 - categorical_accuracy: 1.0000 - val_loss: 4.0192 - val_categorical_accuracy: 0.5562
Epoch 48/100
632/639 [============================>.] - ETA: 0s - loss: 2.5570 - categorical_accuracy: 1.0000
Epoch 00048: val_categorical_accuracy improved from 0.64497 to 0.66272, saving model to ..\..\Trained Models\Full_Model\Indian_Pines\Full_Model_best_Indian_Pines_overlap_ratio_85_percent.h5
639/639 [==============================] - 2s

Epoch 70/100
632/639 [============================>.] - ETA: 0s - loss: 2.3732 - categorical_accuracy: 1.0000
Epoch 00070: val_categorical_accuracy did not improve from 0.66272
639/639 [==============================] - 2s 3ms/sample - loss: 2.3732 - categorical_accuracy: 1.0000 - val_loss: 3.8610 - val_categorical_accuracy: 0.6154
Epoch 71/100
624/639 [============================>.] - ETA: 0s - loss: 2.3643 - categorical_accuracy: 1.0000
Epoch 00071: val_categorical_accuracy did not improve from 0.66272
639/639 [==============================] - 2s 3ms/sample - loss: 2.3643 - categorical_accuracy: 1.0000 - val_loss: 3.8922 - val_categorical_accuracy: 0.5976
Epoch 72/100
624/639 [============================>.] - ETA: 0s - loss: 2.3616 - categorical_accuracy: 1.0000
Epoch 00072: val_categorical_accuracy did not improve from 0.66272
639/639 [==============================] - 2s 3ms/sample - loss: 2.3617 - categorical_accuracy: 1.0000 - val_loss: 3.8692 - val_categorical_accuracy: 0.574

Epoch 95/100
632/639 [============================>.] - ETA: 0s - loss: 2.1940 - categorical_accuracy: 1.0000
Epoch 00095: val_categorical_accuracy did not improve from 0.66272
639/639 [==============================] - 2s 3ms/sample - loss: 2.1940 - categorical_accuracy: 1.0000 - val_loss: 3.6972 - val_categorical_accuracy: 0.6331
Epoch 96/100
624/639 [============================>.] - ETA: 0s - loss: 2.1886 - categorical_accuracy: 1.0000
Epoch 00096: val_categorical_accuracy did not improve from 0.66272
639/639 [==============================] - 2s 3ms/sample - loss: 2.1888 - categorical_accuracy: 1.0000 - val_loss: 3.7373 - val_categorical_accuracy: 0.5858
Epoch 97/100
616/639 [===========================>..] - ETA: 0s - loss: 2.1821 - categorical_accuracy: 1.0000
Epoch 00097: val_categorical_accuracy did not improve from 0.66272
639/639 [==============================] - 2s 3ms/sample - loss: 2.1820 - categorical_accuracy: 1.0000 - val_loss: 3.8107 - val_categorical_accuracy: 0.574

(3109, 103, 24, 24, 1) (785, 103, 24, 24, 1) (3109,) (785,)
Total samples per class: [24, 668, 177, 45, 137, 365, 14, 141, 10, 408, 1067, 181, 101, 465, 46, 45], Total number of samples is 3894.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 785.
number of samples per class in Ytest: [  5 134  36   9  28  73   3  29   2  82 214  37  21  93  10   9]

Xtrain => (3109, 103, 24, 24, 1)
Xtest  => (785, 103, 24, 24, 1)
Ytrain => (3109, 16)
Ytest  => (785, 16)

Model: "3D-SRNet"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_4 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336    

Train on 3109 samples, validate on 785 samples
Epoch 1/100
3088/3109 [============================>.] - ETA: 0s - loss: 4.9185 - categorical_accuracy: 0.4284
Epoch 00001: val_categorical_accuracy improved from -inf to 0.03822, saving model to ..\..\Trained Models\Full_Model\Indian_Pines\Full_Model_best_Indian_Pines_overlap_ratio_95_percent.h5
3109/3109 [==============================] - 15s 5ms/sample - loss: 4.9139 - categorical_accuracy: 0.4294 - val_loss: 5.4153 - val_categorical_accuracy: 0.0382
Epoch 2/100
3088/3109 [============================>.] - ETA: 0s - loss: 4.1447 - categorical_accuracy: 0.6185
Epoch 00002: val_categorical_accuracy improved from 0.03822 to 0.20255, saving model to ..\..\Trained Models\Full_Model\Indian_Pines\Full_Model_best_Indian_Pines_overlap_ratio_95_percent.h5
3109/3109 [==============================] - 6s 2ms/sample - loss: 4.1446 - categorical_accuracy: 0.6195 - val_loss: 5.3445 - val_categorical_accuracy: 0.2025
Epoch 3/100
3088/3109 [============

Epoch 22/100
3088/3109 [============================>.] - ETA: 0s - loss: 2.5061 - categorical_accuracy: 0.9981
Epoch 00022: val_categorical_accuracy did not improve from 0.73631
3109/3109 [==============================] - 6s 2ms/sample - loss: 2.5061 - categorical_accuracy: 0.9981 - val_loss: 3.4684 - val_categorical_accuracy: 0.6943
Epoch 23/100
3104/3109 [============================>.] - ETA: 0s - loss: 2.4820 - categorical_accuracy: 0.9981
Epoch 00023: val_categorical_accuracy improved from 0.73631 to 0.73885, saving model to ..\..\Trained Models\Full_Model\Indian_Pines\Full_Model_best_Indian_Pines_overlap_ratio_95_percent.h5
3109/3109 [==============================] - 6s 2ms/sample - loss: 2.4819 - categorical_accuracy: 0.9981 - val_loss: 3.2130 - val_categorical_accuracy: 0.7389
Epoch 24/100
3088/3109 [============================>.] - ETA: 0s - loss: 2.4612 - categorical_accuracy: 0.9990 ETA: 0s - loss: 2.4614 - categorical_accuracy: 
Epoch 00024: val_categorical_accuracy did

Epoch 45/100
3088/3109 [============================>.] - ETA: 0s - loss: 2.0880 - categorical_accuracy: 1.0000
Epoch 00045: val_categorical_accuracy did not improve from 0.76306
3109/3109 [==============================] - 6s 2ms/sample - loss: 2.0880 - categorical_accuracy: 1.0000 - val_loss: 3.1233 - val_categorical_accuracy: 0.7172
Epoch 46/100
3104/3109 [============================>.] - ETA: 0s - loss: 2.0736 - categorical_accuracy: 1.0000
Epoch 00046: val_categorical_accuracy improved from 0.76306 to 0.76433, saving model to ..\..\Trained Models\Full_Model\Indian_Pines\Full_Model_best_Indian_Pines_overlap_ratio_95_percent.h5
3109/3109 [==============================] - 6s 2ms/sample - loss: 2.0736 - categorical_accuracy: 1.0000 - val_loss: 2.8622 - val_categorical_accuracy: 0.7643
Epoch 47/100
3104/3109 [============================>.] - ETA: 0s - loss: 2.0578 - categorical_accuracy: 1.0000
Epoch 00047: val_categorical_accuracy did not improve from 0.76433
3109/3109 [===========

Epoch 68/100
3088/3109 [============================>.] - ETA: 0s - loss: 1.7721 - categorical_accuracy: 1.0000
Epoch 00068: val_categorical_accuracy did not improve from 0.77452
3109/3109 [==============================] - 6s 2ms/sample - loss: 1.7720 - categorical_accuracy: 1.0000 - val_loss: 2.5459 - val_categorical_accuracy: 0.7707
Epoch 69/100
3072/3109 [============================>.] - ETA: 0s - loss: 1.7605 - categorical_accuracy: 1.0000
Epoch 00069: val_categorical_accuracy improved from 0.77452 to 0.77962, saving model to ..\..\Trained Models\Full_Model\Indian_Pines\Full_Model_best_Indian_Pines_overlap_ratio_95_percent.h5
3109/3109 [==============================] - 6s 2ms/sample - loss: 1.7605 - categorical_accuracy: 1.0000 - val_loss: 2.5476 - val_categorical_accuracy: 0.7796
Epoch 70/100
3088/3109 [============================>.] - ETA: 0s - loss: 1.7477 - categorical_accuracy: 1.0000
Epoch 00070: val_categorical_accuracy did not improve from 0.77962
3109/3109 [===========

Epoch 92/100
3104/3109 [============================>.] - ETA: 0s - loss: 1.5058 - categorical_accuracy: 1.0000
Epoch 00092: val_categorical_accuracy did not improve from 0.77962
3109/3109 [==============================] - 6s 2ms/sample - loss: 1.5057 - categorical_accuracy: 1.0000 - val_loss: 2.3339 - val_categorical_accuracy: 0.7656
Epoch 93/100
3088/3109 [============================>.] - ETA: 0s - loss: 1.4954 - categorical_accuracy: 1.0000
Epoch 00093: val_categorical_accuracy did not improve from 0.77962
3109/3109 [==============================] - 6s 2ms/sample - loss: 1.4954 - categorical_accuracy: 1.0000 - val_loss: 2.3676 - val_categorical_accuracy: 0.7694
Epoch 94/100
3104/3109 [============================>.] - ETA: 0s - loss: 1.4858 - categorical_accuracy: 1.0000
Epoch 00094: val_categorical_accuracy did not improve from 0.77962
3109/3109 [==============================] - 6s 2ms/sample - loss: 1.4858 - categorical_accuracy: 1.0000 - val_loss: 2.2892 - val_categorical_acc

In [5]:
Acc_Table

0             1
0  Test Accuracy Table  Indian_Pines
1      Data_Overlap_50       40.9091
2      Data_Overlap_75       63.9344
3      Data_Overlap_85        60.355
4      Data_Overlap_95       77.0701