# Salinas to Salinas

In [1]:
from Transfer_Model_Utils import *
import scipy.io as sio

In [2]:
uSalinas = sio.loadmat('..\\..\\Salinas\\Salinas_corrected.mat')
gt_uSalinas = sio.loadmat('..\\..\\Salinas\\Salinas_gt.mat')
data_SA = uSalinas['salinas_corrected']
gt_SA = gt_uSalinas['salinas_gt']
print(data_SA.shape, gt_SA.shape)
data_SA = np.moveaxis(data_SA, 2, 0)
print(data_SA.shape, gt_SA.shape)

(512, 217, 204) (512, 217)
(204, 512, 217) (512, 217)


In [3]:
values,counts = np.unique(gt_SA, return_counts=True)
print(values,counts)
range_of_class = list(values)
if 0 in range_of_class:
    range_of_class.pop(0)
range_of_class

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16] [56975  2009  3726  1976  1394  2678  3959  3579 11271  6203  3278  1068
  1927   916  1070  7268  1807]


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

In [4]:
Acc_Tbl = Transfer(overlap_ratio_List_for_Target = [25, 50, 75, 95],
                   overlap_ratio_List_for_Source = [25, 50, 75, 95],
                   epochs_list = [300, 300, 300, 300],
                   batch_size_list = [16, 32, 64, 128],
                   range_of_class = range_of_class,
                   Cube_size = 25,
                   Data = data_SA,
                   Gt = gt_SA,
                   Train_Test_split = 80,
                   channel = 103,
                   Source_data_name = 'Salinas', 
                   Target_data_name = 'Salinas',
                   Verbosity = 0)

               0           1           2           3           4
0  Test Accuracy  Salinas_25  Salinas_50  Salinas_75  Salinas_95
1     Salinas_25        None        None        None        None
2     Salinas_50        None        None        None        None
3     Salinas_75        None        None        None        None
4     Salinas_95        None        None        None        None


= Source Model with overlap ratio of 25% will be transfered to Target Data with overlap ratio of 25%, Source Model shown below =


Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        i

(174, 103, 24, 24, 1) (51, 103, 24, 24, 1) (174,) (51,)
Total samples per class: [9, 16, 8, 10, 17, 17, 15, 40, 23, 14, 6, 9, 7, 7, 23, 4], Total number of samples is 225.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 51.
number of samples per class in Ytest: [2 4 2 2 4 4 3 8 5 3 2 2 2 2 5 1]

Xtrain_transfer => (174, 64)
Xtest_transfer  => (174, 64)
Ytrain => (174, 16)
Ytest  => (51, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainable params: 20,752
Non-trai


Epoch 00096: val_categorical_accuracy did not improve from 0.76471

Epoch 00097: val_categorical_accuracy did not improve from 0.76471

Epoch 00098: val_categorical_accuracy did not improve from 0.76471

Epoch 00099: val_categorical_accuracy did not improve from 0.76471

Epoch 00100: val_categorical_accuracy did not improve from 0.76471

Epoch 00101: val_categorical_accuracy did not improve from 0.76471

Epoch 00102: val_categorical_accuracy did not improve from 0.76471

Epoch 00103: val_categorical_accuracy did not improve from 0.76471

Epoch 00104: val_categorical_accuracy did not improve from 0.76471

Epoch 00105: val_categorical_accuracy did not improve from 0.76471

Epoch 00106: val_categorical_accuracy did not improve from 0.76471

Epoch 00107: val_categorical_accuracy did not improve from 0.76471

Epoch 00108: val_categorical_accuracy did not improve from 0.76471

Epoch 00109: val_categorical_accuracy did not improve from 0.76471

Epoch 00110: val_categorical_accuracy did not i


Epoch 00217: val_categorical_accuracy did not improve from 0.76471

Epoch 00218: val_categorical_accuracy did not improve from 0.76471

Epoch 00219: val_categorical_accuracy did not improve from 0.76471

Epoch 00220: val_categorical_accuracy did not improve from 0.76471

Epoch 00221: val_categorical_accuracy did not improve from 0.76471

Epoch 00222: val_categorical_accuracy did not improve from 0.76471

Epoch 00223: val_categorical_accuracy did not improve from 0.76471

Epoch 00224: val_categorical_accuracy did not improve from 0.76471

Epoch 00225: val_categorical_accuracy did not improve from 0.76471

Epoch 00226: val_categorical_accuracy did not improve from 0.76471

Epoch 00227: val_categorical_accuracy did not improve from 0.76471

Epoch 00228: val_categorical_accuracy did not improve from 0.76471

Epoch 00229: val_categorical_accuracy did not improve from 0.76471

Epoch 00230: val_categorical_accuracy did not improve from 0.76471

Epoch 00231: val_categorical_accuracy did not i

(338, 103, 24, 24, 1) (91, 103, 24, 24, 1) (338,) (91,)
Total samples per class: [15, 32, 17, 14, 26, 35, 30, 80, 51, 27, 10, 17, 9, 10, 47, 9], Total number of samples is 429.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 91.
number of samples per class in Ytest: [ 3  7  4  3  6  7  6 16 11  6  2  4  2  2 10  2]

Xtrain_transfer => (338, 64)
Xtest_transfer  => (338, 64)
Ytrain => (338, 16)
Ytest  => (91, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainable pa


Epoch 00087: val_categorical_accuracy did not improve from 0.81319

Epoch 00088: val_categorical_accuracy did not improve from 0.81319

Epoch 00089: val_categorical_accuracy did not improve from 0.81319

Epoch 00090: val_categorical_accuracy did not improve from 0.81319

Epoch 00091: val_categorical_accuracy did not improve from 0.81319

Epoch 00092: val_categorical_accuracy did not improve from 0.81319

Epoch 00093: val_categorical_accuracy did not improve from 0.81319

Epoch 00094: val_categorical_accuracy did not improve from 0.81319

Epoch 00095: val_categorical_accuracy did not improve from 0.81319

Epoch 00096: val_categorical_accuracy did not improve from 0.81319

Epoch 00097: val_categorical_accuracy did not improve from 0.81319

Epoch 00098: val_categorical_accuracy did not improve from 0.81319

Epoch 00099: val_categorical_accuracy did not improve from 0.81319

Epoch 00100: val_categorical_accuracy did not improve from 0.81319

Epoch 00101: val_categorical_accuracy did not i


Epoch 00206: val_categorical_accuracy did not improve from 0.82418

Epoch 00207: val_categorical_accuracy did not improve from 0.82418

Epoch 00208: val_categorical_accuracy did not improve from 0.82418

Epoch 00209: val_categorical_accuracy did not improve from 0.82418

Epoch 00210: val_categorical_accuracy did not improve from 0.82418

Epoch 00211: val_categorical_accuracy did not improve from 0.82418

Epoch 00212: val_categorical_accuracy did not improve from 0.82418

Epoch 00213: val_categorical_accuracy did not improve from 0.82418

Epoch 00214: val_categorical_accuracy did not improve from 0.82418

Epoch 00215: val_categorical_accuracy did not improve from 0.82418

Epoch 00216: val_categorical_accuracy did not improve from 0.82418

Epoch 00217: val_categorical_accuracy did not improve from 0.82418

Epoch 00218: val_categorical_accuracy did not improve from 0.82418

Epoch 00219: val_categorical_accuracy did not improve from 0.82418

Epoch 00220: val_categorical_accuracy did not i

(1121, 103, 24, 24, 1) (288, 103, 24, 24, 1) (1121,) (288,)
Total samples per class: [47, 104, 56, 50, 81, 109, 96, 287, 168, 83, 30, 52, 30, 30, 162, 24], Total number of samples is 1409.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 288.
number of samples per class in Ytest: [10 21 12 10 17 22 20 58 34 17  6 11  6  6 33  5]

Xtrain_transfer => (1121, 64)
Xtest_transfer  => (1121, 64)
Ytrain => (1121, 16)
Ytest  => (288, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20


Epoch 00066: val_categorical_accuracy did not improve from 0.78125

Epoch 00067: val_categorical_accuracy did not improve from 0.78125

Epoch 00068: val_categorical_accuracy did not improve from 0.78125

Epoch 00069: val_categorical_accuracy did not improve from 0.78125

Epoch 00070: val_categorical_accuracy did not improve from 0.78125

Epoch 00071: val_categorical_accuracy did not improve from 0.78125

Epoch 00072: val_categorical_accuracy did not improve from 0.78125

Epoch 00073: val_categorical_accuracy did not improve from 0.78125

Epoch 00074: val_categorical_accuracy did not improve from 0.78125

Epoch 00075: val_categorical_accuracy did not improve from 0.78125

Epoch 00076: val_categorical_accuracy did not improve from 0.78125

Epoch 00077: val_categorical_accuracy did not improve from 0.78125

Epoch 00078: val_categorical_accuracy did not improve from 0.78125

Epoch 00079: val_categorical_accuracy did not improve from 0.78125

Epoch 00080: val_categorical_accuracy did not i


Epoch 00173: val_categorical_accuracy did not improve from 0.80556

Epoch 00174: val_categorical_accuracy did not improve from 0.80556

Epoch 00175: val_categorical_accuracy did not improve from 0.80556

Epoch 00176: val_categorical_accuracy did not improve from 0.80556

Epoch 00177: val_categorical_accuracy did not improve from 0.80556

Epoch 00178: val_categorical_accuracy did not improve from 0.80556

Epoch 00179: val_categorical_accuracy did not improve from 0.80556

Epoch 00180: val_categorical_accuracy did not improve from 0.80556

Epoch 00181: val_categorical_accuracy did not improve from 0.80556

Epoch 00182: val_categorical_accuracy did not improve from 0.80556

Epoch 00183: val_categorical_accuracy did not improve from 0.80556

Epoch 00184: val_categorical_accuracy did not improve from 0.80556

Epoch 00185: val_categorical_accuracy did not improve from 0.80556

Epoch 00186: val_categorical_accuracy did not improve from 0.80556

Epoch 00187: val_categorical_accuracy did not i


Epoch 00284: val_categorical_accuracy did not improve from 0.82292

Epoch 00285: val_categorical_accuracy did not improve from 0.82292

Epoch 00286: val_categorical_accuracy did not improve from 0.82292

Epoch 00287: val_categorical_accuracy did not improve from 0.82292

Epoch 00288: val_categorical_accuracy did not improve from 0.82292

Epoch 00289: val_categorical_accuracy improved from 0.82292 to 0.82986, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_75_With_source_data_as_Salinas_overlap_ratio_25_percent.h5

Epoch 00290: val_categorical_accuracy did not improve from 0.82986

Epoch 00291: val_categorical_accuracy did not improve from 0.82986

Epoch 00292: val_categorical_accuracy did not improve from 0.82986

Epoch 00293: val_categorical_accuracy did not improve from 0.82986

Epoch 00294: val_categorical_accuracy did not improve from 0.82986

Epoch 00295: val_categorical_accuracy did not i

(16239, 103, 24, 24, 1) (4068, 103, 24, 24, 1) (16239,) (4068,)
Total samples per class: [635, 1619, 663, 632, 1143, 1512, 1490, 4327, 2571, 1092, 357, 650, 306, 349, 2620, 341], Total number of samples is 20307.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 4068.
number of samples per class in Ytest: [127 324 133 127 229 303 298 866 515 219  72 130  62  70 524  69]

Xtrain_transfer => (16239, 64)
Xtest_transfer  => (16239, 64)
Ytrain => (16239, 16)
Ytest  => (4068, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 1


Epoch 00049: val_categorical_accuracy did not improve from 0.82104

Epoch 00050: val_categorical_accuracy did not improve from 0.82104

Epoch 00051: val_categorical_accuracy improved from 0.82104 to 0.82129, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_25_percent.h5

Epoch 00052: val_categorical_accuracy did not improve from 0.82129

Epoch 00053: val_categorical_accuracy improved from 0.82129 to 0.82498, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_25_percent.h5

Epoch 00054: val_categorical_accuracy improved from 0.82498 to 0.82645, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Salinas_overlap_


Epoch 00131: val_categorical_accuracy did not improve from 0.84636

Epoch 00132: val_categorical_accuracy did not improve from 0.84636

Epoch 00133: val_categorical_accuracy did not improve from 0.84636

Epoch 00134: val_categorical_accuracy did not improve from 0.84636

Epoch 00135: val_categorical_accuracy improved from 0.84636 to 0.84661, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_25_percent.h5

Epoch 00136: val_categorical_accuracy did not improve from 0.84661

Epoch 00137: val_categorical_accuracy did not improve from 0.84661

Epoch 00138: val_categorical_accuracy did not improve from 0.84661

Epoch 00139: val_categorical_accuracy did not improve from 0.84661

Epoch 00140: val_categorical_accuracy did not improve from 0.84661

Epoch 00141: val_categorical_accuracy did not improve from 0.84661

Epoch 00142: val_categorical_accuracy did not i


Epoch 00231: val_categorical_accuracy improved from 0.85939 to 0.86037, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_25_percent.h5

Epoch 00232: val_categorical_accuracy did not improve from 0.86037

Epoch 00233: val_categorical_accuracy did not improve from 0.86037

Epoch 00234: val_categorical_accuracy did not improve from 0.86037

Epoch 00235: val_categorical_accuracy did not improve from 0.86037

Epoch 00236: val_categorical_accuracy did not improve from 0.86037

Epoch 00237: val_categorical_accuracy did not improve from 0.86037

Epoch 00238: val_categorical_accuracy did not improve from 0.86037

Epoch 00239: val_categorical_accuracy did not improve from 0.86037

Epoch 00240: val_categorical_accuracy did not improve from 0.86037

Epoch 00241: val_categorical_accuracy improved from 0.86037 to 0.86062, saving model to ..\..\Trained Models\Transf

(174, 103, 24, 24, 1) (51, 103, 24, 24, 1) (174,) (51,)
Total samples per class: [9, 16, 8, 10, 17, 17, 15, 40, 23, 14, 6, 9, 7, 7, 23, 4], Total number of samples is 225.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 51.
number of samples per class in Ytest: [2 4 2 2 4 4 3 8 5 3 2 2 2 2 5 1]

Xtrain_transfer => (174, 64)
Xtest_transfer  => (174, 64)
Ytrain => (174, 16)
Ytest  => (51, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainable params: 20,752
Non-trai


Epoch 00098: val_categorical_accuracy did not improve from 0.86275

Epoch 00099: val_categorical_accuracy did not improve from 0.86275

Epoch 00100: val_categorical_accuracy did not improve from 0.86275

Epoch 00101: val_categorical_accuracy did not improve from 0.86275

Epoch 00102: val_categorical_accuracy did not improve from 0.86275

Epoch 00103: val_categorical_accuracy did not improve from 0.86275

Epoch 00104: val_categorical_accuracy improved from 0.86275 to 0.88235, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_25_With_source_data_as_Salinas_overlap_ratio_50_percent.h5

Epoch 00105: val_categorical_accuracy did not improve from 0.88235

Epoch 00106: val_categorical_accuracy did not improve from 0.88235

Epoch 00107: val_categorical_accuracy did not improve from 0.88235

Epoch 00108: val_categorical_accuracy did not improve from 0.88235

Epoch 00109: val_categorical_accuracy did not i


Epoch 00219: val_categorical_accuracy did not improve from 0.88235

Epoch 00220: val_categorical_accuracy did not improve from 0.88235

Epoch 00221: val_categorical_accuracy did not improve from 0.88235

Epoch 00222: val_categorical_accuracy did not improve from 0.88235

Epoch 00223: val_categorical_accuracy did not improve from 0.88235

Epoch 00224: val_categorical_accuracy did not improve from 0.88235

Epoch 00225: val_categorical_accuracy did not improve from 0.88235

Epoch 00226: val_categorical_accuracy did not improve from 0.88235

Epoch 00227: val_categorical_accuracy did not improve from 0.88235

Epoch 00228: val_categorical_accuracy did not improve from 0.88235

Epoch 00229: val_categorical_accuracy did not improve from 0.88235

Epoch 00230: val_categorical_accuracy did not improve from 0.88235

Epoch 00231: val_categorical_accuracy did not improve from 0.88235

Epoch 00232: val_categorical_accuracy did not improve from 0.88235

Epoch 00233: val_categorical_accuracy did not i

(338, 103, 24, 24, 1) (91, 103, 24, 24, 1) (338,) (91,)
Total samples per class: [15, 32, 17, 14, 26, 35, 30, 80, 51, 27, 10, 17, 9, 10, 47, 9], Total number of samples is 429.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 91.
number of samples per class in Ytest: [ 3  7  4  3  6  7  6 16 11  6  2  4  2  2 10  2]

Xtrain_transfer => (338, 64)
Xtest_transfer  => (338, 64)
Ytrain => (338, 16)
Ytest  => (91, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainable pa


Epoch 00092: val_categorical_accuracy did not improve from 0.78022

Epoch 00093: val_categorical_accuracy did not improve from 0.78022

Epoch 00094: val_categorical_accuracy did not improve from 0.78022

Epoch 00095: val_categorical_accuracy did not improve from 0.78022

Epoch 00096: val_categorical_accuracy did not improve from 0.78022

Epoch 00097: val_categorical_accuracy did not improve from 0.78022

Epoch 00098: val_categorical_accuracy did not improve from 0.78022

Epoch 00099: val_categorical_accuracy did not improve from 0.78022

Epoch 00100: val_categorical_accuracy did not improve from 0.78022

Epoch 00101: val_categorical_accuracy did not improve from 0.78022

Epoch 00102: val_categorical_accuracy did not improve from 0.78022

Epoch 00103: val_categorical_accuracy did not improve from 0.78022

Epoch 00104: val_categorical_accuracy did not improve from 0.78022

Epoch 00105: val_categorical_accuracy did not improve from 0.78022

Epoch 00106: val_categorical_accuracy did not i


Epoch 00213: val_categorical_accuracy did not improve from 0.79121

Epoch 00214: val_categorical_accuracy did not improve from 0.79121

Epoch 00215: val_categorical_accuracy did not improve from 0.79121

Epoch 00216: val_categorical_accuracy did not improve from 0.79121

Epoch 00217: val_categorical_accuracy did not improve from 0.79121

Epoch 00218: val_categorical_accuracy did not improve from 0.79121

Epoch 00219: val_categorical_accuracy did not improve from 0.79121

Epoch 00220: val_categorical_accuracy did not improve from 0.79121

Epoch 00221: val_categorical_accuracy did not improve from 0.79121

Epoch 00222: val_categorical_accuracy did not improve from 0.79121

Epoch 00223: val_categorical_accuracy did not improve from 0.79121

Epoch 00224: val_categorical_accuracy did not improve from 0.79121

Epoch 00225: val_categorical_accuracy did not improve from 0.79121

Epoch 00226: val_categorical_accuracy did not improve from 0.79121

Epoch 00227: val_categorical_accuracy did not i

(1121, 103, 24, 24, 1) (288, 103, 24, 24, 1) (1121,) (288,)
Total samples per class: [47, 104, 56, 50, 81, 109, 96, 287, 168, 83, 30, 52, 30, 30, 162, 24], Total number of samples is 1409.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 288.
number of samples per class in Ytest: [10 21 12 10 17 22 20 58 34 17  6 11  6  6 33  5]

Xtrain_transfer => (1121, 64)
Xtest_transfer  => (1121, 64)
Ytrain => (1121, 16)
Ytest  => (288, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20


Epoch 00077: val_categorical_accuracy did not improve from 0.79861

Epoch 00078: val_categorical_accuracy did not improve from 0.79861

Epoch 00079: val_categorical_accuracy did not improve from 0.79861

Epoch 00080: val_categorical_accuracy did not improve from 0.79861

Epoch 00081: val_categorical_accuracy did not improve from 0.79861

Epoch 00082: val_categorical_accuracy did not improve from 0.79861

Epoch 00083: val_categorical_accuracy did not improve from 0.79861

Epoch 00084: val_categorical_accuracy did not improve from 0.79861

Epoch 00085: val_categorical_accuracy did not improve from 0.79861

Epoch 00086: val_categorical_accuracy did not improve from 0.79861

Epoch 00087: val_categorical_accuracy did not improve from 0.79861

Epoch 00088: val_categorical_accuracy did not improve from 0.79861

Epoch 00089: val_categorical_accuracy did not improve from 0.79861

Epoch 00090: val_categorical_accuracy did not improve from 0.79861

Epoch 00091: val_categorical_accuracy did not i


Epoch 00186: val_categorical_accuracy did not improve from 0.81597

Epoch 00187: val_categorical_accuracy did not improve from 0.81597

Epoch 00188: val_categorical_accuracy did not improve from 0.81597

Epoch 00189: val_categorical_accuracy did not improve from 0.81597

Epoch 00190: val_categorical_accuracy did not improve from 0.81597

Epoch 00191: val_categorical_accuracy did not improve from 0.81597

Epoch 00192: val_categorical_accuracy did not improve from 0.81597

Epoch 00193: val_categorical_accuracy did not improve from 0.81597

Epoch 00194: val_categorical_accuracy did not improve from 0.81597

Epoch 00195: val_categorical_accuracy did not improve from 0.81597

Epoch 00196: val_categorical_accuracy did not improve from 0.81597

Epoch 00197: val_categorical_accuracy did not improve from 0.81597

Epoch 00198: val_categorical_accuracy did not improve from 0.81597

Epoch 00199: val_categorical_accuracy did not improve from 0.81597

Epoch 00200: val_categorical_accuracy did not i


Epoch 00300: val_categorical_accuracy did not improve from 0.82986
288/288 [==============================] - 0s 64us/sample - loss: 0.4960 - categorical_accuracy: 0.8194
Test Accuracy = 0.8194444
288/288 [==============================] - 0s 542us/sample

============ Confusion_matrix for data with source overlap ratio of 50 and target overlap ratio of  75 is as below ============

[[10  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1 19  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  9  0  0  1  0  0  0  0]
 [ 0  0  0  9  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  2  0 15  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0 51  0  1  0  0  4  0  1  0]
 [ 0  0  0  0  0  0  0  0 34  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  5 10  0  2  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0]
 

(16239, 103, 24, 24, 1) (4068, 103, 24, 24, 1) (16239,) (4068,)
Total samples per class: [635, 1619, 663, 632, 1143, 1512, 1490, 4327, 2571, 1092, 357, 650, 306, 349, 2620, 341], Total number of samples is 20307.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 4068.
number of samples per class in Ytest: [127 324 133 127 229 303 298 866 515 219  72 130  62  70 524  69]

Xtrain_transfer => (16239, 64)
Xtest_transfer  => (16239, 64)
Ytrain => (16239, 16)
Ytest  => (4068, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 1


Epoch 00052: val_categorical_accuracy did not improve from 0.82940

Epoch 00053: val_categorical_accuracy did not improve from 0.82940

Epoch 00054: val_categorical_accuracy improved from 0.82940 to 0.83481, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_50_percent.h5

Epoch 00055: val_categorical_accuracy did not improve from 0.83481

Epoch 00056: val_categorical_accuracy did not improve from 0.83481

Epoch 00057: val_categorical_accuracy did not improve from 0.83481

Epoch 00058: val_categorical_accuracy did not improve from 0.83481

Epoch 00059: val_categorical_accuracy did not improve from 0.83481

Epoch 00060: val_categorical_accuracy did not improve from 0.83481

Epoch 00061: val_categorical_accuracy did not improve from 0.83481

Epoch 00062: val_categorical_accuracy did not improve from 0.83481

Epoch 00063: val_categorical_accuracy did not i


Epoch 00137: val_categorical_accuracy did not improve from 0.84980

Epoch 00138: val_categorical_accuracy did not improve from 0.84980

Epoch 00139: val_categorical_accuracy did not improve from 0.84980

Epoch 00140: val_categorical_accuracy did not improve from 0.84980

Epoch 00141: val_categorical_accuracy did not improve from 0.84980

Epoch 00142: val_categorical_accuracy did not improve from 0.84980

Epoch 00143: val_categorical_accuracy did not improve from 0.84980

Epoch 00144: val_categorical_accuracy did not improve from 0.84980

Epoch 00145: val_categorical_accuracy did not improve from 0.84980

Epoch 00146: val_categorical_accuracy did not improve from 0.84980

Epoch 00147: val_categorical_accuracy did not improve from 0.84980

Epoch 00148: val_categorical_accuracy did not improve from 0.84980

Epoch 00149: val_categorical_accuracy did not improve from 0.84980

Epoch 00150: val_categorical_accuracy did not improve from 0.84980

Epoch 00151: val_categorical_accuracy improved 


Epoch 00231: val_categorical_accuracy did not improve from 0.86062

Epoch 00232: val_categorical_accuracy did not improve from 0.86062

Epoch 00233: val_categorical_accuracy did not improve from 0.86062

Epoch 00234: val_categorical_accuracy did not improve from 0.86062

Epoch 00235: val_categorical_accuracy did not improve from 0.86062

Epoch 00236: val_categorical_accuracy did not improve from 0.86062

Epoch 00237: val_categorical_accuracy did not improve from 0.86062

Epoch 00238: val_categorical_accuracy did not improve from 0.86062

Epoch 00239: val_categorical_accuracy did not improve from 0.86062

Epoch 00240: val_categorical_accuracy did not improve from 0.86062

Epoch 00241: val_categorical_accuracy did not improve from 0.86062

Epoch 00242: val_categorical_accuracy did not improve from 0.86062

Epoch 00243: val_categorical_accuracy did not improve from 0.86062

Epoch 00244: val_categorical_accuracy did not improve from 0.86062

Epoch 00245: val_categorical_accuracy did not i

(174, 103, 24, 24, 1) (51, 103, 24, 24, 1) (174,) (51,)
Total samples per class: [9, 16, 8, 10, 17, 17, 15, 40, 23, 14, 6, 9, 7, 7, 23, 4], Total number of samples is 225.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 51.
number of samples per class in Ytest: [2 4 2 2 4 4 3 8 5 3 2 2 2 2 5 1]

Xtrain_transfer => (174, 64)
Xtest_transfer  => (174, 64)
Ytrain => (174, 16)
Ytest  => (51, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainable params: 20,752
Non-trai


Epoch 00092: val_categorical_accuracy did not improve from 0.92157

Epoch 00093: val_categorical_accuracy did not improve from 0.92157

Epoch 00094: val_categorical_accuracy did not improve from 0.92157

Epoch 00095: val_categorical_accuracy did not improve from 0.92157

Epoch 00096: val_categorical_accuracy did not improve from 0.92157

Epoch 00097: val_categorical_accuracy did not improve from 0.92157

Epoch 00098: val_categorical_accuracy did not improve from 0.92157

Epoch 00099: val_categorical_accuracy did not improve from 0.92157

Epoch 00100: val_categorical_accuracy did not improve from 0.92157

Epoch 00101: val_categorical_accuracy did not improve from 0.92157

Epoch 00102: val_categorical_accuracy did not improve from 0.92157

Epoch 00103: val_categorical_accuracy did not improve from 0.92157

Epoch 00104: val_categorical_accuracy did not improve from 0.92157

Epoch 00105: val_categorical_accuracy did not improve from 0.92157

Epoch 00106: val_categorical_accuracy did not i


Epoch 00210: val_categorical_accuracy did not improve from 0.94118

Epoch 00211: val_categorical_accuracy did not improve from 0.94118

Epoch 00212: val_categorical_accuracy did not improve from 0.94118

Epoch 00213: val_categorical_accuracy did not improve from 0.94118

Epoch 00214: val_categorical_accuracy did not improve from 0.94118

Epoch 00215: val_categorical_accuracy did not improve from 0.94118

Epoch 00216: val_categorical_accuracy did not improve from 0.94118

Epoch 00217: val_categorical_accuracy did not improve from 0.94118

Epoch 00218: val_categorical_accuracy did not improve from 0.94118

Epoch 00219: val_categorical_accuracy did not improve from 0.94118

Epoch 00220: val_categorical_accuracy did not improve from 0.94118

Epoch 00221: val_categorical_accuracy did not improve from 0.94118

Epoch 00222: val_categorical_accuracy did not improve from 0.94118

Epoch 00223: val_categorical_accuracy did not improve from 0.94118

Epoch 00224: val_categorical_accuracy did not i

(338, 103, 24, 24, 1) (91, 103, 24, 24, 1) (338,) (91,)
Total samples per class: [15, 32, 17, 14, 26, 35, 30, 80, 51, 27, 10, 17, 9, 10, 47, 9], Total number of samples is 429.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 91.
number of samples per class in Ytest: [ 3  7  4  3  6  7  6 16 11  6  2  4  2  2 10  2]

Xtrain_transfer => (338, 64)
Xtest_transfer  => (338, 64)
Ytrain => (338, 16)
Ytest  => (91, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainable pa


Epoch 00090: val_categorical_accuracy did not improve from 0.91209

Epoch 00091: val_categorical_accuracy did not improve from 0.91209

Epoch 00092: val_categorical_accuracy did not improve from 0.91209

Epoch 00093: val_categorical_accuracy did not improve from 0.91209

Epoch 00094: val_categorical_accuracy did not improve from 0.91209

Epoch 00095: val_categorical_accuracy did not improve from 0.91209

Epoch 00096: val_categorical_accuracy did not improve from 0.91209

Epoch 00097: val_categorical_accuracy did not improve from 0.91209

Epoch 00098: val_categorical_accuracy did not improve from 0.91209

Epoch 00099: val_categorical_accuracy did not improve from 0.91209

Epoch 00100: val_categorical_accuracy did not improve from 0.91209

Epoch 00101: val_categorical_accuracy did not improve from 0.91209

Epoch 00102: val_categorical_accuracy did not improve from 0.91209

Epoch 00103: val_categorical_accuracy did not improve from 0.91209

Epoch 00104: val_categorical_accuracy did not i


Epoch 00209: val_categorical_accuracy did not improve from 0.93407

Epoch 00210: val_categorical_accuracy did not improve from 0.93407

Epoch 00211: val_categorical_accuracy did not improve from 0.93407

Epoch 00212: val_categorical_accuracy did not improve from 0.93407

Epoch 00213: val_categorical_accuracy did not improve from 0.93407

Epoch 00214: val_categorical_accuracy did not improve from 0.93407

Epoch 00215: val_categorical_accuracy did not improve from 0.93407

Epoch 00216: val_categorical_accuracy did not improve from 0.93407

Epoch 00217: val_categorical_accuracy did not improve from 0.93407

Epoch 00218: val_categorical_accuracy did not improve from 0.93407

Epoch 00219: val_categorical_accuracy did not improve from 0.93407

Epoch 00220: val_categorical_accuracy did not improve from 0.93407

Epoch 00221: val_categorical_accuracy did not improve from 0.93407

Epoch 00222: val_categorical_accuracy did not improve from 0.93407

Epoch 00223: val_categorical_accuracy did not i

(1121, 103, 24, 24, 1) (288, 103, 24, 24, 1) (1121,) (288,)
Total samples per class: [47, 104, 56, 50, 81, 109, 96, 287, 168, 83, 30, 52, 30, 30, 162, 24], Total number of samples is 1409.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 288.
number of samples per class in Ytest: [10 21 12 10 17 22 20 58 34 17  6 11  6  6 33  5]

Xtrain_transfer => (1121, 64)
Xtest_transfer  => (1121, 64)
Ytrain => (1121, 16)
Ytest  => (288, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_11 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20


Epoch 00076: val_categorical_accuracy did not improve from 0.90625

Epoch 00077: val_categorical_accuracy did not improve from 0.90625

Epoch 00078: val_categorical_accuracy did not improve from 0.90625

Epoch 00079: val_categorical_accuracy did not improve from 0.90625

Epoch 00080: val_categorical_accuracy did not improve from 0.90625

Epoch 00081: val_categorical_accuracy did not improve from 0.90625

Epoch 00082: val_categorical_accuracy did not improve from 0.90625

Epoch 00083: val_categorical_accuracy did not improve from 0.90625

Epoch 00084: val_categorical_accuracy did not improve from 0.90625

Epoch 00085: val_categorical_accuracy did not improve from 0.90625

Epoch 00086: val_categorical_accuracy did not improve from 0.90625

Epoch 00087: val_categorical_accuracy did not improve from 0.90625

Epoch 00088: val_categorical_accuracy did not improve from 0.90625

Epoch 00089: val_categorical_accuracy did not improve from 0.90625

Epoch 00090: val_categorical_accuracy did not i


Epoch 00199: val_categorical_accuracy did not improve from 0.90625

Epoch 00200: val_categorical_accuracy did not improve from 0.90625

Epoch 00201: val_categorical_accuracy did not improve from 0.90625

Epoch 00202: val_categorical_accuracy did not improve from 0.90625

Epoch 00203: val_categorical_accuracy did not improve from 0.90625

Epoch 00204: val_categorical_accuracy did not improve from 0.90625

Epoch 00205: val_categorical_accuracy did not improve from 0.90625

Epoch 00206: val_categorical_accuracy did not improve from 0.90625

Epoch 00207: val_categorical_accuracy did not improve from 0.90625

Epoch 00208: val_categorical_accuracy did not improve from 0.90625

Epoch 00209: val_categorical_accuracy did not improve from 0.90625

Epoch 00210: val_categorical_accuracy did not improve from 0.90625

Epoch 00211: val_categorical_accuracy did not improve from 0.90625

Epoch 00212: val_categorical_accuracy did not improve from 0.90625

Epoch 00213: val_categorical_accuracy did not i



= Source Model with overlap ratio of 75% will be transfered to Target Data with overlap ratio of 95%, Source Model shown below =


Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_3[0][0]                    
__________________________________________________________________________________________________
bn_conv_0 (BatchNormalization)  (None, 48, 11, 11, 3 128         conv_0[0][0]                     
__________________________________________________________________________________________________
activation_2 (Activation)       (None, 48, 11, 11, 3 0    

(16239, 103, 24, 24, 1) (4068, 103, 24, 24, 1) (16239,) (4068,)
Total samples per class: [635, 1619, 663, 632, 1143, 1512, 1490, 4327, 2571, 1092, 357, 650, 306, 349, 2620, 341], Total number of samples is 20307.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 4068.
number of samples per class in Ytest: [127 324 133 127 229 303 298 866 515 219  72 130  62  70 524  69]

Xtrain_transfer => (16239, 64)
Xtest_transfer  => (16239, 64)
Ytrain => (16239, 16)
Ytest  => (4068, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_12 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 1


Epoch 00049: val_categorical_accuracy did not improve from 0.92945

Epoch 00050: val_categorical_accuracy did not improve from 0.92945

Epoch 00051: val_categorical_accuracy did not improve from 0.92945

Epoch 00052: val_categorical_accuracy did not improve from 0.92945

Epoch 00053: val_categorical_accuracy did not improve from 0.92945

Epoch 00054: val_categorical_accuracy did not improve from 0.92945

Epoch 00055: val_categorical_accuracy improved from 0.92945 to 0.93166, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_75_percent.h5

Epoch 00056: val_categorical_accuracy did not improve from 0.93166

Epoch 00057: val_categorical_accuracy did not improve from 0.93166

Epoch 00058: val_categorical_accuracy did not improve from 0.93166

Epoch 00059: val_categorical_accuracy did not improve from 0.93166

Epoch 00060: val_categorical_accuracy did not i


Epoch 00148: val_categorical_accuracy improved from 0.93486 to 0.93510, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_75_percent.h5

Epoch 00149: val_categorical_accuracy did not improve from 0.93510

Epoch 00150: val_categorical_accuracy did not improve from 0.93510

Epoch 00151: val_categorical_accuracy did not improve from 0.93510

Epoch 00152: val_categorical_accuracy did not improve from 0.93510

Epoch 00153: val_categorical_accuracy did not improve from 0.93510

Epoch 00154: val_categorical_accuracy did not improve from 0.93510

Epoch 00155: val_categorical_accuracy did not improve from 0.93510

Epoch 00156: val_categorical_accuracy did not improve from 0.93510

Epoch 00157: val_categorical_accuracy did not improve from 0.93510

Epoch 00158: val_categorical_accuracy did not improve from 0.93510

Epoch 00159: val_categorical_accuracy did not i


Epoch 00254: val_categorical_accuracy did not improve from 0.93781

Epoch 00255: val_categorical_accuracy did not improve from 0.93781

Epoch 00256: val_categorical_accuracy did not improve from 0.93781

Epoch 00257: val_categorical_accuracy did not improve from 0.93781

Epoch 00258: val_categorical_accuracy did not improve from 0.93781

Epoch 00259: val_categorical_accuracy did not improve from 0.93781

Epoch 00260: val_categorical_accuracy did not improve from 0.93781

Epoch 00261: val_categorical_accuracy did not improve from 0.93781

Epoch 00262: val_categorical_accuracy did not improve from 0.93781

Epoch 00263: val_categorical_accuracy did not improve from 0.93781

Epoch 00264: val_categorical_accuracy did not improve from 0.93781

Epoch 00265: val_categorical_accuracy did not improve from 0.93781

Epoch 00266: val_categorical_accuracy did not improve from 0.93781

Epoch 00267: val_categorical_accuracy did not improve from 0.93781

Epoch 00268: val_categorical_accuracy did not i

(174, 103, 24, 24, 1) (51, 103, 24, 24, 1) (174,) (51,)
Total samples per class: [9, 16, 8, 10, 17, 17, 15, 40, 23, 14, 6, 9, 7, 7, 23, 4], Total number of samples is 225.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 51.
number of samples per class in Ytest: [2 4 2 2 4 4 3 8 5 3 2 2 2 2 5 1]

Xtrain_transfer => (174, 64)
Xtest_transfer  => (174, 64)
Ytrain => (174, 16)
Ytest  => (51, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_13 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainable params: 20,752
Non-trai


Epoch 00090: val_categorical_accuracy did not improve from 0.96078

Epoch 00091: val_categorical_accuracy did not improve from 0.96078

Epoch 00092: val_categorical_accuracy did not improve from 0.96078

Epoch 00093: val_categorical_accuracy did not improve from 0.96078

Epoch 00094: val_categorical_accuracy did not improve from 0.96078

Epoch 00095: val_categorical_accuracy did not improve from 0.96078

Epoch 00096: val_categorical_accuracy did not improve from 0.96078

Epoch 00097: val_categorical_accuracy did not improve from 0.96078

Epoch 00098: val_categorical_accuracy did not improve from 0.96078

Epoch 00099: val_categorical_accuracy did not improve from 0.96078

Epoch 00100: val_categorical_accuracy did not improve from 0.96078

Epoch 00101: val_categorical_accuracy did not improve from 0.96078

Epoch 00102: val_categorical_accuracy did not improve from 0.96078

Epoch 00103: val_categorical_accuracy did not improve from 0.96078

Epoch 00104: val_categorical_accuracy did not i


Epoch 00213: val_categorical_accuracy did not improve from 0.96078

Epoch 00214: val_categorical_accuracy did not improve from 0.96078

Epoch 00215: val_categorical_accuracy did not improve from 0.96078

Epoch 00216: val_categorical_accuracy did not improve from 0.96078

Epoch 00217: val_categorical_accuracy did not improve from 0.96078

Epoch 00218: val_categorical_accuracy did not improve from 0.96078

Epoch 00219: val_categorical_accuracy did not improve from 0.96078

Epoch 00220: val_categorical_accuracy did not improve from 0.96078

Epoch 00221: val_categorical_accuracy did not improve from 0.96078

Epoch 00222: val_categorical_accuracy did not improve from 0.96078

Epoch 00223: val_categorical_accuracy did not improve from 0.96078

Epoch 00224: val_categorical_accuracy did not improve from 0.96078

Epoch 00225: val_categorical_accuracy did not improve from 0.96078

Epoch 00226: val_categorical_accuracy did not improve from 0.96078

Epoch 00227: val_categorical_accuracy did not i

(338, 103, 24, 24, 1) (91, 103, 24, 24, 1) (338,) (91,)
Total samples per class: [15, 32, 17, 14, 26, 35, 30, 80, 51, 27, 10, 17, 9, 10, 47, 9], Total number of samples is 429.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 91.
number of samples per class in Ytest: [ 3  7  4  3  6  7  6 16 11  6  2  4  2  2 10  2]

Xtrain_transfer => (338, 64)
Xtest_transfer  => (338, 64)
Ytrain => (338, 16)
Ytest  => (91, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_14 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainable pa


Epoch 00094: val_categorical_accuracy did not improve from 0.95604

Epoch 00095: val_categorical_accuracy did not improve from 0.95604

Epoch 00096: val_categorical_accuracy did not improve from 0.95604

Epoch 00097: val_categorical_accuracy did not improve from 0.95604

Epoch 00098: val_categorical_accuracy did not improve from 0.95604

Epoch 00099: val_categorical_accuracy did not improve from 0.95604

Epoch 00100: val_categorical_accuracy did not improve from 0.95604

Epoch 00101: val_categorical_accuracy did not improve from 0.95604

Epoch 00102: val_categorical_accuracy did not improve from 0.95604

Epoch 00103: val_categorical_accuracy did not improve from 0.95604

Epoch 00104: val_categorical_accuracy did not improve from 0.95604

Epoch 00105: val_categorical_accuracy did not improve from 0.95604

Epoch 00106: val_categorical_accuracy did not improve from 0.95604

Epoch 00107: val_categorical_accuracy did not improve from 0.95604

Epoch 00108: val_categorical_accuracy did not i


Epoch 00218: val_categorical_accuracy did not improve from 0.95604

Epoch 00219: val_categorical_accuracy did not improve from 0.95604

Epoch 00220: val_categorical_accuracy did not improve from 0.95604

Epoch 00221: val_categorical_accuracy did not improve from 0.95604

Epoch 00222: val_categorical_accuracy did not improve from 0.95604

Epoch 00223: val_categorical_accuracy did not improve from 0.95604

Epoch 00224: val_categorical_accuracy did not improve from 0.95604

Epoch 00225: val_categorical_accuracy did not improve from 0.95604

Epoch 00226: val_categorical_accuracy did not improve from 0.95604

Epoch 00227: val_categorical_accuracy did not improve from 0.95604

Epoch 00228: val_categorical_accuracy did not improve from 0.95604

Epoch 00229: val_categorical_accuracy did not improve from 0.95604

Epoch 00230: val_categorical_accuracy did not improve from 0.95604

Epoch 00231: val_categorical_accuracy did not improve from 0.95604

Epoch 00232: val_categorical_accuracy did not i

(1121, 103, 24, 24, 1) (288, 103, 24, 24, 1) (1121,) (288,)
Total samples per class: [47, 104, 56, 50, 81, 109, 96, 287, 168, 83, 30, 52, 30, 30, 162, 24], Total number of samples is 1409.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 288.
number of samples per class in Ytest: [10 21 12 10 17 22 20 58 34 17  6 11  6  6 33  5]

Xtrain_transfer => (1121, 64)
Xtest_transfer  => (1121, 64)
Ytrain => (1121, 16)
Ytest  => (288, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_15 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20


Epoch 00083: val_categorical_accuracy did not improve from 0.95833

Epoch 00084: val_categorical_accuracy did not improve from 0.95833

Epoch 00085: val_categorical_accuracy did not improve from 0.95833

Epoch 00086: val_categorical_accuracy did not improve from 0.95833

Epoch 00087: val_categorical_accuracy did not improve from 0.95833

Epoch 00088: val_categorical_accuracy did not improve from 0.95833

Epoch 00089: val_categorical_accuracy did not improve from 0.95833

Epoch 00090: val_categorical_accuracy did not improve from 0.95833

Epoch 00091: val_categorical_accuracy did not improve from 0.95833

Epoch 00092: val_categorical_accuracy did not improve from 0.95833

Epoch 00093: val_categorical_accuracy did not improve from 0.95833

Epoch 00094: val_categorical_accuracy did not improve from 0.95833

Epoch 00095: val_categorical_accuracy did not improve from 0.95833

Epoch 00096: val_categorical_accuracy did not improve from 0.95833

Epoch 00097: val_categorical_accuracy did not i


Epoch 00207: val_categorical_accuracy did not improve from 0.95833

Epoch 00208: val_categorical_accuracy did not improve from 0.95833

Epoch 00209: val_categorical_accuracy did not improve from 0.95833

Epoch 00210: val_categorical_accuracy did not improve from 0.95833

Epoch 00211: val_categorical_accuracy did not improve from 0.95833

Epoch 00212: val_categorical_accuracy did not improve from 0.95833

Epoch 00213: val_categorical_accuracy did not improve from 0.95833

Epoch 00214: val_categorical_accuracy did not improve from 0.95833

Epoch 00215: val_categorical_accuracy did not improve from 0.95833

Epoch 00216: val_categorical_accuracy did not improve from 0.95833

Epoch 00217: val_categorical_accuracy did not improve from 0.95833

Epoch 00218: val_categorical_accuracy did not improve from 0.95833

Epoch 00219: val_categorical_accuracy did not improve from 0.95833

Epoch 00220: val_categorical_accuracy did not improve from 0.95833

Epoch 00221: val_categorical_accuracy did not i

(16239, 103, 24, 24, 1) (4068, 103, 24, 24, 1) (16239,) (4068,)
Total samples per class: [635, 1619, 663, 632, 1143, 1512, 1490, 4327, 2571, 1092, 357, 650, 306, 349, 2620, 341], Total number of samples is 20307.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 4068.
number of samples per class in Ytest: [127 324 133 127 229 303 298 866 515 219  72 130  62  70 524  69]

Xtrain_transfer => (16239, 64)
Xtest_transfer  => (16239, 64)
Ytrain => (16239, 16)
Ytest  => (4068, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_16 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 1


Epoch 00094: val_categorical_accuracy did not improve from 0.95157

Epoch 00095: val_categorical_accuracy did not improve from 0.95157

Epoch 00096: val_categorical_accuracy did not improve from 0.95157

Epoch 00097: val_categorical_accuracy did not improve from 0.95157

Epoch 00098: val_categorical_accuracy did not improve from 0.95157

Epoch 00099: val_categorical_accuracy did not improve from 0.95157

Epoch 00100: val_categorical_accuracy did not improve from 0.95157

Epoch 00101: val_categorical_accuracy did not improve from 0.95157

Epoch 00102: val_categorical_accuracy did not improve from 0.95157

Epoch 00103: val_categorical_accuracy did not improve from 0.95157

Epoch 00104: val_categorical_accuracy did not improve from 0.95157

Epoch 00105: val_categorical_accuracy did not improve from 0.95157

Epoch 00106: val_categorical_accuracy did not improve from 0.95157

Epoch 00107: val_categorical_accuracy did not improve from 0.95157

Epoch 00108: val_categorical_accuracy did not i


Epoch 00215: val_categorical_accuracy did not improve from 0.95157

Epoch 00216: val_categorical_accuracy did not improve from 0.95157

Epoch 00217: val_categorical_accuracy did not improve from 0.95157

Epoch 00218: val_categorical_accuracy did not improve from 0.95157

Epoch 00219: val_categorical_accuracy did not improve from 0.95157

Epoch 00220: val_categorical_accuracy did not improve from 0.95157

Epoch 00221: val_categorical_accuracy did not improve from 0.95157

Epoch 00222: val_categorical_accuracy did not improve from 0.95157

Epoch 00223: val_categorical_accuracy did not improve from 0.95157

Epoch 00224: val_categorical_accuracy did not improve from 0.95157

Epoch 00225: val_categorical_accuracy did not improve from 0.95157

Epoch 00226: val_categorical_accuracy did not improve from 0.95157

Epoch 00227: val_categorical_accuracy did not improve from 0.95157

Epoch 00228: val_categorical_accuracy did not improve from 0.95157

Epoch 00229: val_categorical_accuracy did not i

In [5]:
Acc_Tbl

0           1           2           3           4
0  Test Accuracy  Salinas_25  Salinas_50  Salinas_75  Salinas_95
1     Salinas_25     76.4706     80.2198     82.2917     85.5949
2     Salinas_50     86.2745     79.1209     81.9444     85.6686
3     Salinas_75     92.1569     92.3077      90.625     93.6578
4     Salinas_95     96.0784     95.6044     94.7917     94.3707