# Salinas to Pavia

In [1]:
from Transfer_Model_Utils import *
import scipy.io as sio

In [2]:
uPavia = sio.loadmat('..\\..\\pavia\\PaviaU.mat')
gt_uPavia = sio.loadmat('..\\..\\pavia\\PaviaU_gt.mat')
data_PV = uPavia['paviaU']
gt_PV = gt_uPavia['paviaU_gt']
print(data_PV.shape, gt_PV.shape)
data_PV = np.moveaxis(data_PV, 2, 0)
print(data_PV.shape, gt_PV.shape)

(610, 340, 103) (610, 340)
(103, 610, 340) (610, 340)


In [3]:
values,counts = np.unique(gt_PV, return_counts=True)
print(values,counts)
range_of_class = list(values)
if 0 in range_of_class:
    range_of_class.pop(0)
range_of_class

[0 1 2 3 4 5 6 7 8 9] [164624   6631  18649   2099   3064   1345   5029   1330   3682    947]


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
Acc_Tbl = Transfer(overlap_ratio_List_for_Target = [25, 50, 75, 95],
                   overlap_ratio_List_for_Source = [25, 50, 75, 95],
                   epochs_list = [300, 300, 300, 300],
                   batch_size_list = [16, 32, 64, 128],
                   range_of_class = range_of_class,
                   Cube_size = 25,
                   Data = data_PV,
                   Gt = gt_PV,
                   Train_Test_split = 80,
                   channel = 103,
                   Source_data_name = 'Salinas', 
                   Target_data_name = 'Pavia',
                   Verbosity = 0)

               0         1         2         3         4
0  Test Accuracy  Pavia_25  Pavia_50  Pavia_75  Pavia_95
1     Salinas_25      None      None      None      None
2     Salinas_50      None      None      None      None
3     Salinas_75      None      None      None      None
4     Salinas_95      None      None      None      None


= Source Model with overlap ratio of 25% will be transfered to Target Data with overlap ratio of 25%, Source Model shown below =


Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_1[0][0]                    
_______________

(309, 103, 24, 24, 1) (82, 103, 24, 24, 1) (309,) (82,)
Total samples per class: [74, 72, 19, 98, 12, 19, 10, 56, 31], Total number of samples is 391.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 82.
number of samples per class in Ytest: [15 15  4 20  3  4  2 12  7]

Xtrain_transfer => (309, 64)
Xtest_transfer  => (309, 64)
Ytrain => (309, 9)
Ytest  => (82, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
__________________________________________


Epoch 00075: val_categorical_accuracy did not improve from 0.59756

Epoch 00076: val_categorical_accuracy did not improve from 0.59756

Epoch 00077: val_categorical_accuracy did not improve from 0.59756

Epoch 00078: val_categorical_accuracy did not improve from 0.59756

Epoch 00079: val_categorical_accuracy did not improve from 0.59756

Epoch 00080: val_categorical_accuracy did not improve from 0.59756

Epoch 00081: val_categorical_accuracy did not improve from 0.59756

Epoch 00082: val_categorical_accuracy did not improve from 0.59756

Epoch 00083: val_categorical_accuracy did not improve from 0.59756

Epoch 00084: val_categorical_accuracy did not improve from 0.59756

Epoch 00085: val_categorical_accuracy did not improve from 0.59756

Epoch 00086: val_categorical_accuracy improved from 0.59756 to 0.60976, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_25_With_source_data_as_Salinas_overlap_rati


Epoch 00184: val_categorical_accuracy did not improve from 0.64634

Epoch 00185: val_categorical_accuracy did not improve from 0.64634

Epoch 00186: val_categorical_accuracy did not improve from 0.64634

Epoch 00187: val_categorical_accuracy did not improve from 0.64634

Epoch 00188: val_categorical_accuracy did not improve from 0.64634

Epoch 00189: val_categorical_accuracy did not improve from 0.64634

Epoch 00190: val_categorical_accuracy did not improve from 0.64634

Epoch 00191: val_categorical_accuracy did not improve from 0.64634

Epoch 00192: val_categorical_accuracy did not improve from 0.64634

Epoch 00193: val_categorical_accuracy did not improve from 0.64634

Epoch 00194: val_categorical_accuracy did not improve from 0.64634

Epoch 00195: val_categorical_accuracy did not improve from 0.64634

Epoch 00196: val_categorical_accuracy did not improve from 0.64634

Epoch 00197: val_categorical_accuracy did not improve from 0.64634

Epoch 00198: val_categorical_accuracy did not i

82/82 [==============================] - 0s 73us/sample - loss: 1.1151 - categorical_accuracy: 0.6585
Test Accuracy = 0.6585366
82/82 [==============================] - 0s 695us/sample

============ Confusion_matrix for data with source overlap ratio of 25 and target overlap ratio of  25 is as below ============

[[ 8  2  1  4  0  0  0  0  0]
 [ 0 14  0  1  0  0  0  0  0]
 [ 1  0  1  0  0  0  0  2  0]
 [ 1  2  0 17  0  0  0  0  0]
 [ 0  0  0  1  2  0  0  0  0]
 [ 0  3  0  1  0  0  0  0  0]
 [ 1  0  0  1  0  0  0  0  0]
 [ 3  1  0  0  0  0  0  8  0]
 [ 1  0  1  1  0  0  0  0  4]]
[15 15  4 20  3  4  2 12  7]


= Source Model with overlap ratio of 25% will be transfered to Target Data with overlap ratio of 50%, Source Model shown below =


Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None,

(505, 103, 24, 24, 1) (130, 103, 24, 24, 1) (505,) (130,)
Total samples per class: [115, 139, 30, 133, 22, 44, 17, 96, 39], Total number of samples is 635.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 130.
number of samples per class in Ytest: [23 28  6 27  5  9  4 20  8]

Xtrain_transfer => (505, 64)
Xtest_transfer  => (505, 64)
Ytrain => (505, 9)
Ytest  => (130, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
___________________________________


Epoch 00068: val_categorical_accuracy did not improve from 0.56923

Epoch 00069: val_categorical_accuracy did not improve from 0.56923

Epoch 00070: val_categorical_accuracy did not improve from 0.56923

Epoch 00071: val_categorical_accuracy did not improve from 0.56923

Epoch 00072: val_categorical_accuracy did not improve from 0.56923

Epoch 00073: val_categorical_accuracy did not improve from 0.56923

Epoch 00074: val_categorical_accuracy did not improve from 0.56923

Epoch 00075: val_categorical_accuracy did not improve from 0.56923

Epoch 00076: val_categorical_accuracy did not improve from 0.56923

Epoch 00077: val_categorical_accuracy improved from 0.56923 to 0.57692, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_50_With_source_data_as_Salinas_overlap_ratio_25_percent.h5

Epoch 00078: val_categorical_accuracy did not improve from 0.57692

Epoch 00079: val_categorical_accuracy did not impro


Epoch 00177: val_categorical_accuracy did not improve from 0.60000

Epoch 00178: val_categorical_accuracy did not improve from 0.60000

Epoch 00179: val_categorical_accuracy did not improve from 0.60000

Epoch 00180: val_categorical_accuracy did not improve from 0.60000

Epoch 00181: val_categorical_accuracy did not improve from 0.60000

Epoch 00182: val_categorical_accuracy did not improve from 0.60000

Epoch 00183: val_categorical_accuracy did not improve from 0.60000

Epoch 00184: val_categorical_accuracy did not improve from 0.60000

Epoch 00185: val_categorical_accuracy did not improve from 0.60000

Epoch 00186: val_categorical_accuracy did not improve from 0.60000

Epoch 00187: val_categorical_accuracy did not improve from 0.60000

Epoch 00188: val_categorical_accuracy did not improve from 0.60000

Epoch 00189: val_categorical_accuracy did not improve from 0.60000

Epoch 00190: val_categorical_accuracy did not improve from 0.60000

Epoch 00191: val_categorical_accuracy did not i


Epoch 00300: val_categorical_accuracy did not improve from 0.60769
130/130 [==============================] - 0s 120us/sample - loss: 1.1598 - categorical_accuracy: 0.6000
Test Accuracy = 0.6
130/130 [==============================] - 0s 361us/sample

============ Confusion_matrix for data with source overlap ratio of 25 and target overlap ratio of  50 is as below ============

[[12  4  0  7  0  0  0  0  0]
 [ 1 26  0  1  0  0  0  0  0]
 [ 2  0  1  0  0  0  2  1  0]
 [ 1  0  0 25  0  0  0  1  0]
 [ 0  0  1  0  4  0  0  0  0]
 [ 1  6  0  1  0  1  0  0  0]
 [ 2  0  0  1  0  0  0  1  0]
 [ 9  1  1  2  0  0  0  6  1]
 [ 1  0  2  2  0  0  0  0  3]]
[23 28  6 27  5  9  4 20  8]


= Source Model with overlap ratio of 25% will be transfered to Target Data with overlap ratio of 75%, Source Model shown below =


Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connec

(1206, 103, 24, 24, 1) (304, 103, 24, 24, 1) (1206,) (304,)
Total samples per class: [264, 425, 74, 244, 48, 139, 45, 203, 68], Total number of samples is 1510.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 304.
number of samples per class in Ytest: [53 85 15 49 10 28  9 41 14]

Xtrain_transfer => (1206, 64)
Xtest_transfer  => (1206, 64)
Ytrain => (1206, 9)
Ytest  => (304, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
___________________________


Epoch 00067: val_categorical_accuracy did not improve from 0.58553

Epoch 00068: val_categorical_accuracy did not improve from 0.58553

Epoch 00069: val_categorical_accuracy did not improve from 0.58553

Epoch 00070: val_categorical_accuracy did not improve from 0.58553

Epoch 00071: val_categorical_accuracy did not improve from 0.58553

Epoch 00072: val_categorical_accuracy did not improve from 0.58553

Epoch 00073: val_categorical_accuracy did not improve from 0.58553

Epoch 00074: val_categorical_accuracy did not improve from 0.58553

Epoch 00075: val_categorical_accuracy did not improve from 0.58553

Epoch 00076: val_categorical_accuracy did not improve from 0.58553

Epoch 00077: val_categorical_accuracy did not improve from 0.58553

Epoch 00078: val_categorical_accuracy improved from 0.58553 to 0.59211, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Salinas_overlap_rati


Epoch 00180: val_categorical_accuracy did not improve from 0.62171

Epoch 00181: val_categorical_accuracy did not improve from 0.62171

Epoch 00182: val_categorical_accuracy did not improve from 0.62171

Epoch 00183: val_categorical_accuracy did not improve from 0.62171

Epoch 00184: val_categorical_accuracy did not improve from 0.62171

Epoch 00185: val_categorical_accuracy did not improve from 0.62171

Epoch 00186: val_categorical_accuracy did not improve from 0.62171

Epoch 00187: val_categorical_accuracy did not improve from 0.62171

Epoch 00188: val_categorical_accuracy did not improve from 0.62171

Epoch 00189: val_categorical_accuracy did not improve from 0.62171

Epoch 00190: val_categorical_accuracy did not improve from 0.62171

Epoch 00191: val_categorical_accuracy improved from 0.62171 to 0.62500, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Salinas_overlap_rati


Epoch 00289: val_categorical_accuracy did not improve from 0.65132

Epoch 00290: val_categorical_accuracy did not improve from 0.65132

Epoch 00291: val_categorical_accuracy did not improve from 0.65132

Epoch 00292: val_categorical_accuracy did not improve from 0.65132

Epoch 00293: val_categorical_accuracy did not improve from 0.65132

Epoch 00294: val_categorical_accuracy did not improve from 0.65132

Epoch 00295: val_categorical_accuracy did not improve from 0.65132

Epoch 00296: val_categorical_accuracy did not improve from 0.65132

Epoch 00297: val_categorical_accuracy did not improve from 0.65132

Epoch 00298: val_categorical_accuracy did not improve from 0.65132

Epoch 00299: val_categorical_accuracy did not improve from 0.65132

Epoch 00300: val_categorical_accuracy did not improve from 0.65132
304/304 [==============================] - 0s 91us/sample - loss: 1.0617 - categorical_accuracy: 0.6217
Test Accuracy = 0.62171054
304/304 [==============================] - 0s 271us/s

(13491, 103, 24, 24, 1) (3377, 103, 24, 24, 1) (13491,) (3377,)
Total samples per class: [2838, 6243, 775, 1409, 636, 2174, 603, 1758, 432], Total number of samples is 16868.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 3377.
number of samples per class in Ytest: [ 568 1249  155  282  128  435  121  352   87]

Xtrain_transfer => (13491, 64)
Xtest_transfer  => (13491, 64)
Ytrain => (13491, 9)
Ytest  => (3377, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable 


Epoch 00054: val_categorical_accuracy did not improve from 0.69085

Epoch 00055: val_categorical_accuracy did not improve from 0.69085

Epoch 00056: val_categorical_accuracy improved from 0.69085 to 0.69203, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_25_percent.h5

Epoch 00057: val_categorical_accuracy did not improve from 0.69203

Epoch 00058: val_categorical_accuracy did not improve from 0.69203

Epoch 00059: val_categorical_accuracy did not improve from 0.69203

Epoch 00060: val_categorical_accuracy improved from 0.69203 to 0.69973, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_25_percent.h5

Epoch 00061: val_categorical_accuracy improved from 0.69973 to 0.70654, saving model to ..\..\Trained Models\Transfered_Mod


Epoch 00141: val_categorical_accuracy did not improve from 0.72698

Epoch 00142: val_categorical_accuracy did not improve from 0.72698

Epoch 00143: val_categorical_accuracy did not improve from 0.72698

Epoch 00144: val_categorical_accuracy did not improve from 0.72698

Epoch 00145: val_categorical_accuracy did not improve from 0.72698

Epoch 00146: val_categorical_accuracy did not improve from 0.72698

Epoch 00147: val_categorical_accuracy improved from 0.72698 to 0.72757, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_25_percent.h5

Epoch 00148: val_categorical_accuracy did not improve from 0.72757

Epoch 00149: val_categorical_accuracy did not improve from 0.72757

Epoch 00150: val_categorical_accuracy did not improve from 0.72757

Epoch 00151: val_categorical_accuracy did not improve from 0.72757

Epoch 00152: val_categorical_accuracy did not impro


Epoch 00247: val_categorical_accuracy did not improve from 0.73142

Epoch 00248: val_categorical_accuracy did not improve from 0.73142

Epoch 00249: val_categorical_accuracy did not improve from 0.73142

Epoch 00250: val_categorical_accuracy did not improve from 0.73142

Epoch 00251: val_categorical_accuracy did not improve from 0.73142

Epoch 00252: val_categorical_accuracy did not improve from 0.73142

Epoch 00253: val_categorical_accuracy did not improve from 0.73142

Epoch 00254: val_categorical_accuracy did not improve from 0.73142

Epoch 00255: val_categorical_accuracy did not improve from 0.73142

Epoch 00256: val_categorical_accuracy did not improve from 0.73142

Epoch 00257: val_categorical_accuracy did not improve from 0.73142

Epoch 00258: val_categorical_accuracy did not improve from 0.73142

Epoch 00259: val_categorical_accuracy did not improve from 0.73142

Epoch 00260: val_categorical_accuracy did not improve from 0.73142

Epoch 00261: val_categorical_accuracy did not i

(309, 103, 24, 24, 1) (82, 103, 24, 24, 1) (309,) (82,)
Total samples per class: [74, 72, 19, 98, 12, 19, 10, 56, 31], Total number of samples is 391.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 82.
number of samples per class in Ytest: [15 15  4 20  3  4  2 12  7]

Xtrain_transfer => (309, 64)
Xtest_transfer  => (309, 64)
Ytrain => (309, 9)
Ytest  => (82, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
__________________________________________


Epoch 00078: val_categorical_accuracy did not improve from 0.48780

Epoch 00079: val_categorical_accuracy did not improve from 0.48780

Epoch 00080: val_categorical_accuracy did not improve from 0.48780

Epoch 00081: val_categorical_accuracy did not improve from 0.48780

Epoch 00082: val_categorical_accuracy did not improve from 0.48780

Epoch 00083: val_categorical_accuracy did not improve from 0.48780

Epoch 00084: val_categorical_accuracy did not improve from 0.48780

Epoch 00085: val_categorical_accuracy did not improve from 0.48780

Epoch 00086: val_categorical_accuracy did not improve from 0.48780

Epoch 00087: val_categorical_accuracy did not improve from 0.48780

Epoch 00088: val_categorical_accuracy did not improve from 0.48780

Epoch 00089: val_categorical_accuracy did not improve from 0.48780

Epoch 00090: val_categorical_accuracy did not improve from 0.48780

Epoch 00091: val_categorical_accuracy did not improve from 0.48780

Epoch 00092: val_categorical_accuracy did not i


Epoch 00194: val_categorical_accuracy did not improve from 0.52439

Epoch 00195: val_categorical_accuracy did not improve from 0.52439

Epoch 00196: val_categorical_accuracy did not improve from 0.52439

Epoch 00197: val_categorical_accuracy did not improve from 0.52439

Epoch 00198: val_categorical_accuracy did not improve from 0.52439

Epoch 00199: val_categorical_accuracy did not improve from 0.52439

Epoch 00200: val_categorical_accuracy did not improve from 0.52439

Epoch 00201: val_categorical_accuracy did not improve from 0.52439

Epoch 00202: val_categorical_accuracy did not improve from 0.52439

Epoch 00203: val_categorical_accuracy did not improve from 0.52439

Epoch 00204: val_categorical_accuracy did not improve from 0.52439

Epoch 00205: val_categorical_accuracy did not improve from 0.52439

Epoch 00206: val_categorical_accuracy did not improve from 0.52439

Epoch 00207: val_categorical_accuracy did not improve from 0.52439

Epoch 00208: val_categorical_accuracy did not i



= Source Model with overlap ratio of 50% will be transfered to Target Data with overlap ratio of 50%, Source Model shown below =


Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_2[0][0]                    
__________________________________________________________________________________________________
bn_conv_0 (BatchNormalization)  (None, 48, 11, 11, 3 128         conv_0[0][0]                     
__________________________________________________________________________________________________
activation_1 (Activation)       (None, 48, 11, 11, 3 0    

(505, 103, 24, 24, 1) (130, 103, 24, 24, 1) (505,) (130,)
Total samples per class: [115, 139, 30, 133, 22, 44, 17, 96, 39], Total number of samples is 635.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 130.
number of samples per class in Ytest: [23 28  6 27  5  9  4 20  8]

Xtrain_transfer => (505, 64)
Xtest_transfer  => (505, 64)
Ytrain => (505, 9)
Ytest  => (130, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
___________________________________


Epoch 00051: val_categorical_accuracy did not improve from 0.46154

Epoch 00052: val_categorical_accuracy did not improve from 0.46154

Epoch 00053: val_categorical_accuracy improved from 0.46154 to 0.47692, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_50_With_source_data_as_Salinas_overlap_ratio_50_percent.h5

Epoch 00054: val_categorical_accuracy did not improve from 0.47692

Epoch 00055: val_categorical_accuracy did not improve from 0.47692

Epoch 00056: val_categorical_accuracy did not improve from 0.47692

Epoch 00057: val_categorical_accuracy did not improve from 0.47692

Epoch 00058: val_categorical_accuracy did not improve from 0.47692

Epoch 00059: val_categorical_accuracy did not improve from 0.47692

Epoch 00060: val_categorical_accuracy did not improve from 0.47692

Epoch 00061: val_categorical_accuracy did not improve from 0.47692

Epoch 00062: val_categorical_accuracy did not impro


Epoch 00159: val_categorical_accuracy did not improve from 0.53077

Epoch 00160: val_categorical_accuracy did not improve from 0.53077

Epoch 00161: val_categorical_accuracy did not improve from 0.53077

Epoch 00162: val_categorical_accuracy did not improve from 0.53077

Epoch 00163: val_categorical_accuracy did not improve from 0.53077

Epoch 00164: val_categorical_accuracy did not improve from 0.53077

Epoch 00165: val_categorical_accuracy did not improve from 0.53077

Epoch 00166: val_categorical_accuracy did not improve from 0.53077

Epoch 00167: val_categorical_accuracy did not improve from 0.53077

Epoch 00168: val_categorical_accuracy did not improve from 0.53077

Epoch 00169: val_categorical_accuracy improved from 0.53077 to 0.54615, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_50_With_source_data_as_Salinas_overlap_ratio_50_percent.h5

Epoch 00170: val_categorical_accuracy did not impro


Epoch 00277: val_categorical_accuracy did not improve from 0.54615

Epoch 00278: val_categorical_accuracy did not improve from 0.54615

Epoch 00279: val_categorical_accuracy did not improve from 0.54615

Epoch 00280: val_categorical_accuracy did not improve from 0.54615

Epoch 00281: val_categorical_accuracy did not improve from 0.54615

Epoch 00282: val_categorical_accuracy did not improve from 0.54615

Epoch 00283: val_categorical_accuracy did not improve from 0.54615

Epoch 00284: val_categorical_accuracy did not improve from 0.54615

Epoch 00285: val_categorical_accuracy did not improve from 0.54615

Epoch 00286: val_categorical_accuracy did not improve from 0.54615

Epoch 00287: val_categorical_accuracy did not improve from 0.54615

Epoch 00288: val_categorical_accuracy did not improve from 0.54615

Epoch 00289: val_categorical_accuracy did not improve from 0.54615

Epoch 00290: val_categorical_accuracy did not improve from 0.54615

Epoch 00291: val_categorical_accuracy did not i

(1206, 103, 24, 24, 1) (304, 103, 24, 24, 1) (1206,) (304,)
Total samples per class: [264, 425, 74, 244, 48, 139, 45, 203, 68], Total number of samples is 1510.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 304.
number of samples per class in Ytest: [53 85 15 49 10 28  9 41 14]

Xtrain_transfer => (1206, 64)
Xtest_transfer  => (1206, 64)
Ytrain => (1206, 9)
Ytest  => (304, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
___________________________


Epoch 00052: val_categorical_accuracy improved from 0.46711 to 0.47368, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Salinas_overlap_ratio_50_percent.h5

Epoch 00053: val_categorical_accuracy did not improve from 0.47368

Epoch 00054: val_categorical_accuracy did not improve from 0.47368

Epoch 00055: val_categorical_accuracy did not improve from 0.47368

Epoch 00056: val_categorical_accuracy did not improve from 0.47368

Epoch 00057: val_categorical_accuracy improved from 0.47368 to 0.47697, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Salinas_overlap_ratio_50_percent.h5

Epoch 00058: val_categorical_accuracy did not improve from 0.47697

Epoch 00059: val_categorical_accuracy did not improve from 0.47697

Epoch 00060: val_categorical_accuracy did not improve f


Epoch 00138: val_categorical_accuracy did not improve from 0.52961

Epoch 00139: val_categorical_accuracy did not improve from 0.52961

Epoch 00140: val_categorical_accuracy improved from 0.52961 to 0.53618, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Salinas_overlap_ratio_50_percent.h5

Epoch 00141: val_categorical_accuracy did not improve from 0.53618

Epoch 00142: val_categorical_accuracy did not improve from 0.53618

Epoch 00143: val_categorical_accuracy did not improve from 0.53618

Epoch 00144: val_categorical_accuracy did not improve from 0.53618

Epoch 00145: val_categorical_accuracy did not improve from 0.53618

Epoch 00146: val_categorical_accuracy did not improve from 0.53618

Epoch 00147: val_categorical_accuracy did not improve from 0.53618

Epoch 00148: val_categorical_accuracy did not improve from 0.53618

Epoch 00149: val_categorical_accuracy did not impro

Epoch 00236: val_categorical_accuracy did not improve from 0.56579

Epoch 00237: val_categorical_accuracy improved from 0.56579 to 0.57237, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Salinas_overlap_ratio_50_percent.h5

Epoch 00238: val_categorical_accuracy did not improve from 0.57237

Epoch 00239: val_categorical_accuracy did not improve from 0.57237

Epoch 00240: val_categorical_accuracy did not improve from 0.57237

Epoch 00241: val_categorical_accuracy improved from 0.57237 to 0.57566, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Salinas_overlap_ratio_50_percent.h5

Epoch 00242: val_categorical_accuracy did not improve from 0.57566

Epoch 00243: val_categorical_accuracy did not improve from 0.57566

Epoch 00244: val_categorical_accuracy did not improve fr

(13491, 103, 24, 24, 1) (3377, 103, 24, 24, 1) (13491,) (3377,)
Total samples per class: [2838, 6243, 775, 1409, 636, 2174, 603, 1758, 432], Total number of samples is 16868.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 3377.
number of samples per class in Ytest: [ 568 1249  155  282  128  435  121  352   87]

Xtrain_transfer => (13491, 64)
Xtest_transfer  => (13491, 64)
Ytrain => (13491, 9)
Ytest  => (3377, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable 


Epoch 00038: val_categorical_accuracy improved from 0.61179 to 0.61741, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_50_percent.h5

Epoch 00039: val_categorical_accuracy improved from 0.61741 to 0.62008, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_50_percent.h5

Epoch 00040: val_categorical_accuracy did not improve from 0.62008

Epoch 00041: val_categorical_accuracy did not improve from 0.62008

Epoch 00042: val_categorical_accuracy improved from 0.62008 to 0.62215, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_50_percent.h5

Epoch 00043: val_categorical_accuracy improved from 0.62215


Epoch 00094: val_categorical_accuracy did not improve from 0.65502

Epoch 00095: val_categorical_accuracy did not improve from 0.65502

Epoch 00096: val_categorical_accuracy did not improve from 0.65502

Epoch 00097: val_categorical_accuracy did not improve from 0.65502

Epoch 00098: val_categorical_accuracy improved from 0.65502 to 0.66065, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_50_percent.h5

Epoch 00099: val_categorical_accuracy did not improve from 0.66065

Epoch 00100: val_categorical_accuracy did not improve from 0.66065

Epoch 00101: val_categorical_accuracy improved from 0.66065 to 0.66361, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_50_percent.h5

Epoch 00102: val_categorical_accuracy did not improve f


Epoch 00186: val_categorical_accuracy did not improve from 0.67960

Epoch 00187: val_categorical_accuracy did not improve from 0.67960

Epoch 00188: val_categorical_accuracy did not improve from 0.67960

Epoch 00189: val_categorical_accuracy did not improve from 0.67960

Epoch 00190: val_categorical_accuracy did not improve from 0.67960

Epoch 00191: val_categorical_accuracy did not improve from 0.67960

Epoch 00192: val_categorical_accuracy did not improve from 0.67960

Epoch 00193: val_categorical_accuracy did not improve from 0.67960

Epoch 00194: val_categorical_accuracy did not improve from 0.67960

Epoch 00195: val_categorical_accuracy did not improve from 0.67960

Epoch 00196: val_categorical_accuracy did not improve from 0.67960

Epoch 00197: val_categorical_accuracy did not improve from 0.67960

Epoch 00198: val_categorical_accuracy did not improve from 0.67960

Epoch 00199: val_categorical_accuracy did not improve from 0.67960

Epoch 00200: val_categorical_accuracy did not i


Epoch 00298: val_categorical_accuracy improved from 0.68049 to 0.68078, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_50_percent.h5

Epoch 00299: val_categorical_accuracy did not improve from 0.68078

Epoch 00300: val_categorical_accuracy did not improve from 0.68078
3377/3377 [==============================] - 0s 52us/sample - loss: 0.9147 - categorical_accuracy: 0.6760
Test Accuracy = 0.6760438
3377/3377 [==============================] - 0s 102us/sample

============ Confusion_matrix for data with source overlap ratio of 50 and target overlap ratio of  95 is as below ============

[[ 354   33   12   84    1   42    2   39    1]
 [  12 1152    0   43    0   42    0    0    0]
 [  46    0   37    8    0    0    9   52    3]
 [  24   41    3  203    0    5    0    3    3]
 [   0    0    0   19  102    0    0    0    7]
 [  62  135    2   13    0  213  

(309, 103, 24, 24, 1) (82, 103, 24, 24, 1) (309,) (82,)
Total samples per class: [74, 72, 19, 98, 12, 19, 10, 56, 31], Total number of samples is 391.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 82.
number of samples per class in Ytest: [15 15  4 20  3  4  2 12  7]

Xtrain_transfer => (309, 64)
Xtest_transfer  => (309, 64)
Ytrain => (309, 9)
Ytest  => (82, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
__________________________________________


Epoch 00071: val_categorical_accuracy did not improve from 0.51220

Epoch 00072: val_categorical_accuracy did not improve from 0.51220

Epoch 00073: val_categorical_accuracy did not improve from 0.51220

Epoch 00074: val_categorical_accuracy did not improve from 0.51220

Epoch 00075: val_categorical_accuracy improved from 0.51220 to 0.52439, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_25_With_source_data_as_Salinas_overlap_ratio_75_percent.h5

Epoch 00076: val_categorical_accuracy did not improve from 0.52439

Epoch 00077: val_categorical_accuracy did not improve from 0.52439

Epoch 00078: val_categorical_accuracy did not improve from 0.52439

Epoch 00079: val_categorical_accuracy improved from 0.52439 to 0.54878, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_25_With_source_data_as_Salinas_overlap_ratio_75


Epoch 00185: val_categorical_accuracy did not improve from 0.57317

Epoch 00186: val_categorical_accuracy did not improve from 0.57317

Epoch 00187: val_categorical_accuracy did not improve from 0.57317

Epoch 00188: val_categorical_accuracy did not improve from 0.57317

Epoch 00189: val_categorical_accuracy did not improve from 0.57317

Epoch 00190: val_categorical_accuracy did not improve from 0.57317

Epoch 00191: val_categorical_accuracy did not improve from 0.57317

Epoch 00192: val_categorical_accuracy did not improve from 0.57317

Epoch 00193: val_categorical_accuracy did not improve from 0.57317

Epoch 00194: val_categorical_accuracy did not improve from 0.57317

Epoch 00195: val_categorical_accuracy did not improve from 0.57317

Epoch 00196: val_categorical_accuracy did not improve from 0.57317

Epoch 00197: val_categorical_accuracy did not improve from 0.57317

Epoch 00198: val_categorical_accuracy did not improve from 0.57317

Epoch 00199: val_categorical_accuracy did not i



= Source Model with overlap ratio of 75% will be transfered to Target Data with overlap ratio of 50%, Source Model shown below =


Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_3[0][0]                    
__________________________________________________________________________________________________
bn_conv_0 (BatchNormalization)  (None, 48, 11, 11, 3 128         conv_0[0][0]                     
__________________________________________________________________________________________________
activation_2 (Activation)       (None, 48, 11, 11, 3 0    

(505, 103, 24, 24, 1) (130, 103, 24, 24, 1) (505,) (130,)
Total samples per class: [115, 139, 30, 133, 22, 44, 17, 96, 39], Total number of samples is 635.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 130.
number of samples per class in Ytest: [23 28  6 27  5  9  4 20  8]

Xtrain_transfer => (505, 64)
Xtest_transfer  => (505, 64)
Ytrain => (505, 9)
Ytest  => (130, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
___________________________________


Epoch 00057: val_categorical_accuracy did not improve from 0.50000

Epoch 00058: val_categorical_accuracy did not improve from 0.50000

Epoch 00059: val_categorical_accuracy did not improve from 0.50000

Epoch 00060: val_categorical_accuracy did not improve from 0.50000

Epoch 00061: val_categorical_accuracy did not improve from 0.50000

Epoch 00062: val_categorical_accuracy did not improve from 0.50000

Epoch 00063: val_categorical_accuracy did not improve from 0.50000

Epoch 00064: val_categorical_accuracy did not improve from 0.50000

Epoch 00065: val_categorical_accuracy did not improve from 0.50000

Epoch 00066: val_categorical_accuracy did not improve from 0.50000

Epoch 00067: val_categorical_accuracy did not improve from 0.50000

Epoch 00068: val_categorical_accuracy did not improve from 0.50000

Epoch 00069: val_categorical_accuracy did not improve from 0.50000

Epoch 00070: val_categorical_accuracy did not improve from 0.50000

Epoch 00071: val_categorical_accuracy improved 


Epoch 00161: val_categorical_accuracy did not improve from 0.57692

Epoch 00162: val_categorical_accuracy did not improve from 0.57692

Epoch 00163: val_categorical_accuracy did not improve from 0.57692

Epoch 00164: val_categorical_accuracy improved from 0.57692 to 0.58462, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_50_With_source_data_as_Salinas_overlap_ratio_75_percent.h5

Epoch 00165: val_categorical_accuracy did not improve from 0.58462

Epoch 00166: val_categorical_accuracy did not improve from 0.58462

Epoch 00167: val_categorical_accuracy did not improve from 0.58462

Epoch 00168: val_categorical_accuracy did not improve from 0.58462

Epoch 00169: val_categorical_accuracy did not improve from 0.58462

Epoch 00170: val_categorical_accuracy did not improve from 0.58462

Epoch 00171: val_categorical_accuracy did not improve from 0.58462

Epoch 00172: val_categorical_accuracy did not impro


Epoch 00273: val_categorical_accuracy did not improve from 0.60000

Epoch 00274: val_categorical_accuracy did not improve from 0.60000

Epoch 00275: val_categorical_accuracy did not improve from 0.60000

Epoch 00276: val_categorical_accuracy did not improve from 0.60000

Epoch 00277: val_categorical_accuracy did not improve from 0.60000

Epoch 00278: val_categorical_accuracy did not improve from 0.60000

Epoch 00279: val_categorical_accuracy did not improve from 0.60000

Epoch 00280: val_categorical_accuracy did not improve from 0.60000

Epoch 00281: val_categorical_accuracy did not improve from 0.60000

Epoch 00282: val_categorical_accuracy did not improve from 0.60000

Epoch 00283: val_categorical_accuracy did not improve from 0.60000

Epoch 00284: val_categorical_accuracy did not improve from 0.60000

Epoch 00285: val_categorical_accuracy did not improve from 0.60000

Epoch 00286: val_categorical_accuracy did not improve from 0.60000

Epoch 00287: val_categorical_accuracy did not i

(1206, 103, 24, 24, 1) (304, 103, 24, 24, 1) (1206,) (304,)
Total samples per class: [264, 425, 74, 244, 48, 139, 45, 203, 68], Total number of samples is 1510.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 304.
number of samples per class in Ytest: [53 85 15 49 10 28  9 41 14]

Xtrain_transfer => (1206, 64)
Xtest_transfer  => (1206, 64)
Ytrain => (1206, 9)
Ytest  => (304, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_11 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
___________________________


Epoch 00050: val_categorical_accuracy did not improve from 0.53618

Epoch 00051: val_categorical_accuracy did not improve from 0.53618

Epoch 00052: val_categorical_accuracy did not improve from 0.53618

Epoch 00053: val_categorical_accuracy did not improve from 0.53618

Epoch 00054: val_categorical_accuracy did not improve from 0.53618

Epoch 00055: val_categorical_accuracy did not improve from 0.53618

Epoch 00056: val_categorical_accuracy improved from 0.53618 to 0.53947, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Salinas_overlap_ratio_75_percent.h5

Epoch 00057: val_categorical_accuracy did not improve from 0.53947

Epoch 00058: val_categorical_accuracy did not improve from 0.53947

Epoch 00059: val_categorical_accuracy did not improve from 0.53947

Epoch 00060: val_categorical_accuracy did not improve from 0.53947

Epoch 00061: val_categorical_accuracy did not impro


Epoch 00149: val_categorical_accuracy did not improve from 0.57895

Epoch 00150: val_categorical_accuracy did not improve from 0.57895

Epoch 00151: val_categorical_accuracy did not improve from 0.57895

Epoch 00152: val_categorical_accuracy did not improve from 0.57895

Epoch 00153: val_categorical_accuracy did not improve from 0.57895

Epoch 00154: val_categorical_accuracy improved from 0.57895 to 0.58224, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Salinas_overlap_ratio_75_percent.h5

Epoch 00155: val_categorical_accuracy did not improve from 0.58224

Epoch 00156: val_categorical_accuracy did not improve from 0.58224

Epoch 00157: val_categorical_accuracy did not improve from 0.58224

Epoch 00158: val_categorical_accuracy did not improve from 0.58224

Epoch 00159: val_categorical_accuracy did not improve from 0.58224

Epoch 00160: val_categorical_accuracy did not impro


Epoch 00256: val_categorical_accuracy did not improve from 0.60197

Epoch 00257: val_categorical_accuracy did not improve from 0.60197

Epoch 00258: val_categorical_accuracy did not improve from 0.60197

Epoch 00259: val_categorical_accuracy did not improve from 0.60197

Epoch 00260: val_categorical_accuracy did not improve from 0.60197

Epoch 00261: val_categorical_accuracy did not improve from 0.60197

Epoch 00262: val_categorical_accuracy did not improve from 0.60197

Epoch 00263: val_categorical_accuracy did not improve from 0.60197

Epoch 00264: val_categorical_accuracy did not improve from 0.60197

Epoch 00265: val_categorical_accuracy did not improve from 0.60197

Epoch 00266: val_categorical_accuracy did not improve from 0.60197

Epoch 00267: val_categorical_accuracy did not improve from 0.60197

Epoch 00268: val_categorical_accuracy did not improve from 0.60197

Epoch 00269: val_categorical_accuracy improved from 0.60197 to 0.60526, saving model to ..\..\Trained Models\Transf

(13491, 103, 24, 24, 1) (3377, 103, 24, 24, 1) (13491,) (3377,)
Total samples per class: [2838, 6243, 775, 1409, 636, 2174, 603, 1758, 432], Total number of samples is 16868.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 3377.
number of samples per class in Ytest: [ 568 1249  155  282  128  435  121  352   87]

Xtrain_transfer => (13491, 64)
Xtest_transfer  => (13491, 64)
Ytrain => (13491, 9)
Ytest  => (3377, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_12 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable 


Epoch 00040: val_categorical_accuracy did not improve from 0.68315

Epoch 00041: val_categorical_accuracy did not improve from 0.68315

Epoch 00042: val_categorical_accuracy did not improve from 0.68315

Epoch 00043: val_categorical_accuracy did not improve from 0.68315

Epoch 00044: val_categorical_accuracy did not improve from 0.68315

Epoch 00045: val_categorical_accuracy did not improve from 0.68315

Epoch 00046: val_categorical_accuracy improved from 0.68315 to 0.68345, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_75_percent.h5

Epoch 00047: val_categorical_accuracy did not improve from 0.68345

Epoch 00048: val_categorical_accuracy did not improve from 0.68345

Epoch 00049: val_categorical_accuracy did not improve from 0.68345

Epoch 00050: val_categorical_accuracy improved from 0.68345 to 0.68493, saving model to ..\..\Trained Models\Transfered


Epoch 00143: val_categorical_accuracy did not improve from 0.70210

Epoch 00144: val_categorical_accuracy did not improve from 0.70210

Epoch 00145: val_categorical_accuracy did not improve from 0.70210

Epoch 00146: val_categorical_accuracy did not improve from 0.70210

Epoch 00147: val_categorical_accuracy did not improve from 0.70210

Epoch 00148: val_categorical_accuracy did not improve from 0.70210

Epoch 00149: val_categorical_accuracy did not improve from 0.70210

Epoch 00150: val_categorical_accuracy did not improve from 0.70210

Epoch 00151: val_categorical_accuracy did not improve from 0.70210

Epoch 00152: val_categorical_accuracy did not improve from 0.70210

Epoch 00153: val_categorical_accuracy did not improve from 0.70210

Epoch 00154: val_categorical_accuracy did not improve from 0.70210

Epoch 00155: val_categorical_accuracy did not improve from 0.70210

Epoch 00156: val_categorical_accuracy did not improve from 0.70210

Epoch 00157: val_categorical_accuracy did not i


Epoch 00264: val_categorical_accuracy did not improve from 0.70210

Epoch 00265: val_categorical_accuracy did not improve from 0.70210

Epoch 00266: val_categorical_accuracy did not improve from 0.70210

Epoch 00267: val_categorical_accuracy did not improve from 0.70210

Epoch 00268: val_categorical_accuracy did not improve from 0.70210

Epoch 00269: val_categorical_accuracy did not improve from 0.70210

Epoch 00270: val_categorical_accuracy did not improve from 0.70210

Epoch 00271: val_categorical_accuracy did not improve from 0.70210

Epoch 00272: val_categorical_accuracy did not improve from 0.70210

Epoch 00273: val_categorical_accuracy did not improve from 0.70210

Epoch 00274: val_categorical_accuracy did not improve from 0.70210

Epoch 00275: val_categorical_accuracy did not improve from 0.70210

Epoch 00276: val_categorical_accuracy did not improve from 0.70210

Epoch 00277: val_categorical_accuracy did not improve from 0.70210

Epoch 00278: val_categorical_accuracy did not i

(309, 103, 24, 24, 1) (82, 103, 24, 24, 1) (309,) (82,)
Total samples per class: [74, 72, 19, 98, 12, 19, 10, 56, 31], Total number of samples is 391.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 82.
number of samples per class in Ytest: [15 15  4 20  3  4  2 12  7]

Xtrain_transfer => (309, 64)
Xtest_transfer  => (309, 64)
Ytrain => (309, 9)
Ytest  => (82, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_13 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
__________________________________________


Epoch 00066: val_categorical_accuracy did not improve from 0.50000

Epoch 00067: val_categorical_accuracy did not improve from 0.50000

Epoch 00068: val_categorical_accuracy did not improve from 0.50000

Epoch 00069: val_categorical_accuracy did not improve from 0.50000

Epoch 00070: val_categorical_accuracy did not improve from 0.50000

Epoch 00071: val_categorical_accuracy did not improve from 0.50000

Epoch 00072: val_categorical_accuracy did not improve from 0.50000

Epoch 00073: val_categorical_accuracy did not improve from 0.50000

Epoch 00074: val_categorical_accuracy improved from 0.50000 to 0.51220, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_25_With_source_data_as_Salinas_overlap_ratio_95_percent.h5

Epoch 00075: val_categorical_accuracy did not improve from 0.51220

Epoch 00076: val_categorical_accuracy did not improve from 0.51220

Epoch 00077: val_categorical_accuracy did not impro


Epoch 00181: val_categorical_accuracy did not improve from 0.54878

Epoch 00182: val_categorical_accuracy did not improve from 0.54878

Epoch 00183: val_categorical_accuracy did not improve from 0.54878

Epoch 00184: val_categorical_accuracy did not improve from 0.54878

Epoch 00185: val_categorical_accuracy did not improve from 0.54878

Epoch 00186: val_categorical_accuracy did not improve from 0.54878

Epoch 00187: val_categorical_accuracy did not improve from 0.54878

Epoch 00188: val_categorical_accuracy did not improve from 0.54878

Epoch 00189: val_categorical_accuracy did not improve from 0.54878

Epoch 00190: val_categorical_accuracy did not improve from 0.54878

Epoch 00191: val_categorical_accuracy did not improve from 0.54878

Epoch 00192: val_categorical_accuracy did not improve from 0.54878

Epoch 00193: val_categorical_accuracy did not improve from 0.54878

Epoch 00194: val_categorical_accuracy improved from 0.54878 to 0.56098, saving model to ..\..\Trained Models\Transf


Epoch 00298: val_categorical_accuracy did not improve from 0.57317

Epoch 00299: val_categorical_accuracy did not improve from 0.57317

Epoch 00300: val_categorical_accuracy did not improve from 0.57317
82/82 [==============================] - 0s 249us/sample - loss: 1.3367 - categorical_accuracy: 0.5488
Test Accuracy = 0.5487805
82/82 [==============================] - 0s 4ms/sample

============ Confusion_matrix for data with source overlap ratio of 95 and target overlap ratio of  25 is as below ============

[[ 3  7  0  2  0  0  0  1  2]
 [ 0 14  0  1  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  3  0]
 [ 1  2  1 15  0  0  0  0  1]
 [ 0  0  0  1  2  0  0  0  0]
 [ 1  2  0  1  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  1  0]
 [ 1  0  2  1  0  0  0  8  0]
 [ 1  0  1  3  0  0  0  0  2]]
[15 15  4 20  3  4  2 12  7]


= Source Model with overlap ratio of 95% will be transfered to Target Data with overlap ratio of 50%, Source Model shown below =


Model: "model_3"
________________________________

(505, 103, 24, 24, 1) (130, 103, 24, 24, 1) (505,) (130,)
Total samples per class: [115, 139, 30, 133, 22, 44, 17, 96, 39], Total number of samples is 635.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 130.
number of samples per class in Ytest: [23 28  6 27  5  9  4 20  8]

Xtrain_transfer => (505, 64)
Xtest_transfer  => (505, 64)
Ytrain => (505, 9)
Ytest  => (130, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_14 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
___________________________________


Epoch 00053: val_categorical_accuracy did not improve from 0.56923

Epoch 00054: val_categorical_accuracy did not improve from 0.56923

Epoch 00055: val_categorical_accuracy did not improve from 0.56923

Epoch 00056: val_categorical_accuracy did not improve from 0.56923

Epoch 00057: val_categorical_accuracy did not improve from 0.56923

Epoch 00058: val_categorical_accuracy did not improve from 0.56923

Epoch 00059: val_categorical_accuracy did not improve from 0.56923

Epoch 00060: val_categorical_accuracy did not improve from 0.56923

Epoch 00061: val_categorical_accuracy did not improve from 0.56923

Epoch 00062: val_categorical_accuracy did not improve from 0.56923

Epoch 00063: val_categorical_accuracy did not improve from 0.56923

Epoch 00064: val_categorical_accuracy did not improve from 0.56923

Epoch 00065: val_categorical_accuracy did not improve from 0.56923

Epoch 00066: val_categorical_accuracy did not improve from 0.56923

Epoch 00067: val_categorical_accuracy did not i


Epoch 00166: val_categorical_accuracy did not improve from 0.63077

Epoch 00167: val_categorical_accuracy did not improve from 0.63077

Epoch 00168: val_categorical_accuracy did not improve from 0.63077

Epoch 00169: val_categorical_accuracy did not improve from 0.63077

Epoch 00170: val_categorical_accuracy did not improve from 0.63077

Epoch 00171: val_categorical_accuracy did not improve from 0.63077

Epoch 00172: val_categorical_accuracy did not improve from 0.63077

Epoch 00173: val_categorical_accuracy did not improve from 0.63077

Epoch 00174: val_categorical_accuracy did not improve from 0.63077

Epoch 00175: val_categorical_accuracy did not improve from 0.63077

Epoch 00176: val_categorical_accuracy did not improve from 0.63077

Epoch 00177: val_categorical_accuracy did not improve from 0.63077

Epoch 00178: val_categorical_accuracy did not improve from 0.63077

Epoch 00179: val_categorical_accuracy did not improve from 0.63077

Epoch 00180: val_categorical_accuracy did not i


Epoch 00281: val_categorical_accuracy did not improve from 0.65385

Epoch 00282: val_categorical_accuracy did not improve from 0.65385

Epoch 00283: val_categorical_accuracy did not improve from 0.65385

Epoch 00284: val_categorical_accuracy did not improve from 0.65385

Epoch 00285: val_categorical_accuracy did not improve from 0.65385

Epoch 00286: val_categorical_accuracy improved from 0.65385 to 0.66154, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_50_With_source_data_as_Salinas_overlap_ratio_95_percent.h5

Epoch 00287: val_categorical_accuracy did not improve from 0.66154

Epoch 00288: val_categorical_accuracy did not improve from 0.66154

Epoch 00289: val_categorical_accuracy did not improve from 0.66154

Epoch 00290: val_categorical_accuracy did not improve from 0.66154

Epoch 00291: val_categorical_accuracy did not improve from 0.66154

Epoch 00292: val_categorical_accuracy did not impro

(1206, 103, 24, 24, 1) (304, 103, 24, 24, 1) (1206,) (304,)
Total samples per class: [264, 425, 74, 244, 48, 139, 45, 203, 68], Total number of samples is 1510.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 304.
number of samples per class in Ytest: [53 85 15 49 10 28  9 41 14]

Xtrain_transfer => (1206, 64)
Xtest_transfer  => (1206, 64)
Ytrain => (1206, 9)
Ytest  => (304, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_15 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
___________________________


Epoch 00047: val_categorical_accuracy did not improve from 0.55592

Epoch 00048: val_categorical_accuracy improved from 0.55592 to 0.56579, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Salinas_overlap_ratio_95_percent.h5

Epoch 00049: val_categorical_accuracy did not improve from 0.56579

Epoch 00050: val_categorical_accuracy did not improve from 0.56579

Epoch 00051: val_categorical_accuracy did not improve from 0.56579

Epoch 00052: val_categorical_accuracy improved from 0.56579 to 0.57237, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Salinas_overlap_ratio_95_percent.h5

Epoch 00053: val_categorical_accuracy did not improve from 0.57237

Epoch 00054: val_categorical_accuracy improved from 0.57237 to 0.58882, saving model to ..\..\Trained Models\Transfered_Mod


Epoch 00133: val_categorical_accuracy did not improve from 0.64145

Epoch 00134: val_categorical_accuracy did not improve from 0.64145

Epoch 00135: val_categorical_accuracy did not improve from 0.64145

Epoch 00136: val_categorical_accuracy did not improve from 0.64145

Epoch 00137: val_categorical_accuracy did not improve from 0.64145

Epoch 00138: val_categorical_accuracy did not improve from 0.64145

Epoch 00139: val_categorical_accuracy improved from 0.64145 to 0.64474, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Salinas_overlap_ratio_95_percent.h5

Epoch 00140: val_categorical_accuracy did not improve from 0.64474

Epoch 00141: val_categorical_accuracy did not improve from 0.64474

Epoch 00142: val_categorical_accuracy did not improve from 0.64474

Epoch 00143: val_categorical_accuracy improved from 0.64474 to 0.64803, saving model to ..\..\Trained Models\Transfered


Epoch 00246: val_categorical_accuracy did not improve from 0.66118

Epoch 00247: val_categorical_accuracy did not improve from 0.66118

Epoch 00248: val_categorical_accuracy did not improve from 0.66118

Epoch 00249: val_categorical_accuracy did not improve from 0.66118

Epoch 00250: val_categorical_accuracy did not improve from 0.66118

Epoch 00251: val_categorical_accuracy did not improve from 0.66118

Epoch 00252: val_categorical_accuracy did not improve from 0.66118

Epoch 00253: val_categorical_accuracy did not improve from 0.66118

Epoch 00254: val_categorical_accuracy did not improve from 0.66118

Epoch 00255: val_categorical_accuracy did not improve from 0.66118

Epoch 00256: val_categorical_accuracy did not improve from 0.66118

Epoch 00257: val_categorical_accuracy did not improve from 0.66118

Epoch 00258: val_categorical_accuracy did not improve from 0.66118

Epoch 00259: val_categorical_accuracy did not improve from 0.66118

Epoch 00260: val_categorical_accuracy did not i

(13491, 103, 24, 24, 1) (3377, 103, 24, 24, 1) (13491,) (3377,)
Total samples per class: [2838, 6243, 775, 1409, 636, 2174, 603, 1758, 432], Total number of samples is 16868.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 3377.
number of samples per class in Ytest: [ 568 1249  155  282  128  435  121  352   87]

Xtrain_transfer => (13491, 64)
Xtest_transfer  => (13491, 64)
Ytrain => (13491, 9)
Ytest  => (3377, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_16 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable 


Epoch 00033: val_categorical_accuracy did not improve from 0.72905

Epoch 00034: val_categorical_accuracy did not improve from 0.72905

Epoch 00035: val_categorical_accuracy improved from 0.72905 to 0.73379, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_95_percent.h5

Epoch 00036: val_categorical_accuracy did not improve from 0.73379

Epoch 00037: val_categorical_accuracy did not improve from 0.73379

Epoch 00038: val_categorical_accuracy improved from 0.73379 to 0.73823, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Salinas_overlap_ratio_95_percent.h5

Epoch 00039: val_categorical_accuracy did not improve from 0.73823

Epoch 00040: val_categorical_accuracy did not improve from 0.73823

Epoch 00041: val_categorical_accuracy did not improve f


Epoch 00128: val_categorical_accuracy did not improve from 0.75333

Epoch 00129: val_categorical_accuracy did not improve from 0.75333

Epoch 00130: val_categorical_accuracy did not improve from 0.75333

Epoch 00131: val_categorical_accuracy did not improve from 0.75333

Epoch 00132: val_categorical_accuracy did not improve from 0.75333

Epoch 00133: val_categorical_accuracy did not improve from 0.75333

Epoch 00134: val_categorical_accuracy did not improve from 0.75333

Epoch 00135: val_categorical_accuracy did not improve from 0.75333

Epoch 00136: val_categorical_accuracy did not improve from 0.75333

Epoch 00137: val_categorical_accuracy did not improve from 0.75333

Epoch 00138: val_categorical_accuracy did not improve from 0.75333

Epoch 00139: val_categorical_accuracy did not improve from 0.75333

Epoch 00140: val_categorical_accuracy did not improve from 0.75333

Epoch 00141: val_categorical_accuracy did not improve from 0.75333

Epoch 00142: val_categorical_accuracy did not i


Epoch 00240: val_categorical_accuracy did not improve from 0.75688

Epoch 00241: val_categorical_accuracy did not improve from 0.75688

Epoch 00242: val_categorical_accuracy did not improve from 0.75688

Epoch 00243: val_categorical_accuracy did not improve from 0.75688

Epoch 00244: val_categorical_accuracy did not improve from 0.75688

Epoch 00245: val_categorical_accuracy did not improve from 0.75688

Epoch 00246: val_categorical_accuracy did not improve from 0.75688

Epoch 00247: val_categorical_accuracy did not improve from 0.75688

Epoch 00248: val_categorical_accuracy did not improve from 0.75688

Epoch 00249: val_categorical_accuracy did not improve from 0.75688

Epoch 00250: val_categorical_accuracy did not improve from 0.75688

Epoch 00251: val_categorical_accuracy did not improve from 0.75688

Epoch 00252: val_categorical_accuracy did not improve from 0.75688

Epoch 00253: val_categorical_accuracy did not improve from 0.75688

Epoch 00254: val_categorical_accuracy did not i

In [5]:
Acc_Tbl

0         1         2         3         4
0  Test Accuracy  Pavia_25  Pavia_50  Pavia_75  Pavia_95
1     Salinas_25   65.8537        60   62.1711   72.5496
2     Salinas_50   48.7805   52.3077   56.5789   67.6044
3     Salinas_75   51.2195   57.6923   59.8684   69.4107
4     Salinas_95   54.8781   65.3846   64.8026   75.5108