#  Indian Pines to Salinas 

In [1]:
from Transfer_Model_Utils import *
import scipy.io as sio

In [2]:
uSalinas = sio.loadmat('..\\..\\Salinas\\Salinas_corrected.mat')
gt_uSalinas = sio.loadmat('..\\..\\Salinas\\Salinas_gt.mat')
data_SA = uSalinas['salinas_corrected']
gt_SA = gt_uSalinas['salinas_gt']
print(data_SA.shape, gt_SA.shape)
data_SA = np.moveaxis(data_SA, 2, 0)
print(data_SA.shape, gt_SA.shape)

(512, 217, 204) (512, 217)
(204, 512, 217) (512, 217)


In [3]:
values,counts = np.unique(gt_SA, return_counts=True)
print(values,counts)
range_of_class = list(values)
if 0 in range_of_class:
    range_of_class.pop(0)
range_of_class

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16] [56975  2009  3726  1976  1394  2678  3959  3579 11271  6203  3278  1068
  1927   916  1070  7268  1807]


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

In [4]:
Acc_Tbl = Transfer(overlap_ratio_List_for_Target = [25, 50, 75, 95],
                   overlap_ratio_List_for_Source = [50, 75, 85, 95],
                   epochs_list = [300, 300, 300, 300],
                   batch_size_list = [16, 32, 64, 128],
                   range_of_class = range_of_class,
                   Cube_size = 25,
                   Data = data_SA,
                   Gt = gt_SA,
                   Train_Test_split = 80,
                   channel = 103,
                   Source_data_name = 'Indian_Pines', 
                   Target_data_name = 'Salinas',
                   Verbosity = 0)

                 0           1           2           3           4
0    Test Accuracy  Salinas_25  Salinas_50  Salinas_75  Salinas_95
1  Indian_Pines_50        None        None        None        None
2  Indian_Pines_75        None        None        None        None
3  Indian_Pines_85        None        None        None        None
4  Indian_Pines_95        None        None        None        None


= Source Model with overlap ratio of 50% will be transfered to Target Data with overlap ratio of 25%, Source Model shown below =


Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2

(174, 103, 24, 24, 1) (51, 103, 24, 24, 1) (174,) (51,)
Total samples per class: [9, 16, 8, 10, 17, 17, 15, 40, 23, 14, 6, 9, 7, 7, 23, 4], Total number of samples is 225.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 51.
number of samples per class in Ytest: [2 4 2 2 4 4 3 8 5 3 2 2 2 2 5 1]

Xtrain_transfer => (174, 64)
Xtest_transfer  => (174, 64)
Ytrain => (174, 16)
Ytest  => (51, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainable params: 20,752
Non-trai

Epoch 00067: val_categorical_accuracy did not improve from 0.60784

Epoch 00068: val_categorical_accuracy did not improve from 0.60784

Epoch 00069: val_categorical_accuracy did not improve from 0.60784

Epoch 00070: val_categorical_accuracy did not improve from 0.60784

Epoch 00071: val_categorical_accuracy improved from 0.60784 to 0.62745, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_25_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00072: val_categorical_accuracy did not improve from 0.62745

Epoch 00073: val_categorical_accuracy did not improve from 0.62745

Epoch 00074: val_categorical_accuracy did not improve from 0.62745

Epoch 00075: val_categorical_accuracy did not improve from 0.62745

Epoch 00076: val_categorical_accuracy did not improve from 0.62745

Epoch 00077: val_categorical_accuracy did not improve from 0.62745

Epoch 00078: val_categorical_accuracy did n

Epoch 00176: val_categorical_accuracy did not improve from 0.70588

Epoch 00177: val_categorical_accuracy improved from 0.70588 to 0.72549, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_25_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00178: val_categorical_accuracy did not improve from 0.72549

Epoch 00179: val_categorical_accuracy did not improve from 0.72549

Epoch 00180: val_categorical_accuracy did not improve from 0.72549

Epoch 00181: val_categorical_accuracy did not improve from 0.72549

Epoch 00182: val_categorical_accuracy did not improve from 0.72549

Epoch 00183: val_categorical_accuracy did not improve from 0.72549

Epoch 00184: val_categorical_accuracy did not improve from 0.72549

Epoch 00185: val_categorical_accuracy did not improve from 0.72549

Epoch 00186: val_categorical_accuracy did not improve from 0.72549

Epoch 00187: val_categorical_accuracy did n


Epoch 00291: val_categorical_accuracy did not improve from 0.76471

Epoch 00292: val_categorical_accuracy did not improve from 0.76471

Epoch 00293: val_categorical_accuracy did not improve from 0.76471

Epoch 00294: val_categorical_accuracy did not improve from 0.76471

Epoch 00295: val_categorical_accuracy did not improve from 0.76471

Epoch 00296: val_categorical_accuracy did not improve from 0.76471

Epoch 00297: val_categorical_accuracy did not improve from 0.76471

Epoch 00298: val_categorical_accuracy did not improve from 0.76471

Epoch 00299: val_categorical_accuracy did not improve from 0.76471

Epoch 00300: val_categorical_accuracy did not improve from 0.76471
51/51 [==============================] - 0s 59us/sample - loss: 0.8105 - categorical_accuracy: 0.7255
Test Accuracy = 0.7254902
51/51 [==============================] - 0s 529us/sample

============ Confusion_matrix for data with source overlap ratio of 50 and target overlap ratio of  25 is as below ============

[[2 0

(338, 103, 24, 24, 1) (91, 103, 24, 24, 1) (338,) (91,)
Total samples per class: [15, 32, 17, 14, 26, 35, 30, 80, 51, 27, 10, 17, 9, 10, 47, 9], Total number of samples is 429.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 91.
number of samples per class in Ytest: [ 3  7  4  3  6  7  6 16 11  6  2  4  2  2 10  2]

Xtrain_transfer => (338, 64)
Xtest_transfer  => (338, 64)
Ytrain => (338, 16)
Ytest  => (91, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainable pa


Epoch 00073: val_categorical_accuracy improved from 0.54945 to 0.56044, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_50_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00074: val_categorical_accuracy did not improve from 0.56044

Epoch 00075: val_categorical_accuracy improved from 0.56044 to 0.57143, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_50_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00076: val_categorical_accuracy did not improve from 0.57143

Epoch 00077: val_categorical_accuracy did not improve from 0.57143

Epoch 00078: val_categorical_accuracy did not improve from 0.57143

Epoch 00079: val_categorical_accuracy did not improve from 0.57143

Epoch 00080: val_categorical_accuracy did not improve from 0.57143

Epoch 00081: val_categorical_accuracy


Epoch 00170: val_categorical_accuracy did not improve from 0.65934

Epoch 00171: val_categorical_accuracy did not improve from 0.65934

Epoch 00172: val_categorical_accuracy did not improve from 0.65934

Epoch 00173: val_categorical_accuracy did not improve from 0.65934

Epoch 00174: val_categorical_accuracy did not improve from 0.65934

Epoch 00175: val_categorical_accuracy did not improve from 0.65934

Epoch 00176: val_categorical_accuracy did not improve from 0.65934

Epoch 00177: val_categorical_accuracy did not improve from 0.65934

Epoch 00178: val_categorical_accuracy did not improve from 0.65934

Epoch 00179: val_categorical_accuracy did not improve from 0.65934

Epoch 00180: val_categorical_accuracy did not improve from 0.65934

Epoch 00181: val_categorical_accuracy did not improve from 0.65934

Epoch 00182: val_categorical_accuracy did not improve from 0.65934

Epoch 00183: val_categorical_accuracy did not improve from 0.65934

Epoch 00184: val_categorical_accuracy did not i


Epoch 00285: val_categorical_accuracy did not improve from 0.70330

Epoch 00286: val_categorical_accuracy did not improve from 0.70330

Epoch 00287: val_categorical_accuracy did not improve from 0.70330

Epoch 00288: val_categorical_accuracy did not improve from 0.70330

Epoch 00289: val_categorical_accuracy did not improve from 0.70330

Epoch 00290: val_categorical_accuracy did not improve from 0.70330

Epoch 00291: val_categorical_accuracy did not improve from 0.70330

Epoch 00292: val_categorical_accuracy did not improve from 0.70330

Epoch 00293: val_categorical_accuracy did not improve from 0.70330

Epoch 00294: val_categorical_accuracy did not improve from 0.70330

Epoch 00295: val_categorical_accuracy did not improve from 0.70330

Epoch 00296: val_categorical_accuracy did not improve from 0.70330

Epoch 00297: val_categorical_accuracy did not improve from 0.70330

Epoch 00298: val_categorical_accuracy did not improve from 0.70330

Epoch 00299: val_categorical_accuracy did not i

(1121, 103, 24, 24, 1) (288, 103, 24, 24, 1) (1121,) (288,)
Total samples per class: [47, 104, 56, 50, 81, 109, 96, 287, 168, 83, 30, 52, 30, 30, 162, 24], Total number of samples is 1409.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 288.
number of samples per class in Ytest: [10 21 12 10 17 22 20 58 34 17  6 11  6  6 33  5]

Xtrain_transfer => (1121, 64)
Xtest_transfer  => (1121, 64)
Ytrain => (1121, 16)
Ytest  => (288, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20


Epoch 00040: val_categorical_accuracy improved from 0.54167 to 0.56597, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00041: val_categorical_accuracy did not improve from 0.56597

Epoch 00042: val_categorical_accuracy did not improve from 0.56597

Epoch 00043: val_categorical_accuracy did not improve from 0.56597

Epoch 00044: val_categorical_accuracy improved from 0.56597 to 0.56944, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00045: val_categorical_accuracy did not improve from 0.56944

Epoch 00046: val_categorical_accuracy did not improve from 0.56944

Epoch 00047: val_categorical_accuracy did not improve from 0.56944

Epoch 00048: val_categorical_accuracy


Epoch 00114: val_categorical_accuracy improved from 0.65972 to 0.66319, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00115: val_categorical_accuracy did not improve from 0.66319

Epoch 00116: val_categorical_accuracy did not improve from 0.66319

Epoch 00117: val_categorical_accuracy did not improve from 0.66319

Epoch 00118: val_categorical_accuracy did not improve from 0.66319

Epoch 00119: val_categorical_accuracy did not improve from 0.66319

Epoch 00120: val_categorical_accuracy did not improve from 0.66319

Epoch 00121: val_categorical_accuracy did not improve from 0.66319

Epoch 00122: val_categorical_accuracy did not improve from 0.66319

Epoch 00123: val_categorical_accuracy did not improve from 0.66319

Epoch 00124: val_categorical_accuracy improved from 0.66319 to 0.67014, saving model to ..\..\Trained Models\T


Epoch 00207: val_categorical_accuracy did not improve from 0.71181

Epoch 00208: val_categorical_accuracy did not improve from 0.71181

Epoch 00209: val_categorical_accuracy did not improve from 0.71181

Epoch 00210: val_categorical_accuracy did not improve from 0.71181

Epoch 00211: val_categorical_accuracy did not improve from 0.71181

Epoch 00212: val_categorical_accuracy did not improve from 0.71181

Epoch 00213: val_categorical_accuracy did not improve from 0.71181

Epoch 00214: val_categorical_accuracy did not improve from 0.71181

Epoch 00215: val_categorical_accuracy did not improve from 0.71181

Epoch 00216: val_categorical_accuracy did not improve from 0.71181

Epoch 00217: val_categorical_accuracy did not improve from 0.71181

Epoch 00218: val_categorical_accuracy did not improve from 0.71181

Epoch 00219: val_categorical_accuracy did not improve from 0.71181

Epoch 00220: val_categorical_accuracy did not improve from 0.71181

Epoch 00221: val_categorical_accuracy improved 



= Source Model with overlap ratio of 50% will be transfered to Target Data with overlap ratio of 95%, Source Model shown below =


Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_1[0][0]                    
__________________________________________________________________________________________________
bn_conv_0 (BatchNormalization)  (None, 48, 11, 11, 3 128         conv_0[0][0]                     
__________________________________________________________________________________________________
activation (Activation)         (None, 48, 11, 11, 3 0      

(16239, 103, 24, 24, 1) (4068, 103, 24, 24, 1) (16239,) (4068,)
Total samples per class: [635, 1619, 663, 632, 1143, 1512, 1490, 4327, 2571, 1092, 357, 650, 306, 349, 2620, 341], Total number of samples is 20307.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 4068.
number of samples per class in Ytest: [127 324 133 127 229 303 298 866 515 219  72 130  62  70 524  69]

Xtrain_transfer => (16239, 64)
Xtest_transfer  => (16239, 64)
Ytrain => (16239, 16)
Ytest  => (4068, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 1


Epoch 00033: val_categorical_accuracy did not improve from 0.71411

Epoch 00034: val_categorical_accuracy improved from 0.71411 to 0.71976, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00035: val_categorical_accuracy did not improve from 0.71976

Epoch 00036: val_categorical_accuracy did not improve from 0.71976

Epoch 00037: val_categorical_accuracy improved from 0.71976 to 0.72591, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00038: val_categorical_accuracy did not improve from 0.72591

Epoch 00039: val_categorical_accuracy did not improve from 0.72591

Epoch 00040: val_categorical_accuracy did not improve from 0.72591

Epoch 00041: val_categorical_accuracy


Epoch 00108: val_categorical_accuracy did not improve from 0.80580

Epoch 00109: val_categorical_accuracy did not improve from 0.80580

Epoch 00110: val_categorical_accuracy did not improve from 0.80580

Epoch 00111: val_categorical_accuracy did not improve from 0.80580

Epoch 00112: val_categorical_accuracy did not improve from 0.80580

Epoch 00113: val_categorical_accuracy did not improve from 0.80580

Epoch 00114: val_categorical_accuracy did not improve from 0.80580

Epoch 00115: val_categorical_accuracy did not improve from 0.80580

Epoch 00116: val_categorical_accuracy did not improve from 0.80580

Epoch 00117: val_categorical_accuracy did not improve from 0.80580

Epoch 00118: val_categorical_accuracy improved from 0.80580 to 0.80851, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00119: val_categorical_accuracy did 


Epoch 00207: val_categorical_accuracy did not improve from 0.83899

Epoch 00208: val_categorical_accuracy did not improve from 0.83899

Epoch 00209: val_categorical_accuracy did not improve from 0.83899

Epoch 00210: val_categorical_accuracy did not improve from 0.83899

Epoch 00211: val_categorical_accuracy did not improve from 0.83899

Epoch 00212: val_categorical_accuracy did not improve from 0.83899

Epoch 00213: val_categorical_accuracy did not improve from 0.83899

Epoch 00214: val_categorical_accuracy did not improve from 0.83899

Epoch 00215: val_categorical_accuracy did not improve from 0.83899

Epoch 00216: val_categorical_accuracy did not improve from 0.83899

Epoch 00217: val_categorical_accuracy did not improve from 0.83899

Epoch 00218: val_categorical_accuracy did not improve from 0.83899

Epoch 00219: val_categorical_accuracy did not improve from 0.83899

Epoch 00220: val_categorical_accuracy did not improve from 0.83899

Epoch 00221: val_categorical_accuracy did not i



= Source Model with overlap ratio of 75% will be transfered to Target Data with overlap ratio of 25%, Source Model shown below =


Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_2[0][0]                    
__________________________________________________________________________________________________
bn_conv_0 (BatchNormalization)  (None, 48, 11, 11, 3 128         conv_0[0][0]                     
__________________________________________________________________________________________________
activation_1 (Activation)       (None, 48, 11, 11, 3 0    

(174, 103, 24, 24, 1) (51, 103, 24, 24, 1) (174,) (51,)
Total samples per class: [9, 16, 8, 10, 17, 17, 15, 40, 23, 14, 6, 9, 7, 7, 23, 4], Total number of samples is 225.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 51.
number of samples per class in Ytest: [2 4 2 2 4 4 3 8 5 3 2 2 2 2 5 1]

Xtrain_transfer => (174, 64)
Xtest_transfer  => (174, 64)
Ytrain => (174, 16)
Ytest  => (51, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainable params: 20,752
Non-trai


Epoch 00073: val_categorical_accuracy did not improve from 0.60784

Epoch 00074: val_categorical_accuracy did not improve from 0.60784

Epoch 00075: val_categorical_accuracy did not improve from 0.60784

Epoch 00076: val_categorical_accuracy did not improve from 0.60784

Epoch 00077: val_categorical_accuracy did not improve from 0.60784

Epoch 00078: val_categorical_accuracy improved from 0.60784 to 0.62745, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_25_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00079: val_categorical_accuracy did not improve from 0.62745

Epoch 00080: val_categorical_accuracy did not improve from 0.62745

Epoch 00081: val_categorical_accuracy did not improve from 0.62745

Epoch 00082: val_categorical_accuracy did not improve from 0.62745

Epoch 00083: val_categorical_accuracy did not improve from 0.62745

Epoch 00084: val_categorical_accuracy did 


Epoch 00186: val_categorical_accuracy did not improve from 0.68627

Epoch 00187: val_categorical_accuracy did not improve from 0.68627

Epoch 00188: val_categorical_accuracy did not improve from 0.68627

Epoch 00189: val_categorical_accuracy did not improve from 0.68627

Epoch 00190: val_categorical_accuracy did not improve from 0.68627

Epoch 00191: val_categorical_accuracy did not improve from 0.68627

Epoch 00192: val_categorical_accuracy did not improve from 0.68627

Epoch 00193: val_categorical_accuracy did not improve from 0.68627

Epoch 00194: val_categorical_accuracy did not improve from 0.68627

Epoch 00195: val_categorical_accuracy did not improve from 0.68627

Epoch 00196: val_categorical_accuracy did not improve from 0.68627

Epoch 00197: val_categorical_accuracy did not improve from 0.68627

Epoch 00198: val_categorical_accuracy did not improve from 0.68627

Epoch 00199: val_categorical_accuracy did not improve from 0.68627

Epoch 00200: val_categorical_accuracy did not i

51/51 [==============================] - 0s 0s/sample - loss: 0.8953 - categorical_accuracy: 0.6863
Test Accuracy = 0.6862745
51/51 [==============================] - 0s 2ms/sample

============ Confusion_matrix for data with source overlap ratio of 75 and target overlap ratio of  25 is as below ============

[[0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 8 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 5 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 5 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]]
[2 4 2 2 4 4 3 8 5 3 2 2 2 2 5 1]


= Source Model with overlap ratio of 75% will be transfered to Target Data with overlap rati

(338, 103, 24, 24, 1) (91, 103, 24, 24, 1) (338,) (91,)
Total samples per class: [15, 32, 17, 14, 26, 35, 30, 80, 51, 27, 10, 17, 9, 10, 47, 9], Total number of samples is 429.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 91.
number of samples per class in Ytest: [ 3  7  4  3  6  7  6 16 11  6  2  4  2  2 10  2]

Xtrain_transfer => (338, 64)
Xtest_transfer  => (338, 64)
Ytrain => (338, 16)
Ytest  => (91, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainable pa


Epoch 00062: val_categorical_accuracy did not improve from 0.58242

Epoch 00063: val_categorical_accuracy did not improve from 0.58242

Epoch 00064: val_categorical_accuracy did not improve from 0.58242

Epoch 00065: val_categorical_accuracy did not improve from 0.58242

Epoch 00066: val_categorical_accuracy did not improve from 0.58242

Epoch 00067: val_categorical_accuracy did not improve from 0.58242

Epoch 00068: val_categorical_accuracy did not improve from 0.58242

Epoch 00069: val_categorical_accuracy did not improve from 0.58242

Epoch 00070: val_categorical_accuracy did not improve from 0.58242

Epoch 00071: val_categorical_accuracy did not improve from 0.58242

Epoch 00072: val_categorical_accuracy did not improve from 0.58242

Epoch 00073: val_categorical_accuracy did not improve from 0.58242

Epoch 00074: val_categorical_accuracy did not improve from 0.58242

Epoch 00075: val_categorical_accuracy did not improve from 0.58242

Epoch 00076: val_categorical_accuracy did not i


Epoch 00168: val_categorical_accuracy did not improve from 0.65934

Epoch 00169: val_categorical_accuracy did not improve from 0.65934

Epoch 00170: val_categorical_accuracy did not improve from 0.65934

Epoch 00171: val_categorical_accuracy did not improve from 0.65934

Epoch 00172: val_categorical_accuracy did not improve from 0.65934

Epoch 00173: val_categorical_accuracy did not improve from 0.65934

Epoch 00174: val_categorical_accuracy did not improve from 0.65934

Epoch 00175: val_categorical_accuracy improved from 0.65934 to 0.67033, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_50_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00176: val_categorical_accuracy did not improve from 0.67033

Epoch 00177: val_categorical_accuracy did not improve from 0.67033

Epoch 00178: val_categorical_accuracy did not improve from 0.67033

Epoch 00179: val_categorical_accuracy did 


Epoch 00282: val_categorical_accuracy did not improve from 0.69231

Epoch 00283: val_categorical_accuracy did not improve from 0.69231

Epoch 00284: val_categorical_accuracy did not improve from 0.69231

Epoch 00285: val_categorical_accuracy did not improve from 0.69231

Epoch 00286: val_categorical_accuracy did not improve from 0.69231

Epoch 00287: val_categorical_accuracy did not improve from 0.69231

Epoch 00288: val_categorical_accuracy did not improve from 0.69231

Epoch 00289: val_categorical_accuracy did not improve from 0.69231

Epoch 00290: val_categorical_accuracy did not improve from 0.69231

Epoch 00291: val_categorical_accuracy did not improve from 0.69231

Epoch 00292: val_categorical_accuracy improved from 0.69231 to 0.70330, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_50_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00293: val_categorical_accuracy did 

(1121, 103, 24, 24, 1) (288, 103, 24, 24, 1) (1121,) (288,)
Total samples per class: [47, 104, 56, 50, 81, 109, 96, 287, 168, 83, 30, 52, 30, 30, 162, 24], Total number of samples is 1409.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 288.
number of samples per class in Ytest: [10 21 12 10 17 22 20 58 34 17  6 11  6  6 33  5]

Xtrain_transfer => (1121, 64)
Xtest_transfer  => (1121, 64)
Ytrain => (1121, 16)
Ytest  => (288, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20


Epoch 00050: val_categorical_accuracy did not improve from 0.59722

Epoch 00051: val_categorical_accuracy did not improve from 0.59722

Epoch 00052: val_categorical_accuracy improved from 0.59722 to 0.60069, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00053: val_categorical_accuracy did not improve from 0.60069

Epoch 00054: val_categorical_accuracy did not improve from 0.60069

Epoch 00055: val_categorical_accuracy did not improve from 0.60069

Epoch 00056: val_categorical_accuracy did not improve from 0.60069

Epoch 00057: val_categorical_accuracy improved from 0.60069 to 0.60417, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00058: val_categorical_accuracy


Epoch 00125: val_categorical_accuracy did not improve from 0.67708

Epoch 00126: val_categorical_accuracy did not improve from 0.67708

Epoch 00127: val_categorical_accuracy did not improve from 0.67708

Epoch 00128: val_categorical_accuracy did not improve from 0.67708

Epoch 00129: val_categorical_accuracy improved from 0.67708 to 0.68403, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00130: val_categorical_accuracy did not improve from 0.68403

Epoch 00131: val_categorical_accuracy did not improve from 0.68403

Epoch 00132: val_categorical_accuracy did not improve from 0.68403

Epoch 00133: val_categorical_accuracy did not improve from 0.68403

Epoch 00134: val_categorical_accuracy did not improve from 0.68403

Epoch 00135: val_categorical_accuracy did not improve from 0.68403

Epoch 00136: val_categorical_accuracy impr


Epoch 00219: val_categorical_accuracy did not improve from 0.72917

Epoch 00220: val_categorical_accuracy did not improve from 0.72917

Epoch 00221: val_categorical_accuracy did not improve from 0.72917

Epoch 00222: val_categorical_accuracy did not improve from 0.72917

Epoch 00223: val_categorical_accuracy did not improve from 0.72917

Epoch 00224: val_categorical_accuracy did not improve from 0.72917

Epoch 00225: val_categorical_accuracy improved from 0.72917 to 0.73264, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00226: val_categorical_accuracy did not improve from 0.73264

Epoch 00227: val_categorical_accuracy did not improve from 0.73264

Epoch 00228: val_categorical_accuracy improved from 0.73264 to 0.74306, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected

(16239, 103, 24, 24, 1) (4068, 103, 24, 24, 1) (16239,) (4068,)
Total samples per class: [635, 1619, 663, 632, 1143, 1512, 1490, 4327, 2571, 1092, 357, 650, 306, 349, 2620, 341], Total number of samples is 20307.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 4068.
number of samples per class in Ytest: [127 324 133 127 229 303 298 866 515 219  72 130  62  70 524  69]

Xtrain_transfer => (16239, 64)
Xtest_transfer  => (16239, 64)
Ytrain => (16239, 16)
Ytest  => (4068, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 1


Epoch 00027: val_categorical_accuracy improved from 0.72566 to 0.73845, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00028: val_categorical_accuracy did not improve from 0.73845

Epoch 00029: val_categorical_accuracy did not improve from 0.73845

Epoch 00030: val_categorical_accuracy did not improve from 0.73845

Epoch 00031: val_categorical_accuracy did not improve from 0.73845

Epoch 00032: val_categorical_accuracy improved from 0.73845 to 0.74361, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00033: val_categorical_accuracy improved from 0.74361 to 0.74459, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Conn


Epoch 00092: val_categorical_accuracy did not improve from 0.83800

Epoch 00093: val_categorical_accuracy did not improve from 0.83800

Epoch 00094: val_categorical_accuracy did not improve from 0.83800

Epoch 00095: val_categorical_accuracy did not improve from 0.83800

Epoch 00096: val_categorical_accuracy did not improve from 0.83800

Epoch 00097: val_categorical_accuracy did not improve from 0.83800

Epoch 00098: val_categorical_accuracy did not improve from 0.83800

Epoch 00099: val_categorical_accuracy did not improve from 0.83800

Epoch 00100: val_categorical_accuracy did not improve from 0.83800

Epoch 00101: val_categorical_accuracy did not improve from 0.83800

Epoch 00102: val_categorical_accuracy did not improve from 0.83800

Epoch 00103: val_categorical_accuracy did not improve from 0.83800

Epoch 00104: val_categorical_accuracy did not improve from 0.83800

Epoch 00105: val_categorical_accuracy did not improve from 0.83800

Epoch 00106: val_categorical_accuracy did not i


Epoch 00198: val_categorical_accuracy did not improve from 0.85939

Epoch 00199: val_categorical_accuracy did not improve from 0.85939

Epoch 00200: val_categorical_accuracy improved from 0.85939 to 0.87094, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00201: val_categorical_accuracy did not improve from 0.87094

Epoch 00202: val_categorical_accuracy did not improve from 0.87094

Epoch 00203: val_categorical_accuracy did not improve from 0.87094

Epoch 00204: val_categorical_accuracy did not improve from 0.87094

Epoch 00205: val_categorical_accuracy did not improve from 0.87094

Epoch 00206: val_categorical_accuracy did not improve from 0.87094

Epoch 00207: val_categorical_accuracy did not improve from 0.87094

Epoch 00208: val_categorical_accuracy did not improve from 0.87094

Epoch 00209: val_categorical_accuracy did 



= Source Model with overlap ratio of 85% will be transfered to Target Data with overlap ratio of 25%, Source Model shown below =


Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_3[0][0]                    
__________________________________________________________________________________________________
bn_conv_0 (BatchNormalization)  (None, 48, 11, 11, 3 128         conv_0[0][0]                     
__________________________________________________________________________________________________
activation_2 (Activation)       (None, 48, 11, 11, 3 0    

(174, 103, 24, 24, 1) (51, 103, 24, 24, 1) (174,) (51,)
Total samples per class: [9, 16, 8, 10, 17, 17, 15, 40, 23, 14, 6, 9, 7, 7, 23, 4], Total number of samples is 225.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 51.
number of samples per class in Ytest: [2 4 2 2 4 4 3 8 5 3 2 2 2 2 5 1]

Xtrain_transfer => (174, 64)
Xtest_transfer  => (174, 64)
Ytrain => (174, 16)
Ytest  => (51, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainable params: 20,752
Non-trai


Epoch 00065: val_categorical_accuracy did not improve from 0.66667

Epoch 00066: val_categorical_accuracy did not improve from 0.66667

Epoch 00067: val_categorical_accuracy did not improve from 0.66667

Epoch 00068: val_categorical_accuracy did not improve from 0.66667

Epoch 00069: val_categorical_accuracy did not improve from 0.66667

Epoch 00070: val_categorical_accuracy did not improve from 0.66667

Epoch 00071: val_categorical_accuracy did not improve from 0.66667

Epoch 00072: val_categorical_accuracy did not improve from 0.66667

Epoch 00073: val_categorical_accuracy did not improve from 0.66667

Epoch 00074: val_categorical_accuracy did not improve from 0.66667

Epoch 00075: val_categorical_accuracy did not improve from 0.66667

Epoch 00076: val_categorical_accuracy did not improve from 0.66667

Epoch 00077: val_categorical_accuracy did not improve from 0.66667

Epoch 00078: val_categorical_accuracy did not improve from 0.66667

Epoch 00079: val_categorical_accuracy did not i


Epoch 00181: val_categorical_accuracy did not improve from 0.74510

Epoch 00182: val_categorical_accuracy did not improve from 0.74510

Epoch 00183: val_categorical_accuracy did not improve from 0.74510

Epoch 00184: val_categorical_accuracy did not improve from 0.74510

Epoch 00185: val_categorical_accuracy did not improve from 0.74510

Epoch 00186: val_categorical_accuracy did not improve from 0.74510

Epoch 00187: val_categorical_accuracy did not improve from 0.74510

Epoch 00188: val_categorical_accuracy did not improve from 0.74510

Epoch 00189: val_categorical_accuracy did not improve from 0.74510

Epoch 00190: val_categorical_accuracy did not improve from 0.74510

Epoch 00191: val_categorical_accuracy did not improve from 0.74510

Epoch 00192: val_categorical_accuracy did not improve from 0.74510

Epoch 00193: val_categorical_accuracy did not improve from 0.74510

Epoch 00194: val_categorical_accuracy did not improve from 0.74510

Epoch 00195: val_categorical_accuracy did not i

51/51 [==============================] - 0s 118us/sample - loss: 0.8018 - categorical_accuracy: 0.7255
Test Accuracy = 0.7254902
51/51 [==============================] - 0s 5ms/sample

============ Confusion_matrix for data with source overlap ratio of 85 and target overlap ratio of  25 is as below ============

[[2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 3 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 8 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 5 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 5 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]]
[2 4 2 2 4 4 3 8 5 3 2 2 2 2 5 1]


= Source Model with overlap ratio of 85% will be transfered to Target Data with overlap r

(338, 103, 24, 24, 1) (91, 103, 24, 24, 1) (338,) (91,)
Total samples per class: [15, 32, 17, 14, 26, 35, 30, 80, 51, 27, 10, 17, 9, 10, 47, 9], Total number of samples is 429.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 91.
number of samples per class in Ytest: [ 3  7  4  3  6  7  6 16 11  6  2  4  2  2 10  2]

Xtrain_transfer => (338, 64)
Xtest_transfer  => (338, 64)
Ytrain => (338, 16)
Ytest  => (91, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainable pa


Epoch 00058: val_categorical_accuracy did not improve from 0.64835

Epoch 00059: val_categorical_accuracy did not improve from 0.64835

Epoch 00060: val_categorical_accuracy did not improve from 0.64835

Epoch 00061: val_categorical_accuracy did not improve from 0.64835

Epoch 00062: val_categorical_accuracy did not improve from 0.64835

Epoch 00063: val_categorical_accuracy did not improve from 0.64835

Epoch 00064: val_categorical_accuracy did not improve from 0.64835

Epoch 00065: val_categorical_accuracy did not improve from 0.64835

Epoch 00066: val_categorical_accuracy did not improve from 0.64835

Epoch 00067: val_categorical_accuracy did not improve from 0.64835

Epoch 00068: val_categorical_accuracy did not improve from 0.64835

Epoch 00069: val_categorical_accuracy did not improve from 0.64835

Epoch 00070: val_categorical_accuracy did not improve from 0.64835

Epoch 00071: val_categorical_accuracy did not improve from 0.64835

Epoch 00072: val_categorical_accuracy did not i


Epoch 00172: val_categorical_accuracy did not improve from 0.71429

Epoch 00173: val_categorical_accuracy did not improve from 0.71429

Epoch 00174: val_categorical_accuracy did not improve from 0.71429

Epoch 00175: val_categorical_accuracy did not improve from 0.71429

Epoch 00176: val_categorical_accuracy did not improve from 0.71429

Epoch 00177: val_categorical_accuracy did not improve from 0.71429

Epoch 00178: val_categorical_accuracy did not improve from 0.71429

Epoch 00179: val_categorical_accuracy did not improve from 0.71429

Epoch 00180: val_categorical_accuracy did not improve from 0.71429

Epoch 00181: val_categorical_accuracy did not improve from 0.71429

Epoch 00182: val_categorical_accuracy did not improve from 0.71429

Epoch 00183: val_categorical_accuracy did not improve from 0.71429

Epoch 00184: val_categorical_accuracy did not improve from 0.71429

Epoch 00185: val_categorical_accuracy did not improve from 0.71429

Epoch 00186: val_categorical_accuracy did not i


Epoch 00297: val_categorical_accuracy did not improve from 0.71429

Epoch 00298: val_categorical_accuracy did not improve from 0.71429

Epoch 00299: val_categorical_accuracy did not improve from 0.71429

Epoch 00300: val_categorical_accuracy did not improve from 0.71429
91/91 [==============================] - 0s 0s/sample - loss: 0.8899 - categorical_accuracy: 0.6813
Test Accuracy = 0.6813187
91/91 [==============================] - 0s 3ms/sample

============ Confusion_matrix for data with source overlap ratio of 85 and target overlap ratio of  50 is as below ============

[[ 3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  4  0  0  0  0  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0  0  0  0  0  2]
 [ 0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0]
 [ 0  0  

(1121, 103, 24, 24, 1) (288, 103, 24, 24, 1) (1121,) (288,)
Total samples per class: [47, 104, 56, 50, 81, 109, 96, 287, 168, 83, 30, 52, 30, 30, 162, 24], Total number of samples is 1409.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 288.
number of samples per class in Ytest: [10 21 12 10 17 22 20 58 34 17  6 11  6  6 33  5]

Xtrain_transfer => (1121, 64)
Xtest_transfer  => (1121, 64)
Ytrain => (1121, 16)
Ytest  => (288, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_11 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20


Epoch 00045: val_categorical_accuracy did not improve from 0.64236

Epoch 00046: val_categorical_accuracy did not improve from 0.64236

Epoch 00047: val_categorical_accuracy improved from 0.64236 to 0.64931, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_85_percent.h5

Epoch 00048: val_categorical_accuracy did not improve from 0.64931

Epoch 00049: val_categorical_accuracy did not improve from 0.64931

Epoch 00050: val_categorical_accuracy did not improve from 0.64931

Epoch 00051: val_categorical_accuracy did not improve from 0.64931

Epoch 00052: val_categorical_accuracy did not improve from 0.64931

Epoch 00053: val_categorical_accuracy did not improve from 0.64931

Epoch 00054: val_categorical_accuracy improved from 0.64931 to 0.68056, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected


Epoch 00151: val_categorical_accuracy did not improve from 0.72569

Epoch 00152: val_categorical_accuracy did not improve from 0.72569

Epoch 00153: val_categorical_accuracy did not improve from 0.72569

Epoch 00154: val_categorical_accuracy did not improve from 0.72569

Epoch 00155: val_categorical_accuracy did not improve from 0.72569

Epoch 00156: val_categorical_accuracy did not improve from 0.72569

Epoch 00157: val_categorical_accuracy did not improve from 0.72569

Epoch 00158: val_categorical_accuracy did not improve from 0.72569

Epoch 00159: val_categorical_accuracy did not improve from 0.72569

Epoch 00160: val_categorical_accuracy did not improve from 0.72569

Epoch 00161: val_categorical_accuracy did not improve from 0.72569

Epoch 00162: val_categorical_accuracy did not improve from 0.72569

Epoch 00163: val_categorical_accuracy did not improve from 0.72569

Epoch 00164: val_categorical_accuracy did not improve from 0.72569

Epoch 00165: val_categorical_accuracy did not i


Epoch 00263: val_categorical_accuracy did not improve from 0.74653

Epoch 00264: val_categorical_accuracy did not improve from 0.74653

Epoch 00265: val_categorical_accuracy did not improve from 0.74653

Epoch 00266: val_categorical_accuracy did not improve from 0.74653

Epoch 00267: val_categorical_accuracy did not improve from 0.74653

Epoch 00268: val_categorical_accuracy did not improve from 0.74653

Epoch 00269: val_categorical_accuracy improved from 0.74653 to 0.75347, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_85_percent.h5

Epoch 00270: val_categorical_accuracy did not improve from 0.75347

Epoch 00271: val_categorical_accuracy did not improve from 0.75347

Epoch 00272: val_categorical_accuracy did not improve from 0.75347

Epoch 00273: val_categorical_accuracy did not improve from 0.75347

Epoch 00274: val_categorical_accuracy did 

(16239, 103, 24, 24, 1) (4068, 103, 24, 24, 1) (16239,) (4068,)
Total samples per class: [635, 1619, 663, 632, 1143, 1512, 1490, 4327, 2571, 1092, 357, 650, 306, 349, 2620, 341], Total number of samples is 20307.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 4068.
number of samples per class in Ytest: [127 324 133 127 229 303 298 866 515 219  72 130  62  70 524  69]

Xtrain_transfer => (16239, 64)
Xtest_transfer  => (16239, 64)
Ytrain => (16239, 16)
Ytest  => (4068, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_12 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 1


Epoch 00048: val_categorical_accuracy did not improve from 0.74164

Epoch 00049: val_categorical_accuracy did not improve from 0.74164

Epoch 00050: val_categorical_accuracy did not improve from 0.74164

Epoch 00051: val_categorical_accuracy did not improve from 0.74164

Epoch 00052: val_categorical_accuracy improved from 0.74164 to 0.74336, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_85_percent.h5

Epoch 00053: val_categorical_accuracy did not improve from 0.74336

Epoch 00054: val_categorical_accuracy did not improve from 0.74336

Epoch 00055: val_categorical_accuracy did not improve from 0.74336

Epoch 00056: val_categorical_accuracy did not improve from 0.74336

Epoch 00057: val_categorical_accuracy did not improve from 0.74336

Epoch 00058: val_categorical_accuracy improved from 0.74336 to 0.74508, saving model to ..\..\Trained Models\T


Epoch 00129: val_categorical_accuracy did not improve from 0.77507

Epoch 00130: val_categorical_accuracy did not improve from 0.77507

Epoch 00131: val_categorical_accuracy did not improve from 0.77507

Epoch 00132: val_categorical_accuracy did not improve from 0.77507

Epoch 00133: val_categorical_accuracy did not improve from 0.77507

Epoch 00134: val_categorical_accuracy did not improve from 0.77507

Epoch 00135: val_categorical_accuracy did not improve from 0.77507

Epoch 00136: val_categorical_accuracy did not improve from 0.77507

Epoch 00137: val_categorical_accuracy did not improve from 0.77507

Epoch 00138: val_categorical_accuracy did not improve from 0.77507

Epoch 00139: val_categorical_accuracy did not improve from 0.77507

Epoch 00140: val_categorical_accuracy did not improve from 0.77507

Epoch 00141: val_categorical_accuracy improved from 0.77507 to 0.77532, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Laye


Epoch 00232: val_categorical_accuracy did not improve from 0.79081

Epoch 00233: val_categorical_accuracy did not improve from 0.79081

Epoch 00234: val_categorical_accuracy did not improve from 0.79081

Epoch 00235: val_categorical_accuracy did not improve from 0.79081

Epoch 00236: val_categorical_accuracy did not improve from 0.79081

Epoch 00237: val_categorical_accuracy did not improve from 0.79081

Epoch 00238: val_categorical_accuracy did not improve from 0.79081

Epoch 00239: val_categorical_accuracy did not improve from 0.79081

Epoch 00240: val_categorical_accuracy did not improve from 0.79081

Epoch 00241: val_categorical_accuracy did not improve from 0.79081

Epoch 00242: val_categorical_accuracy did not improve from 0.79081

Epoch 00243: val_categorical_accuracy did not improve from 0.79081

Epoch 00244: val_categorical_accuracy improved from 0.79081 to 0.79449, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Laye

(174, 103, 24, 24, 1) (51, 103, 24, 24, 1) (174,) (51,)
Total samples per class: [9, 16, 8, 10, 17, 17, 15, 40, 23, 14, 6, 9, 7, 7, 23, 4], Total number of samples is 225.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 51.
number of samples per class in Ytest: [2 4 2 2 4 4 3 8 5 3 2 2 2 2 5 1]

Xtrain_transfer => (174, 64)
Xtest_transfer  => (174, 64)
Ytrain => (174, 16)
Ytest  => (51, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_13 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainable params: 20,752
Non-trai


Epoch 00064: val_categorical_accuracy did not improve from 0.66667

Epoch 00065: val_categorical_accuracy did not improve from 0.66667

Epoch 00066: val_categorical_accuracy did not improve from 0.66667

Epoch 00067: val_categorical_accuracy did not improve from 0.66667

Epoch 00068: val_categorical_accuracy did not improve from 0.66667

Epoch 00069: val_categorical_accuracy did not improve from 0.66667

Epoch 00070: val_categorical_accuracy did not improve from 0.66667

Epoch 00071: val_categorical_accuracy did not improve from 0.66667

Epoch 00072: val_categorical_accuracy did not improve from 0.66667

Epoch 00073: val_categorical_accuracy did not improve from 0.66667

Epoch 00074: val_categorical_accuracy did not improve from 0.66667

Epoch 00075: val_categorical_accuracy did not improve from 0.66667

Epoch 00076: val_categorical_accuracy did not improve from 0.66667

Epoch 00077: val_categorical_accuracy did not improve from 0.66667

Epoch 00078: val_categorical_accuracy did not i


Epoch 00181: val_categorical_accuracy did not improve from 0.72549

Epoch 00182: val_categorical_accuracy did not improve from 0.72549

Epoch 00183: val_categorical_accuracy did not improve from 0.72549

Epoch 00184: val_categorical_accuracy did not improve from 0.72549

Epoch 00185: val_categorical_accuracy did not improve from 0.72549

Epoch 00186: val_categorical_accuracy did not improve from 0.72549

Epoch 00187: val_categorical_accuracy did not improve from 0.72549

Epoch 00188: val_categorical_accuracy did not improve from 0.72549

Epoch 00189: val_categorical_accuracy did not improve from 0.72549

Epoch 00190: val_categorical_accuracy did not improve from 0.72549

Epoch 00191: val_categorical_accuracy did not improve from 0.72549

Epoch 00192: val_categorical_accuracy did not improve from 0.72549

Epoch 00193: val_categorical_accuracy did not improve from 0.72549

Epoch 00194: val_categorical_accuracy did not improve from 0.72549

Epoch 00195: val_categorical_accuracy did not i

51/51 [==============================] - 0s 0s/sample - loss: 0.8850 - categorical_accuracy: 0.7059
Test Accuracy = 0.7058824
51/51 [==============================] - 0s 6ms/sample

============ Confusion_matrix for data with source overlap ratio of 95 and target overlap ratio of  25 is as below ============

[[2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 3 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 8 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 5 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 5 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]]
[2 4 2 2 4 4 3 8 5 3 2 2 2 2 5 1]


= Source Model with overlap ratio of 95% will be transfered to Target Data with overlap rati

(338, 103, 24, 24, 1) (91, 103, 24, 24, 1) (338,) (91,)
Total samples per class: [15, 32, 17, 14, 26, 35, 30, 80, 51, 27, 10, 17, 9, 10, 47, 9], Total number of samples is 429.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 91.
number of samples per class in Ytest: [ 3  7  4  3  6  7  6 16 11  6  2  4  2  2 10  2]

Xtrain_transfer => (338, 64)
Xtest_transfer  => (338, 64)
Ytrain => (338, 16)
Ytest  => (91, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_14 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainable pa


Epoch 00066: val_categorical_accuracy improved from 0.57143 to 0.58242, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_50_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00067: val_categorical_accuracy did not improve from 0.58242

Epoch 00068: val_categorical_accuracy did not improve from 0.58242

Epoch 00069: val_categorical_accuracy did not improve from 0.58242

Epoch 00070: val_categorical_accuracy did not improve from 0.58242

Epoch 00071: val_categorical_accuracy did not improve from 0.58242

Epoch 00072: val_categorical_accuracy did not improve from 0.58242

Epoch 00073: val_categorical_accuracy did not improve from 0.58242

Epoch 00074: val_categorical_accuracy did not improve from 0.58242

Epoch 00075: val_categorical_accuracy did not improve from 0.58242

Epoch 00076: val_categorical_accuracy did not improve from 0.58242

Epoch 00077: val_categorical_accuracy impr

Epoch 00176: val_categorical_accuracy did not improve from 0.63736

Epoch 00177: val_categorical_accuracy did not improve from 0.63736

Epoch 00178: val_categorical_accuracy did not improve from 0.63736

Epoch 00179: val_categorical_accuracy did not improve from 0.63736

Epoch 00180: val_categorical_accuracy did not improve from 0.63736

Epoch 00181: val_categorical_accuracy did not improve from 0.63736

Epoch 00182: val_categorical_accuracy did not improve from 0.63736

Epoch 00183: val_categorical_accuracy did not improve from 0.63736

Epoch 00184: val_categorical_accuracy did not improve from 0.63736

Epoch 00185: val_categorical_accuracy did not improve from 0.63736

Epoch 00186: val_categorical_accuracy did not improve from 0.63736

Epoch 00187: val_categorical_accuracy did not improve from 0.63736

Epoch 00188: val_categorical_accuracy did not improve from 0.63736

Epoch 00189: val_categorical_accuracy did not improve from 0.63736

Epoch 00190: val_categorical_accuracy did not im


Epoch 00295: val_categorical_accuracy did not improve from 0.65934

Epoch 00296: val_categorical_accuracy did not improve from 0.65934

Epoch 00297: val_categorical_accuracy did not improve from 0.65934

Epoch 00298: val_categorical_accuracy did not improve from 0.65934

Epoch 00299: val_categorical_accuracy did not improve from 0.65934

Epoch 00300: val_categorical_accuracy did not improve from 0.65934
91/91 [==============================] - 0s 66us/sample - loss: 0.9242 - categorical_accuracy: 0.6484
Test Accuracy = 0.64835167
91/91 [==============================] - 0s 3ms/sample

============ Confusion_matrix for data with source overlap ratio of 95 and target overlap ratio of  50 is as below ============

[[ 3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  4  0  0  0  0  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  4  0  0  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  7  0 

(1121, 103, 24, 24, 1) (288, 103, 24, 24, 1) (1121,) (288,)
Total samples per class: [47, 104, 56, 50, 81, 109, 96, 287, 168, 83, 30, 52, 30, 30, 162, 24], Total number of samples is 1409.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 288.
number of samples per class in Ytest: [10 21 12 10 17 22 20 58 34 17  6 11  6  6 33  5]

Xtrain_transfer => (1121, 64)
Xtest_transfer  => (1121, 64)
Ytrain => (1121, 16)
Ytest  => (288, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_15 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20


Epoch 00049: val_categorical_accuracy did not improve from 0.57639

Epoch 00050: val_categorical_accuracy did not improve from 0.57639

Epoch 00051: val_categorical_accuracy did not improve from 0.57639

Epoch 00052: val_categorical_accuracy improved from 0.57639 to 0.58333, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00053: val_categorical_accuracy did not improve from 0.58333

Epoch 00054: val_categorical_accuracy did not improve from 0.58333

Epoch 00055: val_categorical_accuracy improved from 0.58333 to 0.60069, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00056: val_categorical_accuracy did not improve from 0.60069

Epoch 00057: val_categorical_accuracy


Epoch 00142: val_categorical_accuracy did not improve from 0.66319

Epoch 00143: val_categorical_accuracy did not improve from 0.66319

Epoch 00144: val_categorical_accuracy did not improve from 0.66319

Epoch 00145: val_categorical_accuracy did not improve from 0.66319

Epoch 00146: val_categorical_accuracy did not improve from 0.66319

Epoch 00147: val_categorical_accuracy did not improve from 0.66319

Epoch 00148: val_categorical_accuracy improved from 0.66319 to 0.66667, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00149: val_categorical_accuracy did not improve from 0.66667

Epoch 00150: val_categorical_accuracy did not improve from 0.66667

Epoch 00151: val_categorical_accuracy did not improve from 0.66667

Epoch 00152: val_categorical_accuracy did not improve from 0.66667

Epoch 00153: val_categorical_accuracy did 


Epoch 00254: val_categorical_accuracy did not improve from 0.69444

Epoch 00255: val_categorical_accuracy did not improve from 0.69444

Epoch 00256: val_categorical_accuracy did not improve from 0.69444

Epoch 00257: val_categorical_accuracy did not improve from 0.69444

Epoch 00258: val_categorical_accuracy did not improve from 0.69444

Epoch 00259: val_categorical_accuracy did not improve from 0.69444

Epoch 00260: val_categorical_accuracy did not improve from 0.69444

Epoch 00261: val_categorical_accuracy did not improve from 0.69444

Epoch 00262: val_categorical_accuracy did not improve from 0.69444

Epoch 00263: val_categorical_accuracy did not improve from 0.69444

Epoch 00264: val_categorical_accuracy did not improve from 0.69444

Epoch 00265: val_categorical_accuracy did not improve from 0.69444

Epoch 00266: val_categorical_accuracy did not improve from 0.69444

Epoch 00267: val_categorical_accuracy did not improve from 0.69444

Epoch 00268: val_categorical_accuracy did not i

(16239, 103, 24, 24, 1) (4068, 103, 24, 24, 1) (16239,) (4068,)
Total samples per class: [635, 1619, 663, 632, 1143, 1512, 1490, 4327, 2571, 1092, 357, 650, 306, 349, 2620, 341], Total number of samples is 20307.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 4068.
number of samples per class in Ytest: [127 324 133 127 229 303 298 866 515 219  72 130  62  70 524  69]

Xtrain_transfer => (16239, 64)
Xtest_transfer  => (16239, 64)
Ytrain => (16239, 16)
Ytest  => (4068, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_16 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 1


Epoch 00032: val_categorical_accuracy improved from 0.67134 to 0.67207, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00033: val_categorical_accuracy did not improve from 0.67207

Epoch 00034: val_categorical_accuracy did not improve from 0.67207

Epoch 00035: val_categorical_accuracy improved from 0.67207 to 0.67429, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00036: val_categorical_accuracy improved from 0.67429 to 0.67453, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00037: val_categorical_acc


Epoch 00104: val_categorical_accuracy did not improve from 0.73673

Epoch 00105: val_categorical_accuracy did not improve from 0.73673

Epoch 00106: val_categorical_accuracy did not improve from 0.73673

Epoch 00107: val_categorical_accuracy improved from 0.73673 to 0.73820, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00108: val_categorical_accuracy did not improve from 0.73820

Epoch 00109: val_categorical_accuracy improved from 0.73820 to 0.74041, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Salinas\Fully_Connected_Layers_for_Salinas_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00110: val_categorical_accuracy did not improve from 0.74041

Epoch 00111: val_categorical_accuracy did not improve from 0.74041

Epoch 00112: val_categorical_accuracy


Epoch 00203: val_categorical_accuracy did not improve from 0.77827

Epoch 00204: val_categorical_accuracy did not improve from 0.77827

Epoch 00205: val_categorical_accuracy did not improve from 0.77827

Epoch 00206: val_categorical_accuracy did not improve from 0.77827

Epoch 00207: val_categorical_accuracy did not improve from 0.77827

Epoch 00208: val_categorical_accuracy did not improve from 0.77827

Epoch 00209: val_categorical_accuracy did not improve from 0.77827

Epoch 00210: val_categorical_accuracy did not improve from 0.77827

Epoch 00211: val_categorical_accuracy did not improve from 0.77827

Epoch 00212: val_categorical_accuracy did not improve from 0.77827

Epoch 00213: val_categorical_accuracy did not improve from 0.77827

Epoch 00214: val_categorical_accuracy did not improve from 0.77827

Epoch 00215: val_categorical_accuracy did not improve from 0.77827

Epoch 00216: val_categorical_accuracy did not improve from 0.77827

Epoch 00217: val_categorical_accuracy did not i

In [5]:
Acc_Tbl

0           1           2           3           4
0    Test Accuracy  Salinas_25  Salinas_50  Salinas_75  Salinas_95
1  Indian_Pines_50      72.549     69.2308     72.2222     82.5221
2  Indian_Pines_75     68.6275     68.1319     76.0417     85.3491
3  Indian_Pines_85      72.549     68.1319     73.6111      78.884
4  Indian_Pines_95     70.5882     64.8352       68.75     77.8515