In [1]:
from Transfer_Model_Utils import *
import scipy.io as sio

In [2]:
uIndian_pines = sio.loadmat('..\\..\\Indian Pines\\Indian_pines_corrected.mat')
gt_uIndian_pines = sio.loadmat('..\\..\\Indian Pines\\Indian_pines_gt.mat')
data_IN = uIndian_pines['indian_pines_corrected']
gt_IN = gt_uIndian_pines['indian_pines_gt']
print(data_IN.shape, gt_IN.shape)
data_IN = np.moveaxis(data_IN, 2, 0)
print(data_IN.shape, gt_IN.shape)

(145, 145, 200) (145, 145)
(200, 145, 145) (145, 145)


In [3]:
values,counts = np.unique(gt_IN, return_counts=True)
print(values,counts)
range_of_class = list(values)
if 0 in range_of_class:
    range_of_class.pop(0)
range_of_class

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16] [10776    46  1428   830   237   483   730    28   478    20   972  2455
   593   205  1265   386    93]


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

In [4]:
Acc_Tbl = Transfer(overlap_ratio_List_for_Target = [50, 75, 85, 95],
                   overlap_ratio_List_for_Source = [25, 50, 75, 95], 
                   epochs_list = [300, 300, 300, 300],
                   batch_size_list = [16, 32, 64, 128],
                   range_of_class = range_of_class,
                   Cube_size = 25,
                   Data = data_IN,
                   Gt = gt_IN,
                   Train_Test_split = 80,
                   channel = 103,
                   Source_data_name = 'Pavia', 
                   Target_data_name = 'Indian_Pines',
                   Verbosity = 0)

               0                1                2                3  \
0  Test Accuracy  Indian_Pines_50  Indian_Pines_75  Indian_Pines_85   
1       Pavia_25             None             None             None   
2       Pavia_50             None             None             None   
3       Pavia_75             None             None             None   
4       Pavia_95             None             None             None   

                 4  
0  Indian_Pines_95  
1             None  
2             None  
3             None  
4             None  


= Source Model with overlap ratio of 25% will be transfered to Target Data with overlap ratio of 50%, Source Model shown below =


Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 103, 24, 24, 0                                            
__

(75, 103, 24, 24, 1) (22, 103, 24, 24, 1) (75,) (22,)
Total samples per class: [0, 15, 8, 0, 7, 10, 0, 4, 0, 12, 24, 5, 0, 12, 0, 0], Total number of samples is 97.

unique classes in Ytest: [ 2  3  5  6  8 10 11 12 14], Total number of samples in Ytest is 22.
number of samples per class in Ytest: [3 2 2 2 1 3 5 1 3]

Xtrain_transfer => (75, 64)
Xtest_transfer  => (75, 64)
Ytrain => (75, 9)
Ytest  => (22, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
_______________________________


Epoch 00096: val_categorical_accuracy did not improve from 0.50000

Epoch 00097: val_categorical_accuracy did not improve from 0.50000

Epoch 00098: val_categorical_accuracy did not improve from 0.50000

Epoch 00099: val_categorical_accuracy did not improve from 0.50000

Epoch 00100: val_categorical_accuracy did not improve from 0.50000

Epoch 00101: val_categorical_accuracy did not improve from 0.50000

Epoch 00102: val_categorical_accuracy did not improve from 0.50000

Epoch 00103: val_categorical_accuracy did not improve from 0.50000

Epoch 00104: val_categorical_accuracy did not improve from 0.50000

Epoch 00105: val_categorical_accuracy did not improve from 0.50000

Epoch 00106: val_categorical_accuracy did not improve from 0.50000

Epoch 00107: val_categorical_accuracy did not improve from 0.50000

Epoch 00108: val_categorical_accuracy did not improve from 0.50000

Epoch 00109: val_categorical_accuracy did not improve from 0.50000

Epoch 00110: val_categorical_accuracy did not i


Epoch 00218: val_categorical_accuracy did not improve from 0.50000

Epoch 00219: val_categorical_accuracy did not improve from 0.50000

Epoch 00220: val_categorical_accuracy did not improve from 0.50000

Epoch 00221: val_categorical_accuracy did not improve from 0.50000

Epoch 00222: val_categorical_accuracy did not improve from 0.50000

Epoch 00223: val_categorical_accuracy did not improve from 0.50000

Epoch 00224: val_categorical_accuracy did not improve from 0.50000

Epoch 00225: val_categorical_accuracy did not improve from 0.50000

Epoch 00226: val_categorical_accuracy did not improve from 0.50000

Epoch 00227: val_categorical_accuracy did not improve from 0.50000

Epoch 00228: val_categorical_accuracy did not improve from 0.50000

Epoch 00229: val_categorical_accuracy did not improve from 0.50000

Epoch 00230: val_categorical_accuracy did not improve from 0.50000

Epoch 00231: val_categorical_accuracy did not improve from 0.50000

Epoch 00232: val_categorical_accuracy did not i

(224, 103, 24, 24, 1) (61, 103, 24, 24, 1) (224,) (61,)
Total samples per class: [0, 49, 14, 5, 13, 26, 0, 10, 0, 30, 71, 17, 9, 31, 5, 5], Total number of samples is 285.

unique classes in Ytest: [ 2  3  4  5  6  8 10 11 12 13 14 15 16], Total number of samples in Ytest is 61.
number of samples per class in Ytest: [10  3  1  3  6  2  6 15  4  2  7  1  1]

Xtrain_transfer => (224, 64)
Xtest_transfer  => (224, 64)
Ytrain => (224, 13)
Ytest  => (61, 13)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc13 (Dense)                 (None, 13)                3341      
Total params: 19,981
Trainable params: 19,981
Non-traina


Epoch 00088: val_categorical_accuracy did not improve from 0.42623

Epoch 00089: val_categorical_accuracy did not improve from 0.42623

Epoch 00090: val_categorical_accuracy did not improve from 0.42623

Epoch 00091: val_categorical_accuracy did not improve from 0.42623

Epoch 00092: val_categorical_accuracy did not improve from 0.42623

Epoch 00093: val_categorical_accuracy did not improve from 0.42623

Epoch 00094: val_categorical_accuracy did not improve from 0.42623

Epoch 00095: val_categorical_accuracy did not improve from 0.42623

Epoch 00096: val_categorical_accuracy did not improve from 0.42623

Epoch 00097: val_categorical_accuracy did not improve from 0.42623

Epoch 00098: val_categorical_accuracy did not improve from 0.42623

Epoch 00099: val_categorical_accuracy did not improve from 0.42623

Epoch 00100: val_categorical_accuracy did not improve from 0.42623

Epoch 00101: val_categorical_accuracy did not improve from 0.42623

Epoch 00102: val_categorical_accuracy did not i

Epoch 00214: val_categorical_accuracy did not improve from 0.44262

Epoch 00215: val_categorical_accuracy did not improve from 0.44262

Epoch 00216: val_categorical_accuracy did not improve from 0.44262

Epoch 00217: val_categorical_accuracy did not improve from 0.44262

Epoch 00218: val_categorical_accuracy did not improve from 0.44262

Epoch 00219: val_categorical_accuracy did not improve from 0.44262

Epoch 00220: val_categorical_accuracy did not improve from 0.44262

Epoch 00221: val_categorical_accuracy did not improve from 0.44262

Epoch 00222: val_categorical_accuracy did not improve from 0.44262

Epoch 00223: val_categorical_accuracy did not improve from 0.44262

Epoch 00224: val_categorical_accuracy did not improve from 0.44262

Epoch 00225: val_categorical_accuracy did not improve from 0.44262

Epoch 00226: val_categorical_accuracy did not improve from 0.44262

Epoch 00227: val_categorical_accuracy did not improve from 0.44262

Epoch 00228: val_categorical_accuracy did not im

(639, 103, 24, 24, 1) (169, 103, 24, 24, 1) (639,) (169,)
Total samples per class: [6, 135, 36, 11, 33, 77, 4, 29, 4, 83, 216, 43, 21, 89, 11, 10], Total number of samples is 808.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 169.
number of samples per class in Ytest: [ 2 27  8  3  7 16  1  6  1 17 44  9  5 18  3  2]

Xtrain_transfer => (639, 64)
Xtest_transfer  => (639, 64)
Ytrain => (639, 16)
Ytest  => (169, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainab


Epoch 00066: val_categorical_accuracy did not improve from 0.42012

Epoch 00067: val_categorical_accuracy did not improve from 0.42012

Epoch 00068: val_categorical_accuracy did not improve from 0.42012

Epoch 00069: val_categorical_accuracy did not improve from 0.42012

Epoch 00070: val_categorical_accuracy did not improve from 0.42012

Epoch 00071: val_categorical_accuracy did not improve from 0.42012

Epoch 00072: val_categorical_accuracy did not improve from 0.42012

Epoch 00073: val_categorical_accuracy did not improve from 0.42012

Epoch 00074: val_categorical_accuracy did not improve from 0.42012

Epoch 00075: val_categorical_accuracy did not improve from 0.42012

Epoch 00076: val_categorical_accuracy did not improve from 0.42012

Epoch 00077: val_categorical_accuracy did not improve from 0.42012

Epoch 00078: val_categorical_accuracy did not improve from 0.42012

Epoch 00079: val_categorical_accuracy did not improve from 0.42012

Epoch 00080: val_categorical_accuracy did not i


Epoch 00178: val_categorical_accuracy did not improve from 0.46154

Epoch 00179: val_categorical_accuracy did not improve from 0.46154

Epoch 00180: val_categorical_accuracy did not improve from 0.46154

Epoch 00181: val_categorical_accuracy did not improve from 0.46154

Epoch 00182: val_categorical_accuracy did not improve from 0.46154

Epoch 00183: val_categorical_accuracy did not improve from 0.46154

Epoch 00184: val_categorical_accuracy did not improve from 0.46154

Epoch 00185: val_categorical_accuracy did not improve from 0.46154

Epoch 00186: val_categorical_accuracy did not improve from 0.46154

Epoch 00187: val_categorical_accuracy did not improve from 0.46154

Epoch 00188: val_categorical_accuracy did not improve from 0.46154

Epoch 00189: val_categorical_accuracy did not improve from 0.46154

Epoch 00190: val_categorical_accuracy did not improve from 0.46154

Epoch 00191: val_categorical_accuracy did not improve from 0.46154

Epoch 00192: val_categorical_accuracy did not i


Epoch 00298: val_categorical_accuracy did not improve from 0.46746

Epoch 00299: val_categorical_accuracy did not improve from 0.46746

Epoch 00300: val_categorical_accuracy did not improve from 0.46746
169/169 [==============================] - 0s 141us/sample - loss: 1.8459 - categorical_accuracy: 0.4142
Test Accuracy = 0.41420117
169/169 [==============================] - 0s 446us/sample

============ Confusion_matrix for data with source overlap ratio of 25 and target overlap ratio of  85 is as below ============

[[ 0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0 10  0  0  0  0  7  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  4  3  0  0  0  0  0]
 [ 0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  6  0  0  0  0  0]
 [ 0  3  0  0  0  3  0  0  0  0  2  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  2  0  0  0  0  4  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  1  0  0  0

(3109, 103, 24, 24, 1) (785, 103, 24, 24, 1) (3109,) (785,)
Total samples per class: [24, 668, 177, 45, 137, 365, 14, 141, 10, 408, 1067, 181, 101, 465, 46, 45], Total number of samples is 3894.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 785.
number of samples per class in Ytest: [  5 134  36   9  28  73   3  29   2  82 214  37  21  93  10   9]

Xtrain_transfer => (3109, 64)
Xtest_transfer  => (3109, 64)
Ytrain => (3109, 16)
Ytest  => (785, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112 


Epoch 00045: val_categorical_accuracy did not improve from 0.50573

Epoch 00046: val_categorical_accuracy did not improve from 0.50573

Epoch 00047: val_categorical_accuracy improved from 0.50573 to 0.50828, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_95_With_source_data_as_Pavia_overlap_ratio_25_percent.h5

Epoch 00048: val_categorical_accuracy did not improve from 0.50828

Epoch 00049: val_categorical_accuracy did not improve from 0.50828

Epoch 00050: val_categorical_accuracy did not improve from 0.50828

Epoch 00051: val_categorical_accuracy did not improve from 0.50828

Epoch 00052: val_categorical_accuracy did not improve from 0.50828

Epoch 00053: val_categorical_accuracy did not improve from 0.50828

Epoch 00054: val_categorical_accuracy did not improve from 0.50828

Epoch 00055: val_categorical_accuracy did not improve from 0.50828

Epoch 00056: val_categorical_accuracy d


Epoch 00160: val_categorical_accuracy did not improve from 0.51465

Epoch 00161: val_categorical_accuracy did not improve from 0.51465

Epoch 00162: val_categorical_accuracy did not improve from 0.51465

Epoch 00163: val_categorical_accuracy did not improve from 0.51465

Epoch 00164: val_categorical_accuracy did not improve from 0.51465

Epoch 00165: val_categorical_accuracy did not improve from 0.51465

Epoch 00166: val_categorical_accuracy did not improve from 0.51465

Epoch 00167: val_categorical_accuracy did not improve from 0.51465

Epoch 00168: val_categorical_accuracy did not improve from 0.51465

Epoch 00169: val_categorical_accuracy did not improve from 0.51465

Epoch 00170: val_categorical_accuracy did not improve from 0.51465

Epoch 00171: val_categorical_accuracy did not improve from 0.51465

Epoch 00172: val_categorical_accuracy did not improve from 0.51465

Epoch 00173: val_categorical_accuracy did not improve from 0.51465

Epoch 00174: val_categorical_accuracy did not i

(75, 103, 24, 24, 1) (22, 103, 24, 24, 1) (75,) (22,)
Total samples per class: [0, 15, 8, 0, 7, 10, 0, 4, 0, 12, 24, 5, 0, 12, 0, 0], Total number of samples is 97.

unique classes in Ytest: [ 2  3  5  6  8 10 11 12 14], Total number of samples in Ytest is 22.
number of samples per class in Ytest: [3 2 2 2 1 3 5 1 3]

Xtrain_transfer => (75, 64)
Xtest_transfer  => (75, 64)
Ytrain => (75, 9)
Ytest  => (22, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
_______________________________


Epoch 00093: val_categorical_accuracy did not improve from 0.45455

Epoch 00094: val_categorical_accuracy did not improve from 0.45455

Epoch 00095: val_categorical_accuracy did not improve from 0.45455

Epoch 00096: val_categorical_accuracy did not improve from 0.45455

Epoch 00097: val_categorical_accuracy did not improve from 0.45455

Epoch 00098: val_categorical_accuracy did not improve from 0.45455

Epoch 00099: val_categorical_accuracy did not improve from 0.45455

Epoch 00100: val_categorical_accuracy did not improve from 0.45455

Epoch 00101: val_categorical_accuracy did not improve from 0.45455

Epoch 00102: val_categorical_accuracy did not improve from 0.45455

Epoch 00103: val_categorical_accuracy did not improve from 0.45455

Epoch 00104: val_categorical_accuracy did not improve from 0.45455

Epoch 00105: val_categorical_accuracy did not improve from 0.45455

Epoch 00106: val_categorical_accuracy did not improve from 0.45455

Epoch 00107: val_categorical_accuracy did not i


Epoch 00220: val_categorical_accuracy did not improve from 0.45455

Epoch 00221: val_categorical_accuracy did not improve from 0.45455

Epoch 00222: val_categorical_accuracy did not improve from 0.45455

Epoch 00223: val_categorical_accuracy did not improve from 0.45455

Epoch 00224: val_categorical_accuracy did not improve from 0.45455

Epoch 00225: val_categorical_accuracy did not improve from 0.45455

Epoch 00226: val_categorical_accuracy did not improve from 0.45455

Epoch 00227: val_categorical_accuracy did not improve from 0.45455

Epoch 00228: val_categorical_accuracy did not improve from 0.45455

Epoch 00229: val_categorical_accuracy did not improve from 0.45455

Epoch 00230: val_categorical_accuracy did not improve from 0.45455

Epoch 00231: val_categorical_accuracy did not improve from 0.45455

Epoch 00232: val_categorical_accuracy did not improve from 0.45455

Epoch 00233: val_categorical_accuracy did not improve from 0.45455

Epoch 00234: val_categorical_accuracy did not i

(224, 103, 24, 24, 1) (61, 103, 24, 24, 1) (224,) (61,)
Total samples per class: [0, 49, 14, 5, 13, 26, 0, 10, 0, 30, 71, 17, 9, 31, 5, 5], Total number of samples is 285.

unique classes in Ytest: [ 2  3  4  5  6  8 10 11 12 13 14 15 16], Total number of samples in Ytest is 61.
number of samples per class in Ytest: [10  3  1  3  6  2  6 15  4  2  7  1  1]

Xtrain_transfer => (224, 64)
Xtest_transfer  => (224, 64)
Ytrain => (224, 13)
Ytest  => (61, 13)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc13 (Dense)                 (None, 13)                3341      
Total params: 19,981
Trainable params: 19,981
Non-traina


Epoch 00077: val_categorical_accuracy did not improve from 0.39344

Epoch 00078: val_categorical_accuracy did not improve from 0.39344

Epoch 00079: val_categorical_accuracy did not improve from 0.39344

Epoch 00080: val_categorical_accuracy did not improve from 0.39344

Epoch 00081: val_categorical_accuracy did not improve from 0.39344

Epoch 00082: val_categorical_accuracy did not improve from 0.39344

Epoch 00083: val_categorical_accuracy did not improve from 0.39344

Epoch 00084: val_categorical_accuracy did not improve from 0.39344

Epoch 00085: val_categorical_accuracy did not improve from 0.39344

Epoch 00086: val_categorical_accuracy did not improve from 0.39344

Epoch 00087: val_categorical_accuracy did not improve from 0.39344

Epoch 00088: val_categorical_accuracy did not improve from 0.39344

Epoch 00089: val_categorical_accuracy did not improve from 0.39344

Epoch 00090: val_categorical_accuracy did not improve from 0.39344

Epoch 00091: val_categorical_accuracy did not i

Epoch 00186: val_categorical_accuracy did not improve from 0.47541

Epoch 00187: val_categorical_accuracy did not improve from 0.47541

Epoch 00188: val_categorical_accuracy did not improve from 0.47541

Epoch 00189: val_categorical_accuracy did not improve from 0.47541

Epoch 00190: val_categorical_accuracy did not improve from 0.47541

Epoch 00191: val_categorical_accuracy did not improve from 0.47541

Epoch 00192: val_categorical_accuracy did not improve from 0.47541

Epoch 00193: val_categorical_accuracy did not improve from 0.47541

Epoch 00194: val_categorical_accuracy did not improve from 0.47541

Epoch 00195: val_categorical_accuracy did not improve from 0.47541

Epoch 00196: val_categorical_accuracy did not improve from 0.47541

Epoch 00197: val_categorical_accuracy did not improve from 0.47541

Epoch 00198: val_categorical_accuracy did not improve from 0.47541

Epoch 00199: val_categorical_accuracy did not improve from 0.47541

Epoch 00200: val_categorical_accuracy did not im

61/61 [==============================] - 0s 67us/sample - loss: 1.7050 - categorical_accuracy: 0.4426
Test Accuracy = 0.44262296
61/61 [==============================] - 0s 2ms/sample

============ Confusion_matrix for data with source overlap ratio of 50 and target overlap ratio of  75 is as below ============

[[7 0 0 0 1 0 0 2 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 3 0 0 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 1 0 0 0 0 0]
 [2 0 0 0 0 0 1 3 0 0 0 0 0]
 [2 0 0 0 2 2 0 9 0 0 0 0 0]
 [2 0 0 0 1 0 0 1 0 0 0 0 0]
 [2 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0 5 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0]]
[10  3  1  3  6  2  6 15  4  2  7  1  1]


= Source Model with overlap ratio of 50% will be transfered to Target Data with overlap ratio of 85%, Source Model shown below =


Model: "model_1"
__________________________________________________________________________________________________
Layer (type)      

(639, 103, 24, 24, 1) (169, 103, 24, 24, 1) (639,) (169,)
Total samples per class: [6, 135, 36, 11, 33, 77, 4, 29, 4, 83, 216, 43, 21, 89, 11, 10], Total number of samples is 808.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 169.
number of samples per class in Ytest: [ 2 27  8  3  7 16  1  6  1 17 44  9  5 18  3  2]

Xtrain_transfer => (639, 64)
Xtest_transfer  => (639, 64)
Ytrain => (639, 16)
Ytest  => (169, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainab


Epoch 00072: val_categorical_accuracy did not improve from 0.43195

Epoch 00073: val_categorical_accuracy did not improve from 0.43195

Epoch 00074: val_categorical_accuracy did not improve from 0.43195

Epoch 00075: val_categorical_accuracy did not improve from 0.43195

Epoch 00076: val_categorical_accuracy did not improve from 0.43195

Epoch 00077: val_categorical_accuracy did not improve from 0.43195

Epoch 00078: val_categorical_accuracy did not improve from 0.43195

Epoch 00079: val_categorical_accuracy did not improve from 0.43195

Epoch 00080: val_categorical_accuracy did not improve from 0.43195

Epoch 00081: val_categorical_accuracy did not improve from 0.43195

Epoch 00082: val_categorical_accuracy did not improve from 0.43195

Epoch 00083: val_categorical_accuracy did not improve from 0.43195

Epoch 00084: val_categorical_accuracy improved from 0.43195 to 0.43787, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected


Epoch 00193: val_categorical_accuracy did not improve from 0.43787

Epoch 00194: val_categorical_accuracy did not improve from 0.43787

Epoch 00195: val_categorical_accuracy did not improve from 0.43787

Epoch 00196: val_categorical_accuracy did not improve from 0.43787

Epoch 00197: val_categorical_accuracy did not improve from 0.43787

Epoch 00198: val_categorical_accuracy did not improve from 0.43787

Epoch 00199: val_categorical_accuracy did not improve from 0.43787

Epoch 00200: val_categorical_accuracy did not improve from 0.43787

Epoch 00201: val_categorical_accuracy did not improve from 0.43787

Epoch 00202: val_categorical_accuracy did not improve from 0.43787

Epoch 00203: val_categorical_accuracy did not improve from 0.43787

Epoch 00204: val_categorical_accuracy did not improve from 0.43787

Epoch 00205: val_categorical_accuracy did not improve from 0.43787

Epoch 00206: val_categorical_accuracy did not improve from 0.43787

Epoch 00207: val_categorical_accuracy improved 



= Source Model with overlap ratio of 50% will be transfered to Target Data with overlap ratio of 95%, Source Model shown below =


Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_2[0][0]                    
__________________________________________________________________________________________________
bn_conv_0 (BatchNormalization)  (None, 48, 11, 11, 3 128         conv_0[0][0]                     
__________________________________________________________________________________________________
activation_1 (Activation)       (None, 48, 11, 11, 3 0    

(3109, 103, 24, 24, 1) (785, 103, 24, 24, 1) (3109,) (785,)
Total samples per class: [24, 668, 177, 45, 137, 365, 14, 141, 10, 408, 1067, 181, 101, 465, 46, 45], Total number of samples is 3894.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 785.
number of samples per class in Ytest: [  5 134  36   9  28  73   3  29   2  82 214  37  21  93  10   9]

Xtrain_transfer => (3109, 64)
Xtest_transfer  => (3109, 64)
Ytrain => (3109, 16)
Ytest  => (785, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112 


Epoch 00059: val_categorical_accuracy did not improve from 0.50573

Epoch 00060: val_categorical_accuracy did not improve from 0.50573

Epoch 00061: val_categorical_accuracy did not improve from 0.50573

Epoch 00062: val_categorical_accuracy did not improve from 0.50573

Epoch 00063: val_categorical_accuracy did not improve from 0.50573

Epoch 00064: val_categorical_accuracy did not improve from 0.50573

Epoch 00065: val_categorical_accuracy did not improve from 0.50573

Epoch 00066: val_categorical_accuracy did not improve from 0.50573

Epoch 00067: val_categorical_accuracy did not improve from 0.50573

Epoch 00068: val_categorical_accuracy did not improve from 0.50573

Epoch 00069: val_categorical_accuracy did not improve from 0.50573

Epoch 00070: val_categorical_accuracy did not improve from 0.50573

Epoch 00071: val_categorical_accuracy did not improve from 0.50573

Epoch 00072: val_categorical_accuracy did not improve from 0.50573

Epoch 00073: val_categorical_accuracy did not i


Epoch 00173: val_categorical_accuracy did not improve from 0.51720

Epoch 00174: val_categorical_accuracy did not improve from 0.51720

Epoch 00175: val_categorical_accuracy did not improve from 0.51720

Epoch 00176: val_categorical_accuracy did not improve from 0.51720

Epoch 00177: val_categorical_accuracy did not improve from 0.51720

Epoch 00178: val_categorical_accuracy did not improve from 0.51720

Epoch 00179: val_categorical_accuracy did not improve from 0.51720

Epoch 00180: val_categorical_accuracy did not improve from 0.51720

Epoch 00181: val_categorical_accuracy did not improve from 0.51720

Epoch 00182: val_categorical_accuracy did not improve from 0.51720

Epoch 00183: val_categorical_accuracy did not improve from 0.51720

Epoch 00184: val_categorical_accuracy did not improve from 0.51720

Epoch 00185: val_categorical_accuracy did not improve from 0.51720

Epoch 00186: val_categorical_accuracy did not improve from 0.51720

Epoch 00187: val_categorical_accuracy did not i


Epoch 00288: val_categorical_accuracy did not improve from 0.52611

Epoch 00289: val_categorical_accuracy did not improve from 0.52611

Epoch 00290: val_categorical_accuracy did not improve from 0.52611

Epoch 00291: val_categorical_accuracy did not improve from 0.52611

Epoch 00292: val_categorical_accuracy did not improve from 0.52611

Epoch 00293: val_categorical_accuracy did not improve from 0.52611

Epoch 00294: val_categorical_accuracy did not improve from 0.52611

Epoch 00295: val_categorical_accuracy did not improve from 0.52611

Epoch 00296: val_categorical_accuracy did not improve from 0.52611

Epoch 00297: val_categorical_accuracy did not improve from 0.52611

Epoch 00298: val_categorical_accuracy did not improve from 0.52611

Epoch 00299: val_categorical_accuracy did not improve from 0.52611

Epoch 00300: val_categorical_accuracy did not improve from 0.52611
785/785 [==============================] - 0s 59us/sample - loss: 1.4477 - categorical_accuracy: 0.5146
Test Accurac

(75, 103, 24, 24, 1) (22, 103, 24, 24, 1) (75,) (22,)
Total samples per class: [0, 15, 8, 0, 7, 10, 0, 4, 0, 12, 24, 5, 0, 12, 0, 0], Total number of samples is 97.

unique classes in Ytest: [ 2  3  5  6  8 10 11 12 14], Total number of samples in Ytest is 22.
number of samples per class in Ytest: [3 2 2 2 1 3 5 1 3]

Xtrain_transfer => (75, 64)
Xtest_transfer  => (75, 64)
Ytrain => (75, 9)
Ytest  => (22, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
_______________________________


Epoch 00098: val_categorical_accuracy did not improve from 0.50000

Epoch 00099: val_categorical_accuracy did not improve from 0.50000

Epoch 00100: val_categorical_accuracy did not improve from 0.50000

Epoch 00101: val_categorical_accuracy did not improve from 0.50000

Epoch 00102: val_categorical_accuracy did not improve from 0.50000

Epoch 00103: val_categorical_accuracy did not improve from 0.50000

Epoch 00104: val_categorical_accuracy did not improve from 0.50000

Epoch 00105: val_categorical_accuracy did not improve from 0.50000

Epoch 00106: val_categorical_accuracy did not improve from 0.50000

Epoch 00107: val_categorical_accuracy did not improve from 0.50000

Epoch 00108: val_categorical_accuracy did not improve from 0.50000

Epoch 00109: val_categorical_accuracy did not improve from 0.50000

Epoch 00110: val_categorical_accuracy did not improve from 0.50000

Epoch 00111: val_categorical_accuracy did not improve from 0.50000

Epoch 00112: val_categorical_accuracy did not i


Epoch 00222: val_categorical_accuracy did not improve from 0.50000

Epoch 00223: val_categorical_accuracy did not improve from 0.50000

Epoch 00224: val_categorical_accuracy did not improve from 0.50000

Epoch 00225: val_categorical_accuracy did not improve from 0.50000

Epoch 00226: val_categorical_accuracy did not improve from 0.50000

Epoch 00227: val_categorical_accuracy did not improve from 0.50000

Epoch 00228: val_categorical_accuracy did not improve from 0.50000

Epoch 00229: val_categorical_accuracy did not improve from 0.50000

Epoch 00230: val_categorical_accuracy did not improve from 0.50000

Epoch 00231: val_categorical_accuracy did not improve from 0.50000

Epoch 00232: val_categorical_accuracy did not improve from 0.50000

Epoch 00233: val_categorical_accuracy did not improve from 0.50000

Epoch 00234: val_categorical_accuracy did not improve from 0.50000

Epoch 00235: val_categorical_accuracy did not improve from 0.50000

Epoch 00236: val_categorical_accuracy did not i

(224, 103, 24, 24, 1) (61, 103, 24, 24, 1) (224,) (61,)
Total samples per class: [0, 49, 14, 5, 13, 26, 0, 10, 0, 30, 71, 17, 9, 31, 5, 5], Total number of samples is 285.

unique classes in Ytest: [ 2  3  4  5  6  8 10 11 12 13 14 15 16], Total number of samples in Ytest is 61.
number of samples per class in Ytest: [10  3  1  3  6  2  6 15  4  2  7  1  1]

Xtrain_transfer => (224, 64)
Xtest_transfer  => (224, 64)
Ytrain => (224, 13)
Ytest  => (61, 13)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc13 (Dense)                 (None, 13)                3341      
Total params: 19,981
Trainable params: 19,981
Non-traina


Epoch 00081: val_categorical_accuracy did not improve from 0.45902

Epoch 00082: val_categorical_accuracy did not improve from 0.45902

Epoch 00083: val_categorical_accuracy did not improve from 0.45902

Epoch 00084: val_categorical_accuracy did not improve from 0.45902

Epoch 00085: val_categorical_accuracy did not improve from 0.45902

Epoch 00086: val_categorical_accuracy did not improve from 0.45902

Epoch 00087: val_categorical_accuracy improved from 0.45902 to 0.47541, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_75_With_source_data_as_Pavia_overlap_ratio_75_percent.h5

Epoch 00088: val_categorical_accuracy did not improve from 0.47541

Epoch 00089: val_categorical_accuracy did not improve from 0.47541

Epoch 00090: val_categorical_accuracy did not improve from 0.47541

Epoch 00091: val_categorical_accuracy did not improve from 0.47541

Epoch 00092: val_categorical_accuracy d


Epoch 00200: val_categorical_accuracy did not improve from 0.49180

Epoch 00201: val_categorical_accuracy did not improve from 0.49180

Epoch 00202: val_categorical_accuracy did not improve from 0.49180

Epoch 00203: val_categorical_accuracy did not improve from 0.49180

Epoch 00204: val_categorical_accuracy did not improve from 0.49180

Epoch 00205: val_categorical_accuracy did not improve from 0.49180

Epoch 00206: val_categorical_accuracy did not improve from 0.49180

Epoch 00207: val_categorical_accuracy did not improve from 0.49180

Epoch 00208: val_categorical_accuracy improved from 0.49180 to 0.50820, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_75_With_source_data_as_Pavia_overlap_ratio_75_percent.h5

Epoch 00209: val_categorical_accuracy did not improve from 0.50820

Epoch 00210: val_categorical_accuracy did not improve from 0.50820

Epoch 00211: val_categorical_accuracy d



= Source Model with overlap ratio of 75% will be transfered to Target Data with overlap ratio of 85%, Source Model shown below =


Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_3[0][0]                    
__________________________________________________________________________________________________
bn_conv_0 (BatchNormalization)  (None, 48, 11, 11, 3 128         conv_0[0][0]                     
__________________________________________________________________________________________________
activation_2 (Activation)       (None, 48, 11, 11, 3 0    

(639, 103, 24, 24, 1) (169, 103, 24, 24, 1) (639,) (169,)
Total samples per class: [6, 135, 36, 11, 33, 77, 4, 29, 4, 83, 216, 43, 21, 89, 11, 10], Total number of samples is 808.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 169.
number of samples per class in Ytest: [ 2 27  8  3  7 16  1  6  1 17 44  9  5 18  3  2]

Xtrain_transfer => (639, 64)
Xtest_transfer  => (639, 64)
Ytrain => (639, 16)
Ytest  => (169, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_11 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainab


Epoch 00051: val_categorical_accuracy did not improve from 0.50296

Epoch 00052: val_categorical_accuracy did not improve from 0.50296

Epoch 00053: val_categorical_accuracy did not improve from 0.50296

Epoch 00054: val_categorical_accuracy did not improve from 0.50296

Epoch 00055: val_categorical_accuracy did not improve from 0.50296

Epoch 00056: val_categorical_accuracy improved from 0.50296 to 0.51479, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_85_With_source_data_as_Pavia_overlap_ratio_75_percent.h5

Epoch 00057: val_categorical_accuracy did not improve from 0.51479

Epoch 00058: val_categorical_accuracy did not improve from 0.51479

Epoch 00059: val_categorical_accuracy did not improve from 0.51479

Epoch 00060: val_categorical_accuracy did not improve from 0.51479

Epoch 00061: val_categorical_accuracy did not improve from 0.51479

Epoch 00062: val_categorical_accuracy i


Epoch 00150: val_categorical_accuracy did not improve from 0.57396

Epoch 00151: val_categorical_accuracy did not improve from 0.57396

Epoch 00152: val_categorical_accuracy did not improve from 0.57396

Epoch 00153: val_categorical_accuracy did not improve from 0.57396

Epoch 00154: val_categorical_accuracy did not improve from 0.57396

Epoch 00155: val_categorical_accuracy did not improve from 0.57396

Epoch 00156: val_categorical_accuracy did not improve from 0.57396

Epoch 00157: val_categorical_accuracy did not improve from 0.57396

Epoch 00158: val_categorical_accuracy did not improve from 0.57396

Epoch 00159: val_categorical_accuracy did not improve from 0.57396

Epoch 00160: val_categorical_accuracy did not improve from 0.57396

Epoch 00161: val_categorical_accuracy did not improve from 0.57396

Epoch 00162: val_categorical_accuracy did not improve from 0.57396

Epoch 00163: val_categorical_accuracy did not improve from 0.57396

Epoch 00164: val_categorical_accuracy did not i


Epoch 00265: val_categorical_accuracy did not improve from 0.60947

Epoch 00266: val_categorical_accuracy did not improve from 0.60947

Epoch 00267: val_categorical_accuracy did not improve from 0.60947

Epoch 00268: val_categorical_accuracy did not improve from 0.60947

Epoch 00269: val_categorical_accuracy did not improve from 0.60947

Epoch 00270: val_categorical_accuracy did not improve from 0.60947

Epoch 00271: val_categorical_accuracy did not improve from 0.60947

Epoch 00272: val_categorical_accuracy did not improve from 0.60947

Epoch 00273: val_categorical_accuracy did not improve from 0.60947

Epoch 00274: val_categorical_accuracy did not improve from 0.60947

Epoch 00275: val_categorical_accuracy did not improve from 0.60947

Epoch 00276: val_categorical_accuracy did not improve from 0.60947

Epoch 00277: val_categorical_accuracy did not improve from 0.60947

Epoch 00278: val_categorical_accuracy did not improve from 0.60947

Epoch 00279: val_categorical_accuracy did not i

(3109, 103, 24, 24, 1) (785, 103, 24, 24, 1) (3109,) (785,)
Total samples per class: [24, 668, 177, 45, 137, 365, 14, 141, 10, 408, 1067, 181, 101, 465, 46, 45], Total number of samples is 3894.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 785.
number of samples per class in Ytest: [  5 134  36   9  28  73   3  29   2  82 214  37  21  93  10   9]

Xtrain_transfer => (3109, 64)
Xtest_transfer  => (3109, 64)
Ytrain => (3109, 16)
Ytest  => (785, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_12 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112 


Epoch 00053: val_categorical_accuracy did not improve from 0.60510

Epoch 00054: val_categorical_accuracy did not improve from 0.60510

Epoch 00055: val_categorical_accuracy improved from 0.60510 to 0.60637, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_95_With_source_data_as_Pavia_overlap_ratio_75_percent.h5

Epoch 00056: val_categorical_accuracy did not improve from 0.60637

Epoch 00057: val_categorical_accuracy did not improve from 0.60637

Epoch 00058: val_categorical_accuracy did not improve from 0.60637

Epoch 00059: val_categorical_accuracy did not improve from 0.60637

Epoch 00060: val_categorical_accuracy did not improve from 0.60637

Epoch 00061: val_categorical_accuracy improved from 0.60637 to 0.60764, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_95_With_source_data_a


Epoch 00140: val_categorical_accuracy did not improve from 0.64586

Epoch 00141: val_categorical_accuracy did not improve from 0.64586

Epoch 00142: val_categorical_accuracy improved from 0.64586 to 0.64841, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_95_With_source_data_as_Pavia_overlap_ratio_75_percent.h5

Epoch 00143: val_categorical_accuracy did not improve from 0.64841

Epoch 00144: val_categorical_accuracy did not improve from 0.64841

Epoch 00145: val_categorical_accuracy did not improve from 0.64841

Epoch 00146: val_categorical_accuracy did not improve from 0.64841

Epoch 00147: val_categorical_accuracy did not improve from 0.64841

Epoch 00148: val_categorical_accuracy did not improve from 0.64841

Epoch 00149: val_categorical_accuracy did not improve from 0.64841

Epoch 00150: val_categorical_accuracy did not improve from 0.64841

Epoch 00151: val_categorical_accuracy d


Epoch 00254: val_categorical_accuracy did not improve from 0.65223

Epoch 00255: val_categorical_accuracy did not improve from 0.65223

Epoch 00256: val_categorical_accuracy did not improve from 0.65223

Epoch 00257: val_categorical_accuracy did not improve from 0.65223

Epoch 00258: val_categorical_accuracy did not improve from 0.65223

Epoch 00259: val_categorical_accuracy did not improve from 0.65223

Epoch 00260: val_categorical_accuracy did not improve from 0.65223

Epoch 00261: val_categorical_accuracy did not improve from 0.65223

Epoch 00262: val_categorical_accuracy did not improve from 0.65223

Epoch 00263: val_categorical_accuracy did not improve from 0.65223

Epoch 00264: val_categorical_accuracy did not improve from 0.65223

Epoch 00265: val_categorical_accuracy did not improve from 0.65223

Epoch 00266: val_categorical_accuracy did not improve from 0.65223

Epoch 00267: val_categorical_accuracy did not improve from 0.65223

Epoch 00268: val_categorical_accuracy did not i

(75, 103, 24, 24, 1) (22, 103, 24, 24, 1) (75,) (22,)
Total samples per class: [0, 15, 8, 0, 7, 10, 0, 4, 0, 12, 24, 5, 0, 12, 0, 0], Total number of samples is 97.

unique classes in Ytest: [ 2  3  5  6  8 10 11 12 14], Total number of samples in Ytest is 22.
number of samples per class in Ytest: [3 2 2 2 1 3 5 1 3]

Xtrain_transfer => (75, 64)
Xtest_transfer  => (75, 64)
Ytrain => (75, 9)
Ytest  => (22, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_13 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
_______________________________


Epoch 00085: val_categorical_accuracy did not improve from 0.54545

Epoch 00086: val_categorical_accuracy did not improve from 0.54545

Epoch 00087: val_categorical_accuracy did not improve from 0.54545

Epoch 00088: val_categorical_accuracy did not improve from 0.54545

Epoch 00089: val_categorical_accuracy did not improve from 0.54545

Epoch 00090: val_categorical_accuracy did not improve from 0.54545

Epoch 00091: val_categorical_accuracy did not improve from 0.54545

Epoch 00092: val_categorical_accuracy did not improve from 0.54545

Epoch 00093: val_categorical_accuracy did not improve from 0.54545

Epoch 00094: val_categorical_accuracy did not improve from 0.54545

Epoch 00095: val_categorical_accuracy did not improve from 0.54545

Epoch 00096: val_categorical_accuracy did not improve from 0.54545

Epoch 00097: val_categorical_accuracy did not improve from 0.54545

Epoch 00098: val_categorical_accuracy did not improve from 0.54545

Epoch 00099: val_categorical_accuracy did not i

Epoch 00208: val_categorical_accuracy did not improve from 0.59091

Epoch 00209: val_categorical_accuracy did not improve from 0.59091

Epoch 00210: val_categorical_accuracy did not improve from 0.59091

Epoch 00211: val_categorical_accuracy did not improve from 0.59091

Epoch 00212: val_categorical_accuracy did not improve from 0.59091

Epoch 00213: val_categorical_accuracy did not improve from 0.59091

Epoch 00214: val_categorical_accuracy did not improve from 0.59091

Epoch 00215: val_categorical_accuracy did not improve from 0.59091

Epoch 00216: val_categorical_accuracy did not improve from 0.59091

Epoch 00217: val_categorical_accuracy did not improve from 0.59091

Epoch 00218: val_categorical_accuracy did not improve from 0.59091

Epoch 00219: val_categorical_accuracy did not improve from 0.59091

Epoch 00220: val_categorical_accuracy did not improve from 0.59091

Epoch 00221: val_categorical_accuracy did not improve from 0.59091

Epoch 00222: val_categorical_accuracy did not im

(224, 103, 24, 24, 1) (61, 103, 24, 24, 1) (224,) (61,)
Total samples per class: [0, 49, 14, 5, 13, 26, 0, 10, 0, 30, 71, 17, 9, 31, 5, 5], Total number of samples is 285.

unique classes in Ytest: [ 2  3  4  5  6  8 10 11 12 13 14 15 16], Total number of samples in Ytest is 61.
number of samples per class in Ytest: [10  3  1  3  6  2  6 15  4  2  7  1  1]

Xtrain_transfer => (224, 64)
Xtest_transfer  => (224, 64)
Ytrain => (224, 13)
Ytest  => (61, 13)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_14 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc13 (Dense)                 (None, 13)                3341      
Total params: 19,981
Trainable params: 19,981
Non-traina


Epoch 00074: val_categorical_accuracy did not improve from 0.54098

Epoch 00075: val_categorical_accuracy did not improve from 0.54098

Epoch 00076: val_categorical_accuracy did not improve from 0.54098

Epoch 00077: val_categorical_accuracy did not improve from 0.54098

Epoch 00078: val_categorical_accuracy did not improve from 0.54098

Epoch 00079: val_categorical_accuracy did not improve from 0.54098

Epoch 00080: val_categorical_accuracy did not improve from 0.54098

Epoch 00081: val_categorical_accuracy did not improve from 0.54098

Epoch 00082: val_categorical_accuracy did not improve from 0.54098

Epoch 00083: val_categorical_accuracy did not improve from 0.54098

Epoch 00084: val_categorical_accuracy did not improve from 0.54098

Epoch 00085: val_categorical_accuracy did not improve from 0.54098

Epoch 00086: val_categorical_accuracy did not improve from 0.54098

Epoch 00087: val_categorical_accuracy did not improve from 0.54098

Epoch 00088: val_categorical_accuracy did not i


Epoch 00197: val_categorical_accuracy did not improve from 0.54098

Epoch 00198: val_categorical_accuracy did not improve from 0.54098

Epoch 00199: val_categorical_accuracy did not improve from 0.54098

Epoch 00200: val_categorical_accuracy did not improve from 0.54098

Epoch 00201: val_categorical_accuracy did not improve from 0.54098

Epoch 00202: val_categorical_accuracy did not improve from 0.54098

Epoch 00203: val_categorical_accuracy did not improve from 0.54098

Epoch 00204: val_categorical_accuracy did not improve from 0.54098

Epoch 00205: val_categorical_accuracy did not improve from 0.54098

Epoch 00206: val_categorical_accuracy did not improve from 0.54098

Epoch 00207: val_categorical_accuracy did not improve from 0.54098

Epoch 00208: val_categorical_accuracy did not improve from 0.54098

Epoch 00209: val_categorical_accuracy did not improve from 0.54098

Epoch 00210: val_categorical_accuracy did not improve from 0.54098

Epoch 00211: val_categorical_accuracy did not i



= Source Model with overlap ratio of 95% will be transfered to Target Data with overlap ratio of 85%, Source Model shown below =


Model: "model_3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_4 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_4[0][0]                    
__________________________________________________________________________________________________
bn_conv_0 (BatchNormalization)  (None, 48, 11, 11, 3 128         conv_0[0][0]                     
__________________________________________________________________________________________________
activation_3 (Activation)       (None, 48, 11, 11, 3 0    

(639, 103, 24, 24, 1) (169, 103, 24, 24, 1) (639,) (169,)
Total samples per class: [6, 135, 36, 11, 33, 77, 4, 29, 4, 83, 216, 43, 21, 89, 11, 10], Total number of samples is 808.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 169.
number of samples per class in Ytest: [ 2 27  8  3  7 16  1  6  1 17 44  9  5 18  3  2]

Xtrain_transfer => (639, 64)
Xtest_transfer  => (639, 64)
Ytrain => (639, 16)
Ytest  => (169, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_15 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainab


Epoch 00060: val_categorical_accuracy improved from 0.57988 to 0.59763, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_85_With_source_data_as_Pavia_overlap_ratio_95_percent.h5

Epoch 00061: val_categorical_accuracy did not improve from 0.59763

Epoch 00062: val_categorical_accuracy did not improve from 0.59763

Epoch 00063: val_categorical_accuracy did not improve from 0.59763

Epoch 00064: val_categorical_accuracy did not improve from 0.59763

Epoch 00065: val_categorical_accuracy did not improve from 0.59763

Epoch 00066: val_categorical_accuracy did not improve from 0.59763

Epoch 00067: val_categorical_accuracy did not improve from 0.59763

Epoch 00068: val_categorical_accuracy did not improve from 0.59763

Epoch 00069: val_categorical_accuracy did not improve from 0.59763

Epoch 00070: val_categorical_accuracy did not improve from 0.59763

Epoch 00071: val_categorical_accuracy i


Epoch 00174: val_categorical_accuracy did not improve from 0.63314

Epoch 00175: val_categorical_accuracy did not improve from 0.63314

Epoch 00176: val_categorical_accuracy did not improve from 0.63314

Epoch 00177: val_categorical_accuracy did not improve from 0.63314

Epoch 00178: val_categorical_accuracy did not improve from 0.63314

Epoch 00179: val_categorical_accuracy did not improve from 0.63314

Epoch 00180: val_categorical_accuracy did not improve from 0.63314

Epoch 00181: val_categorical_accuracy did not improve from 0.63314

Epoch 00182: val_categorical_accuracy did not improve from 0.63314

Epoch 00183: val_categorical_accuracy did not improve from 0.63314

Epoch 00184: val_categorical_accuracy did not improve from 0.63314

Epoch 00185: val_categorical_accuracy did not improve from 0.63314

Epoch 00186: val_categorical_accuracy did not improve from 0.63314

Epoch 00187: val_categorical_accuracy did not improve from 0.63314

Epoch 00188: val_categorical_accuracy did not i


Epoch 00297: val_categorical_accuracy did not improve from 0.63314

Epoch 00298: val_categorical_accuracy did not improve from 0.63314

Epoch 00299: val_categorical_accuracy did not improve from 0.63314

Epoch 00300: val_categorical_accuracy did not improve from 0.63314
169/169 [==============================] - 0s 77us/sample - loss: 1.3150 - categorical_accuracy: 0.5976
Test Accuracy = 0.5976331
169/169 [==============================] - 0s 2ms/sample

============ Confusion_matrix for data with source overlap ratio of 95 and target overlap ratio of  85 is as below ============

[[ 0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0]
 [ 0 23  0  0  0  2  0  0  0  0  2  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  7  0  0  0  0  0]
 [ 0  2  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  2  0  0  0  0  0]
 [ 0  0  0  0  1 12  0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  1  0  3  0  0  1  0  0  0  0  0]
 [ 

(3109, 103, 24, 24, 1) (785, 103, 24, 24, 1) (3109,) (785,)
Total samples per class: [24, 668, 177, 45, 137, 365, 14, 141, 10, 408, 1067, 181, 101, 465, 46, 45], Total number of samples is 3894.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 785.
number of samples per class in Ytest: [  5 134  36   9  28  73   3  29   2  82 214  37  21  93  10   9]

Xtrain_transfer => (3109, 64)
Xtest_transfer  => (3109, 64)
Ytrain => (3109, 16)
Ytest  => (785, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_16 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112 


Epoch 00062: val_categorical_accuracy did not improve from 0.63949

Epoch 00063: val_categorical_accuracy did not improve from 0.63949

Epoch 00064: val_categorical_accuracy did not improve from 0.63949

Epoch 00065: val_categorical_accuracy improved from 0.63949 to 0.64459, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_95_With_source_data_as_Pavia_overlap_ratio_95_percent.h5

Epoch 00066: val_categorical_accuracy did not improve from 0.64459

Epoch 00067: val_categorical_accuracy did not improve from 0.64459

Epoch 00068: val_categorical_accuracy did not improve from 0.64459

Epoch 00069: val_categorical_accuracy did not improve from 0.64459

Epoch 00070: val_categorical_accuracy did not improve from 0.64459

Epoch 00071: val_categorical_accuracy did not improve from 0.64459

Epoch 00072: val_categorical_accuracy improved from 0.64459 to 0.66115, saving model to ..\..\Trained Model


Epoch 00168: val_categorical_accuracy did not improve from 0.67516

Epoch 00169: val_categorical_accuracy did not improve from 0.67516

Epoch 00170: val_categorical_accuracy did not improve from 0.67516

Epoch 00171: val_categorical_accuracy did not improve from 0.67516

Epoch 00172: val_categorical_accuracy did not improve from 0.67516

Epoch 00173: val_categorical_accuracy did not improve from 0.67516

Epoch 00174: val_categorical_accuracy did not improve from 0.67516

Epoch 00175: val_categorical_accuracy did not improve from 0.67516

Epoch 00176: val_categorical_accuracy did not improve from 0.67516

Epoch 00177: val_categorical_accuracy did not improve from 0.67516

Epoch 00178: val_categorical_accuracy did not improve from 0.67516

Epoch 00179: val_categorical_accuracy did not improve from 0.67516

Epoch 00180: val_categorical_accuracy did not improve from 0.67516

Epoch 00181: val_categorical_accuracy did not improve from 0.67516

Epoch 00182: val_categorical_accuracy did not i


Epoch 00282: val_categorical_accuracy did not improve from 0.68662

Epoch 00283: val_categorical_accuracy did not improve from 0.68662

Epoch 00284: val_categorical_accuracy did not improve from 0.68662

Epoch 00285: val_categorical_accuracy did not improve from 0.68662

Epoch 00286: val_categorical_accuracy did not improve from 0.68662

Epoch 00287: val_categorical_accuracy did not improve from 0.68662

Epoch 00288: val_categorical_accuracy improved from 0.68662 to 0.68790, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_95_With_source_data_as_Pavia_overlap_ratio_95_percent.h5

Epoch 00289: val_categorical_accuracy did not improve from 0.68790

Epoch 00290: val_categorical_accuracy did not improve from 0.68790

Epoch 00291: val_categorical_accuracy did not improve from 0.68790

Epoch 00292: val_categorical_accuracy did not improve from 0.68790

Epoch 00293: val_categorical_accuracy d

In [5]:
Acc_Tbl

0                1                2                3  \
0  Test Accuracy  Indian_Pines_50  Indian_Pines_75  Indian_Pines_85   
1       Pavia_25          27.2727          40.9836          41.4201   
2       Pavia_50          36.3636          44.2623          42.6035   
3       Pavia_75          40.9091          44.2623           60.355   
4       Pavia_95          45.4545          54.0984          59.7633   

                 4  
0  Indian_Pines_95  
1          49.4268  
2           51.465  
3          62.1656  
4          67.8981