# Indian Pines to Pavia

In [1]:
from Transfer_Model_Utils import *
import scipy.io as sio

In [2]:
uPavia = sio.loadmat('..\\..\\pavia\\PaviaU.mat')
gt_uPavia = sio.loadmat('..\\..\\pavia\\PaviaU_gt.mat')
data_PV = uPavia['paviaU']
gt_PV = gt_uPavia['paviaU_gt']
print(data_PV.shape, gt_PV.shape)
data_PV = np.moveaxis(data_PV, 2, 0)
print(data_PV.shape, gt_PV.shape)

(610, 340, 103) (610, 340)
(103, 610, 340) (610, 340)


In [3]:
values,counts = np.unique(gt_PV, return_counts=True)
print(values,counts)
range_of_class = list(values)
if 0 in range_of_class:
    range_of_class.pop(0)
range_of_class

[0 1 2 3 4 5 6 7 8 9] [164624   6631  18649   2099   3064   1345   5029   1330   3682    947]


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
Acc_Tbl = Transfer(overlap_ratio_List_for_Target = [25, 50, 75, 95],
                   overlap_ratio_List_for_Source = [50, 75, 85, 95],
                   epochs_list = [300, 300, 300, 300],
                   batch_size_list = [16, 32, 64, 128],
                   range_of_class = range_of_class,
                   Cube_size = 25,
                   Data = data_PV,
                   Gt = gt_PV,
                   Train_Test_split = 80,
                   channel = 103,
                   Source_data_name = 'Indian_Pines', 
                   Target_data_name = 'Pavia',
                   Verbosity = 0)

                 0         1         2         3         4
0    Test Accuracy  Pavia_25  Pavia_50  Pavia_75  Pavia_95
1  Indian_Pines_50      None      None      None      None
2  Indian_Pines_75      None      None      None      None
3  Indian_Pines_85      None      None      None      None
4  Indian_Pines_95      None      None      None      None


= Source Model with overlap ratio of 50% will be transfered to Target Data with overlap ratio of 25%, Source Model shown below =


Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_1[0][0]                    
___

(309, 103, 24, 24, 1) (82, 103, 24, 24, 1) (309,) (82,)
Total samples per class: [74, 72, 19, 98, 12, 19, 10, 56, 31], Total number of samples is 391.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 82.
number of samples per class in Ytest: [15 15  4 20  3  4  2 12  7]

Xtrain_transfer => (309, 64)
Xtest_transfer  => (309, 64)
Ytrain => (309, 9)
Ytest  => (82, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
__________________________________________


Epoch 00068: val_categorical_accuracy did not improve from 0.67073

Epoch 00069: val_categorical_accuracy did not improve from 0.67073

Epoch 00070: val_categorical_accuracy did not improve from 0.67073

Epoch 00071: val_categorical_accuracy did not improve from 0.67073

Epoch 00072: val_categorical_accuracy did not improve from 0.67073

Epoch 00073: val_categorical_accuracy improved from 0.67073 to 0.68293, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_25_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00074: val_categorical_accuracy did not improve from 0.68293

Epoch 00075: val_categorical_accuracy did not improve from 0.68293

Epoch 00076: val_categorical_accuracy did not improve from 0.68293

Epoch 00077: val_categorical_accuracy did not improve from 0.68293

Epoch 00078: val_categorical_accuracy did not improve from 0.68293

Epoch 00079: val_categorical_accuracy did not 


Epoch 00177: val_categorical_accuracy did not improve from 0.71951

Epoch 00178: val_categorical_accuracy did not improve from 0.71951

Epoch 00179: val_categorical_accuracy did not improve from 0.71951

Epoch 00180: val_categorical_accuracy did not improve from 0.71951

Epoch 00181: val_categorical_accuracy did not improve from 0.71951

Epoch 00182: val_categorical_accuracy did not improve from 0.71951

Epoch 00183: val_categorical_accuracy did not improve from 0.71951

Epoch 00184: val_categorical_accuracy did not improve from 0.71951

Epoch 00185: val_categorical_accuracy did not improve from 0.71951

Epoch 00186: val_categorical_accuracy did not improve from 0.71951

Epoch 00187: val_categorical_accuracy did not improve from 0.71951

Epoch 00188: val_categorical_accuracy did not improve from 0.71951

Epoch 00189: val_categorical_accuracy did not improve from 0.71951

Epoch 00190: val_categorical_accuracy did not improve from 0.71951

Epoch 00191: val_categorical_accuracy did not i


Epoch 00294: val_categorical_accuracy did not improve from 0.74390

Epoch 00295: val_categorical_accuracy did not improve from 0.74390

Epoch 00296: val_categorical_accuracy did not improve from 0.74390

Epoch 00297: val_categorical_accuracy did not improve from 0.74390

Epoch 00298: val_categorical_accuracy did not improve from 0.74390

Epoch 00299: val_categorical_accuracy did not improve from 0.74390

Epoch 00300: val_categorical_accuracy did not improve from 0.74390
82/82 [==============================] - 0s 215us/sample - loss: 0.9362 - categorical_accuracy: 0.6951
Test Accuracy = 0.69512194
82/82 [==============================] - 0s 189us/sample

============ Confusion_matrix for data with source overlap ratio of 50 and target overlap ratio of  25 is as below ============

[[ 9  0  0  2  0  0  0  3  1]
 [ 0 14  0  1  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  2  0]
 [ 1  0  0 18  0  0  0  0  1]
 [ 0  0  0  0  1  0  0  2  0]
 [ 0  2  0  2  0  0  0  0  0]
 [ 1  0  0  1  0  0  0  0  

(505, 103, 24, 24, 1) (130, 103, 24, 24, 1) (505,) (130,)
Total samples per class: [115, 139, 30, 133, 22, 44, 17, 96, 39], Total number of samples is 635.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 130.
number of samples per class in Ytest: [23 28  6 27  5  9  4 20  8]

Xtrain_transfer => (505, 64)
Xtest_transfer  => (505, 64)
Ytrain => (505, 9)
Ytest  => (130, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
___________________________________


Epoch 00061: val_categorical_accuracy did not improve from 0.63846

Epoch 00062: val_categorical_accuracy did not improve from 0.63846

Epoch 00063: val_categorical_accuracy did not improve from 0.63846

Epoch 00064: val_categorical_accuracy did not improve from 0.63846

Epoch 00065: val_categorical_accuracy did not improve from 0.63846

Epoch 00066: val_categorical_accuracy did not improve from 0.63846

Epoch 00067: val_categorical_accuracy did not improve from 0.63846

Epoch 00068: val_categorical_accuracy did not improve from 0.63846

Epoch 00069: val_categorical_accuracy did not improve from 0.63846

Epoch 00070: val_categorical_accuracy did not improve from 0.63846

Epoch 00071: val_categorical_accuracy improved from 0.63846 to 0.65385, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_50_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00072: val_categorical_accuracy did not 


Epoch 00167: val_categorical_accuracy did not improve from 0.69231

Epoch 00168: val_categorical_accuracy did not improve from 0.69231

Epoch 00169: val_categorical_accuracy did not improve from 0.69231

Epoch 00170: val_categorical_accuracy did not improve from 0.69231

Epoch 00171: val_categorical_accuracy improved from 0.69231 to 0.70000, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_50_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00172: val_categorical_accuracy did not improve from 0.70000

Epoch 00173: val_categorical_accuracy did not improve from 0.70000

Epoch 00174: val_categorical_accuracy did not improve from 0.70000

Epoch 00175: val_categorical_accuracy did not improve from 0.70000

Epoch 00176: val_categorical_accuracy did not improve from 0.70000

Epoch 00177: val_categorical_accuracy did not improve from 0.70000

Epoch 00178: val_categorical_accuracy did not 


Epoch 00282: val_categorical_accuracy did not improve from 0.70769

Epoch 00283: val_categorical_accuracy did not improve from 0.70769

Epoch 00284: val_categorical_accuracy did not improve from 0.70769

Epoch 00285: val_categorical_accuracy did not improve from 0.70769

Epoch 00286: val_categorical_accuracy did not improve from 0.70769

Epoch 00287: val_categorical_accuracy did not improve from 0.70769

Epoch 00288: val_categorical_accuracy did not improve from 0.70769

Epoch 00289: val_categorical_accuracy did not improve from 0.70769

Epoch 00290: val_categorical_accuracy did not improve from 0.70769

Epoch 00291: val_categorical_accuracy did not improve from 0.70769

Epoch 00292: val_categorical_accuracy did not improve from 0.70769

Epoch 00293: val_categorical_accuracy did not improve from 0.70769

Epoch 00294: val_categorical_accuracy did not improve from 0.70769

Epoch 00295: val_categorical_accuracy did not improve from 0.70769

Epoch 00296: val_categorical_accuracy did not i

(1206, 103, 24, 24, 1) (304, 103, 24, 24, 1) (1206,) (304,)
Total samples per class: [264, 425, 74, 244, 48, 139, 45, 203, 68], Total number of samples is 1510.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 304.
number of samples per class in Ytest: [53 85 15 49 10 28  9 41 14]

Xtrain_transfer => (1206, 64)
Xtest_transfer  => (1206, 64)
Ytrain => (1206, 9)
Ytest  => (304, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
___________________________


Epoch 00052: val_categorical_accuracy did not improve from 0.62171

Epoch 00053: val_categorical_accuracy did not improve from 0.62171

Epoch 00054: val_categorical_accuracy did not improve from 0.62171

Epoch 00055: val_categorical_accuracy did not improve from 0.62171

Epoch 00056: val_categorical_accuracy improved from 0.62171 to 0.64145, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00057: val_categorical_accuracy did not improve from 0.64145

Epoch 00058: val_categorical_accuracy did not improve from 0.64145

Epoch 00059: val_categorical_accuracy did not improve from 0.64145

Epoch 00060: val_categorical_accuracy did not improve from 0.64145

Epoch 00061: val_categorical_accuracy did not improve from 0.64145

Epoch 00062: val_categorical_accuracy did not improve from 0.64145

Epoch 00063: val_categorical_accuracy did not 


Epoch 00148: val_categorical_accuracy improved from 0.68750 to 0.69079, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00149: val_categorical_accuracy did not improve from 0.69079

Epoch 00150: val_categorical_accuracy did not improve from 0.69079

Epoch 00151: val_categorical_accuracy did not improve from 0.69079

Epoch 00152: val_categorical_accuracy did not improve from 0.69079

Epoch 00153: val_categorical_accuracy did not improve from 0.69079

Epoch 00154: val_categorical_accuracy did not improve from 0.69079

Epoch 00155: val_categorical_accuracy did not improve from 0.69079

Epoch 00156: val_categorical_accuracy did not improve from 0.69079

Epoch 00157: val_categorical_accuracy did not improve from 0.69079

Epoch 00158: val_categorical_accuracy did not improve from 0.69079

Epoch 00159: val_categorical_accuracy did not 


Epoch 00254: val_categorical_accuracy did not improve from 0.71711

Epoch 00255: val_categorical_accuracy did not improve from 0.71711

Epoch 00256: val_categorical_accuracy improved from 0.71711 to 0.72697, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00257: val_categorical_accuracy did not improve from 0.72697

Epoch 00258: val_categorical_accuracy did not improve from 0.72697

Epoch 00259: val_categorical_accuracy did not improve from 0.72697

Epoch 00260: val_categorical_accuracy did not improve from 0.72697

Epoch 00261: val_categorical_accuracy did not improve from 0.72697

Epoch 00262: val_categorical_accuracy did not improve from 0.72697

Epoch 00263: val_categorical_accuracy did not improve from 0.72697

Epoch 00264: val_categorical_accuracy did not improve from 0.72697

Epoch 00265: val_categorical_accuracy did not 

(13491, 103, 24, 24, 1) (3377, 103, 24, 24, 1) (13491,) (3377,)
Total samples per class: [2838, 6243, 775, 1409, 636, 2174, 603, 1758, 432], Total number of samples is 16868.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 3377.
number of samples per class in Ytest: [ 568 1249  155  282  128  435  121  352   87]

Xtrain_transfer => (13491, 64)
Xtest_transfer  => (13491, 64)
Ytrain => (13491, 9)
Ytest  => (3377, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable 


Epoch 00036: val_categorical_accuracy did not improve from 0.71780

Epoch 00037: val_categorical_accuracy did not improve from 0.71780

Epoch 00038: val_categorical_accuracy did not improve from 0.71780

Epoch 00039: val_categorical_accuracy did not improve from 0.71780

Epoch 00040: val_categorical_accuracy did not improve from 0.71780

Epoch 00041: val_categorical_accuracy improved from 0.71780 to 0.73201, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00042: val_categorical_accuracy did not improve from 0.73201

Epoch 00043: val_categorical_accuracy did not improve from 0.73201

Epoch 00044: val_categorical_accuracy did not improve from 0.73201

Epoch 00045: val_categorical_accuracy improved from 0.73201 to 0.73438, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layer


Epoch 00104: val_categorical_accuracy did not improve from 0.79686

Epoch 00105: val_categorical_accuracy did not improve from 0.79686

Epoch 00106: val_categorical_accuracy did not improve from 0.79686

Epoch 00107: val_categorical_accuracy did not improve from 0.79686

Epoch 00108: val_categorical_accuracy did not improve from 0.79686

Epoch 00109: val_categorical_accuracy improved from 0.79686 to 0.79716, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00110: val_categorical_accuracy did not improve from 0.79716

Epoch 00111: val_categorical_accuracy improved from 0.79716 to 0.80041, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00112: val_categorical_accuracy did not


Epoch 00191: val_categorical_accuracy did not improve from 0.82322

Epoch 00192: val_categorical_accuracy did not improve from 0.82322

Epoch 00193: val_categorical_accuracy did not improve from 0.82322

Epoch 00194: val_categorical_accuracy did not improve from 0.82322

Epoch 00195: val_categorical_accuracy did not improve from 0.82322

Epoch 00196: val_categorical_accuracy did not improve from 0.82322

Epoch 00197: val_categorical_accuracy did not improve from 0.82322

Epoch 00198: val_categorical_accuracy did not improve from 0.82322

Epoch 00199: val_categorical_accuracy did not improve from 0.82322

Epoch 00200: val_categorical_accuracy did not improve from 0.82322

Epoch 00201: val_categorical_accuracy did not improve from 0.82322

Epoch 00202: val_categorical_accuracy did not improve from 0.82322

Epoch 00203: val_categorical_accuracy did not improve from 0.82322

Epoch 00204: val_categorical_accuracy did not improve from 0.82322

Epoch 00205: val_categorical_accuracy improved 


Epoch 00294: val_categorical_accuracy did not improve from 0.83151

Epoch 00295: val_categorical_accuracy improved from 0.83151 to 0.83180, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00296: val_categorical_accuracy did not improve from 0.83180

Epoch 00297: val_categorical_accuracy did not improve from 0.83180

Epoch 00298: val_categorical_accuracy did not improve from 0.83180

Epoch 00299: val_categorical_accuracy improved from 0.83180 to 0.83358, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00300: val_categorical_accuracy did not improve from 0.83358
3377/3377 [==============================] - 0s 53us/sample - loss: 0.5620 - categorical_accuracy: 0.8327
Test Acc

(309, 103, 24, 24, 1) (82, 103, 24, 24, 1) (309,) (82,)
Total samples per class: [74, 72, 19, 98, 12, 19, 10, 56, 31], Total number of samples is 391.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 82.
number of samples per class in Ytest: [15 15  4 20  3  4  2 12  7]

Xtrain_transfer => (309, 64)
Xtest_transfer  => (309, 64)
Ytrain => (309, 9)
Ytest  => (82, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
__________________________________________


Epoch 00069: val_categorical_accuracy did not improve from 0.71951

Epoch 00070: val_categorical_accuracy did not improve from 0.71951

Epoch 00071: val_categorical_accuracy did not improve from 0.71951

Epoch 00072: val_categorical_accuracy did not improve from 0.71951

Epoch 00073: val_categorical_accuracy did not improve from 0.71951

Epoch 00074: val_categorical_accuracy did not improve from 0.71951

Epoch 00075: val_categorical_accuracy did not improve from 0.71951

Epoch 00076: val_categorical_accuracy improved from 0.71951 to 0.74390, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_25_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00077: val_categorical_accuracy did not improve from 0.74390

Epoch 00078: val_categorical_accuracy did not improve from 0.74390

Epoch 00079: val_categorical_accuracy did not improve from 0.74390

Epoch 00080: val_categorical_accuracy did not 


Epoch 00181: val_categorical_accuracy did not improve from 0.78049

Epoch 00182: val_categorical_accuracy did not improve from 0.78049

Epoch 00183: val_categorical_accuracy did not improve from 0.78049

Epoch 00184: val_categorical_accuracy did not improve from 0.78049

Epoch 00185: val_categorical_accuracy did not improve from 0.78049

Epoch 00186: val_categorical_accuracy did not improve from 0.78049

Epoch 00187: val_categorical_accuracy did not improve from 0.78049

Epoch 00188: val_categorical_accuracy did not improve from 0.78049

Epoch 00189: val_categorical_accuracy did not improve from 0.78049

Epoch 00190: val_categorical_accuracy did not improve from 0.78049

Epoch 00191: val_categorical_accuracy did not improve from 0.78049

Epoch 00192: val_categorical_accuracy did not improve from 0.78049

Epoch 00193: val_categorical_accuracy did not improve from 0.78049

Epoch 00194: val_categorical_accuracy did not improve from 0.78049

Epoch 00195: val_categorical_accuracy did not i

82/82 [==============================] - 0s 0s/sample - loss: 0.8016 - categorical_accuracy: 0.7073
Test Accuracy = 0.70731705
82/82 [==============================] - 0s 1ms/sample

============ Confusion_matrix for data with source overlap ratio of 75 and target overlap ratio of  25 is as below ============

[[10  2  2  0  0  0  0  1  0]
 [ 0 15  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  2  0]
 [ 0  3  0 16  0  0  0  0  1]
 [ 0  0  0  0  3  0  0  0  0]
 [ 0  4  0  0  0  0  0  0  0]
 [ 1  0  0  1  0  0  0  0  0]
 [ 3  1  0  0  0  0  0  8  0]
 [ 0  0  0  1  0  0  0  0  6]]
[15 15  4 20  3  4  2 12  7]


= Source Model with overlap ratio of 75% will be transfered to Target Data with overlap ratio of 50%, Source Model shown below =


Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 

(505, 103, 24, 24, 1) (130, 103, 24, 24, 1) (505,) (130,)
Total samples per class: [115, 139, 30, 133, 22, 44, 17, 96, 39], Total number of samples is 635.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 130.
number of samples per class in Ytest: [23 28  6 27  5  9  4 20  8]

Xtrain_transfer => (505, 64)
Xtest_transfer  => (505, 64)
Ytrain => (505, 9)
Ytest  => (130, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
___________________________________


Epoch 00065: val_categorical_accuracy did not improve from 0.65385

Epoch 00066: val_categorical_accuracy improved from 0.65385 to 0.67692, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_50_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00067: val_categorical_accuracy did not improve from 0.67692

Epoch 00068: val_categorical_accuracy did not improve from 0.67692

Epoch 00069: val_categorical_accuracy did not improve from 0.67692

Epoch 00070: val_categorical_accuracy did not improve from 0.67692

Epoch 00071: val_categorical_accuracy did not improve from 0.67692

Epoch 00072: val_categorical_accuracy did not improve from 0.67692

Epoch 00073: val_categorical_accuracy did not improve from 0.67692

Epoch 00074: val_categorical_accuracy did not improve from 0.67692

Epoch 00075: val_categorical_accuracy did not improve from 0.67692

Epoch 00076: val_categorical_accuracy did not 


Epoch 00167: val_categorical_accuracy did not improve from 0.75385

Epoch 00168: val_categorical_accuracy did not improve from 0.75385

Epoch 00169: val_categorical_accuracy did not improve from 0.75385

Epoch 00170: val_categorical_accuracy did not improve from 0.75385

Epoch 00171: val_categorical_accuracy did not improve from 0.75385

Epoch 00172: val_categorical_accuracy did not improve from 0.75385

Epoch 00173: val_categorical_accuracy did not improve from 0.75385

Epoch 00174: val_categorical_accuracy did not improve from 0.75385

Epoch 00175: val_categorical_accuracy improved from 0.75385 to 0.76154, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_50_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00176: val_categorical_accuracy did not improve from 0.76154

Epoch 00177: val_categorical_accuracy did not improve from 0.76154

Epoch 00178: val_categorical_accuracy did not 

Epoch 00283: val_categorical_accuracy did not improve from 0.76923

Epoch 00284: val_categorical_accuracy did not improve from 0.76923

Epoch 00285: val_categorical_accuracy did not improve from 0.76923

Epoch 00286: val_categorical_accuracy did not improve from 0.76923

Epoch 00287: val_categorical_accuracy did not improve from 0.76923

Epoch 00288: val_categorical_accuracy did not improve from 0.76923

Epoch 00289: val_categorical_accuracy did not improve from 0.76923

Epoch 00290: val_categorical_accuracy did not improve from 0.76923

Epoch 00291: val_categorical_accuracy did not improve from 0.76923

Epoch 00292: val_categorical_accuracy did not improve from 0.76923

Epoch 00293: val_categorical_accuracy did not improve from 0.76923

Epoch 00294: val_categorical_accuracy did not improve from 0.76923

Epoch 00295: val_categorical_accuracy did not improve from 0.76923

Epoch 00296: val_categorical_accuracy did not improve from 0.76923

Epoch 00297: val_categorical_accuracy did not im

(1206, 103, 24, 24, 1) (304, 103, 24, 24, 1) (1206,) (304,)
Total samples per class: [264, 425, 74, 244, 48, 139, 45, 203, 68], Total number of samples is 1510.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 304.
number of samples per class in Ytest: [53 85 15 49 10 28  9 41 14]

Xtrain_transfer => (1206, 64)
Xtest_transfer  => (1206, 64)
Ytrain => (1206, 9)
Ytest  => (304, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
___________________________


Epoch 00047: val_categorical_accuracy did not improve from 0.62171

Epoch 00048: val_categorical_accuracy did not improve from 0.62171

Epoch 00049: val_categorical_accuracy did not improve from 0.62171

Epoch 00050: val_categorical_accuracy did not improve from 0.62171

Epoch 00051: val_categorical_accuracy did not improve from 0.62171

Epoch 00052: val_categorical_accuracy did not improve from 0.62171

Epoch 00053: val_categorical_accuracy did not improve from 0.62171

Epoch 00054: val_categorical_accuracy improved from 0.62171 to 0.62500, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00055: val_categorical_accuracy did not improve from 0.62500

Epoch 00056: val_categorical_accuracy did not improve from 0.62500

Epoch 00057: val_categorical_accuracy did not improve from 0.62500

Epoch 00058: val_categorical_accuracy did not 


Epoch 00144: val_categorical_accuracy did not improve from 0.71053

Epoch 00145: val_categorical_accuracy did not improve from 0.71053

Epoch 00146: val_categorical_accuracy did not improve from 0.71053

Epoch 00147: val_categorical_accuracy did not improve from 0.71053

Epoch 00148: val_categorical_accuracy did not improve from 0.71053

Epoch 00149: val_categorical_accuracy did not improve from 0.71053

Epoch 00150: val_categorical_accuracy did not improve from 0.71053

Epoch 00151: val_categorical_accuracy did not improve from 0.71053

Epoch 00152: val_categorical_accuracy did not improve from 0.71053

Epoch 00153: val_categorical_accuracy did not improve from 0.71053

Epoch 00154: val_categorical_accuracy did not improve from 0.71053

Epoch 00155: val_categorical_accuracy did not improve from 0.71053

Epoch 00156: val_categorical_accuracy did not improve from 0.71053

Epoch 00157: val_categorical_accuracy did not improve from 0.71053

Epoch 00158: val_categorical_accuracy improved 


Epoch 00250: val_categorical_accuracy did not improve from 0.74671

Epoch 00251: val_categorical_accuracy did not improve from 0.74671

Epoch 00252: val_categorical_accuracy did not improve from 0.74671

Epoch 00253: val_categorical_accuracy did not improve from 0.74671

Epoch 00254: val_categorical_accuracy did not improve from 0.74671

Epoch 00255: val_categorical_accuracy did not improve from 0.74671

Epoch 00256: val_categorical_accuracy did not improve from 0.74671

Epoch 00257: val_categorical_accuracy did not improve from 0.74671

Epoch 00258: val_categorical_accuracy did not improve from 0.74671

Epoch 00259: val_categorical_accuracy did not improve from 0.74671

Epoch 00260: val_categorical_accuracy did not improve from 0.74671

Epoch 00261: val_categorical_accuracy did not improve from 0.74671

Epoch 00262: val_categorical_accuracy did not improve from 0.74671

Epoch 00263: val_categorical_accuracy did not improve from 0.74671

Epoch 00264: val_categorical_accuracy did not i

(13491, 103, 24, 24, 1) (3377, 103, 24, 24, 1) (13491,) (3377,)
Total samples per class: [2838, 6243, 775, 1409, 636, 2174, 603, 1758, 432], Total number of samples is 16868.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 3377.
number of samples per class in Ytest: [ 568 1249  155  282  128  435  121  352   87]

Xtrain_transfer => (13491, 64)
Xtest_transfer  => (13491, 64)
Ytrain => (13491, 9)
Ytest  => (3377, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable 


Epoch 00044: val_categorical_accuracy did not improve from 0.79183

Epoch 00045: val_categorical_accuracy did not improve from 0.79183

Epoch 00046: val_categorical_accuracy improved from 0.79183 to 0.79390, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00047: val_categorical_accuracy did not improve from 0.79390

Epoch 00048: val_categorical_accuracy improved from 0.79390 to 0.79479, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00049: val_categorical_accuracy did not improve from 0.79479

Epoch 00050: val_categorical_accuracy improved from 0.79479 to 0.79716, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Laye


Epoch 00117: val_categorical_accuracy did not improve from 0.82351

Epoch 00118: val_categorical_accuracy did not improve from 0.82351

Epoch 00119: val_categorical_accuracy did not improve from 0.82351

Epoch 00120: val_categorical_accuracy improved from 0.82351 to 0.82381, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00121: val_categorical_accuracy did not improve from 0.82381

Epoch 00122: val_categorical_accuracy did not improve from 0.82381

Epoch 00123: val_categorical_accuracy did not improve from 0.82381

Epoch 00124: val_categorical_accuracy did not improve from 0.82381

Epoch 00125: val_categorical_accuracy did not improve from 0.82381

Epoch 00126: val_categorical_accuracy did not improve from 0.82381

Epoch 00127: val_categorical_accuracy did not improve from 0.82381

Epoch 00128: val_categorical_accuracy did not 


Epoch 00226: val_categorical_accuracy did not improve from 0.83092

Epoch 00227: val_categorical_accuracy did not improve from 0.83092

Epoch 00228: val_categorical_accuracy did not improve from 0.83092

Epoch 00229: val_categorical_accuracy did not improve from 0.83092

Epoch 00230: val_categorical_accuracy did not improve from 0.83092

Epoch 00231: val_categorical_accuracy improved from 0.83092 to 0.83328, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00232: val_categorical_accuracy did not improve from 0.83328

Epoch 00233: val_categorical_accuracy did not improve from 0.83328

Epoch 00234: val_categorical_accuracy did not improve from 0.83328

Epoch 00235: val_categorical_accuracy did not improve from 0.83328

Epoch 00236: val_categorical_accuracy did not improve from 0.83328

Epoch 00237: val_categorical_accuracy did not 

(309, 103, 24, 24, 1) (82, 103, 24, 24, 1) (309,) (82,)
Total samples per class: [74, 72, 19, 98, 12, 19, 10, 56, 31], Total number of samples is 391.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 82.
number of samples per class in Ytest: [15 15  4 20  3  4  2 12  7]

Xtrain_transfer => (309, 64)
Xtest_transfer  => (309, 64)
Ytrain => (309, 9)
Ytest  => (82, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
__________________________________________


Epoch 00069: val_categorical_accuracy did not improve from 0.65854

Epoch 00070: val_categorical_accuracy did not improve from 0.65854

Epoch 00071: val_categorical_accuracy did not improve from 0.65854

Epoch 00072: val_categorical_accuracy did not improve from 0.65854

Epoch 00073: val_categorical_accuracy did not improve from 0.65854

Epoch 00074: val_categorical_accuracy did not improve from 0.65854

Epoch 00075: val_categorical_accuracy did not improve from 0.65854

Epoch 00076: val_categorical_accuracy did not improve from 0.65854

Epoch 00077: val_categorical_accuracy did not improve from 0.65854

Epoch 00078: val_categorical_accuracy did not improve from 0.65854

Epoch 00079: val_categorical_accuracy did not improve from 0.65854

Epoch 00080: val_categorical_accuracy did not improve from 0.65854

Epoch 00081: val_categorical_accuracy did not improve from 0.65854

Epoch 00082: val_categorical_accuracy did not improve from 0.65854

Epoch 00083: val_categorical_accuracy did not i


Epoch 00175: val_categorical_accuracy did not improve from 0.74390

Epoch 00176: val_categorical_accuracy did not improve from 0.74390

Epoch 00177: val_categorical_accuracy did not improve from 0.74390

Epoch 00178: val_categorical_accuracy did not improve from 0.74390

Epoch 00179: val_categorical_accuracy did not improve from 0.74390

Epoch 00180: val_categorical_accuracy did not improve from 0.74390

Epoch 00181: val_categorical_accuracy did not improve from 0.74390

Epoch 00182: val_categorical_accuracy did not improve from 0.74390

Epoch 00183: val_categorical_accuracy did not improve from 0.74390

Epoch 00184: val_categorical_accuracy did not improve from 0.74390

Epoch 00185: val_categorical_accuracy did not improve from 0.74390

Epoch 00186: val_categorical_accuracy did not improve from 0.74390

Epoch 00187: val_categorical_accuracy did not improve from 0.74390

Epoch 00188: val_categorical_accuracy did not improve from 0.74390

Epoch 00189: val_categorical_accuracy did not i


Epoch 00298: val_categorical_accuracy did not improve from 0.74390

Epoch 00299: val_categorical_accuracy did not improve from 0.74390

Epoch 00300: val_categorical_accuracy did not improve from 0.74390
82/82 [==============================] - 0s 0s/sample - loss: 1.0006 - categorical_accuracy: 0.7195
Test Accuracy = 0.7195122
82/82 [==============================] - 0s 3ms/sample

============ Confusion_matrix for data with source overlap ratio of 85 and target overlap ratio of  25 is as below ============

[[ 8  1  0  5  0  0  0  1  0]
 [ 0 12  0  3  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  2  0]
 [ 0  2  0 18  0  0  0  0  0]
 [ 0  0  0  0  3  0  0  0  0]
 [ 0  1  0  3  0  0  0  0  0]
 [ 1  0  0  0  0  0  1  0  0]
 [ 0  0  0  2  0  0  0 10  0]
 [ 0  0  0  0  0  0  0  0  7]]
[15 15  4 20  3  4  2 12  7]


= Source Model with overlap ratio of 85% will be transfered to Target Data with overlap ratio of 50%, Source Model shown below =


Model: "model_2"
___________________________________

(505, 103, 24, 24, 1) (130, 103, 24, 24, 1) (505,) (130,)
Total samples per class: [115, 139, 30, 133, 22, 44, 17, 96, 39], Total number of samples is 635.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 130.
number of samples per class in Ytest: [23 28  6 27  5  9  4 20  8]

Xtrain_transfer => (505, 64)
Xtest_transfer  => (505, 64)
Ytrain => (505, 9)
Ytest  => (130, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
___________________________________


Epoch 00076: val_categorical_accuracy did not improve from 0.60000

Epoch 00077: val_categorical_accuracy did not improve from 0.60000

Epoch 00078: val_categorical_accuracy did not improve from 0.60000

Epoch 00079: val_categorical_accuracy did not improve from 0.60000

Epoch 00080: val_categorical_accuracy did not improve from 0.60000

Epoch 00081: val_categorical_accuracy did not improve from 0.60000

Epoch 00082: val_categorical_accuracy did not improve from 0.60000

Epoch 00083: val_categorical_accuracy did not improve from 0.60000

Epoch 00084: val_categorical_accuracy improved from 0.60000 to 0.61538, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_50_With_source_data_as_Indian_Pines_overlap_ratio_85_percent.h5

Epoch 00085: val_categorical_accuracy did not improve from 0.61538

Epoch 00086: val_categorical_accuracy did not improve from 0.61538

Epoch 00087: val_categorical_accuracy did not 


Epoch 00182: val_categorical_accuracy did not improve from 0.66923

Epoch 00183: val_categorical_accuracy did not improve from 0.66923

Epoch 00184: val_categorical_accuracy did not improve from 0.66923

Epoch 00185: val_categorical_accuracy improved from 0.66923 to 0.67692, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_50_With_source_data_as_Indian_Pines_overlap_ratio_85_percent.h5

Epoch 00186: val_categorical_accuracy did not improve from 0.67692

Epoch 00187: val_categorical_accuracy did not improve from 0.67692

Epoch 00188: val_categorical_accuracy did not improve from 0.67692

Epoch 00189: val_categorical_accuracy did not improve from 0.67692

Epoch 00190: val_categorical_accuracy did not improve from 0.67692

Epoch 00191: val_categorical_accuracy did not improve from 0.67692

Epoch 00192: val_categorical_accuracy did not improve from 0.67692

Epoch 00193: val_categorical_accuracy did not 


Epoch 00289: val_categorical_accuracy did not improve from 0.71538

Epoch 00290: val_categorical_accuracy did not improve from 0.71538

Epoch 00291: val_categorical_accuracy did not improve from 0.71538

Epoch 00292: val_categorical_accuracy did not improve from 0.71538

Epoch 00293: val_categorical_accuracy did not improve from 0.71538

Epoch 00294: val_categorical_accuracy did not improve from 0.71538

Epoch 00295: val_categorical_accuracy did not improve from 0.71538

Epoch 00296: val_categorical_accuracy did not improve from 0.71538

Epoch 00297: val_categorical_accuracy did not improve from 0.71538

Epoch 00298: val_categorical_accuracy did not improve from 0.71538

Epoch 00299: val_categorical_accuracy did not improve from 0.71538

Epoch 00300: val_categorical_accuracy did not improve from 0.71538
130/130 [==============================] - 0s 95us/sample - loss: 0.9495 - categorical_accuracy: 0.6615
Test Accuracy = 0.6615385
130/130 [==============================] - 0s 2ms/samp

(1206, 103, 24, 24, 1) (304, 103, 24, 24, 1) (1206,) (304,)
Total samples per class: [264, 425, 74, 244, 48, 139, 45, 203, 68], Total number of samples is 1510.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 304.
number of samples per class in Ytest: [53 85 15 49 10 28  9 41 14]

Xtrain_transfer => (1206, 64)
Xtest_transfer  => (1206, 64)
Ytrain => (1206, 9)
Ytest  => (304, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_11 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
___________________________


Epoch 00059: val_categorical_accuracy did not improve from 0.57566

Epoch 00060: val_categorical_accuracy improved from 0.57566 to 0.59868, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_85_percent.h5

Epoch 00061: val_categorical_accuracy did not improve from 0.59868

Epoch 00062: val_categorical_accuracy did not improve from 0.59868

Epoch 00063: val_categorical_accuracy did not improve from 0.59868

Epoch 00064: val_categorical_accuracy did not improve from 0.59868

Epoch 00065: val_categorical_accuracy did not improve from 0.59868

Epoch 00066: val_categorical_accuracy did not improve from 0.59868

Epoch 00067: val_categorical_accuracy did not improve from 0.59868

Epoch 00068: val_categorical_accuracy did not improve from 0.59868

Epoch 00069: val_categorical_accuracy did not improve from 0.59868

Epoch 00070: val_categorical_accuracy did not 


Epoch 00150: val_categorical_accuracy did not improve from 0.67763

Epoch 00151: val_categorical_accuracy did not improve from 0.67763

Epoch 00152: val_categorical_accuracy did not improve from 0.67763

Epoch 00153: val_categorical_accuracy did not improve from 0.67763

Epoch 00154: val_categorical_accuracy did not improve from 0.67763

Epoch 00155: val_categorical_accuracy did not improve from 0.67763

Epoch 00156: val_categorical_accuracy did not improve from 0.67763

Epoch 00157: val_categorical_accuracy improved from 0.67763 to 0.68750, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_85_percent.h5

Epoch 00158: val_categorical_accuracy did not improve from 0.68750

Epoch 00159: val_categorical_accuracy did not improve from 0.68750

Epoch 00160: val_categorical_accuracy did not improve from 0.68750

Epoch 00161: val_categorical_accuracy did not 


Epoch 00260: val_categorical_accuracy did not improve from 0.70066

Epoch 00261: val_categorical_accuracy did not improve from 0.70066

Epoch 00262: val_categorical_accuracy did not improve from 0.70066

Epoch 00263: val_categorical_accuracy did not improve from 0.70066

Epoch 00264: val_categorical_accuracy did not improve from 0.70066

Epoch 00265: val_categorical_accuracy did not improve from 0.70066

Epoch 00266: val_categorical_accuracy did not improve from 0.70066

Epoch 00267: val_categorical_accuracy did not improve from 0.70066

Epoch 00268: val_categorical_accuracy did not improve from 0.70066

Epoch 00269: val_categorical_accuracy did not improve from 0.70066

Epoch 00270: val_categorical_accuracy did not improve from 0.70066

Epoch 00271: val_categorical_accuracy did not improve from 0.70066

Epoch 00272: val_categorical_accuracy did not improve from 0.70066

Epoch 00273: val_categorical_accuracy did not improve from 0.70066

Epoch 00274: val_categorical_accuracy did not i

(13491, 103, 24, 24, 1) (3377, 103, 24, 24, 1) (13491,) (3377,)
Total samples per class: [2838, 6243, 775, 1409, 636, 2174, 603, 1758, 432], Total number of samples is 16868.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 3377.
number of samples per class in Ytest: [ 568 1249  155  282  128  435  121  352   87]

Xtrain_transfer => (13491, 64)
Xtest_transfer  => (13491, 64)
Ytrain => (13491, 9)
Ytest  => (3377, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_12 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable 


Epoch 00035: val_categorical_accuracy did not improve from 0.71839

Epoch 00036: val_categorical_accuracy improved from 0.71839 to 0.71869, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_85_percent.h5

Epoch 00037: val_categorical_accuracy improved from 0.71869 to 0.72461, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_85_percent.h5

Epoch 00038: val_categorical_accuracy improved from 0.72461 to 0.72875, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_85_percent.h5

Epoch 00039: val_categorical_accuracy did not improve from 0.72875

Epoch 00040: val_categorical_accuracy did no


Epoch 00107: val_categorical_accuracy did not improve from 0.77258

Epoch 00108: val_categorical_accuracy did not improve from 0.77258

Epoch 00109: val_categorical_accuracy did not improve from 0.77258

Epoch 00110: val_categorical_accuracy did not improve from 0.77258

Epoch 00111: val_categorical_accuracy did not improve from 0.77258

Epoch 00112: val_categorical_accuracy did not improve from 0.77258

Epoch 00113: val_categorical_accuracy did not improve from 0.77258

Epoch 00114: val_categorical_accuracy did not improve from 0.77258

Epoch 00115: val_categorical_accuracy did not improve from 0.77258

Epoch 00116: val_categorical_accuracy did not improve from 0.77258

Epoch 00117: val_categorical_accuracy did not improve from 0.77258

Epoch 00118: val_categorical_accuracy did not improve from 0.77258

Epoch 00119: val_categorical_accuracy did not improve from 0.77258

Epoch 00120: val_categorical_accuracy did not improve from 0.77258

Epoch 00121: val_categorical_accuracy did not i


Epoch 00210: val_categorical_accuracy did not improve from 0.78531

Epoch 00211: val_categorical_accuracy did not improve from 0.78531

Epoch 00212: val_categorical_accuracy did not improve from 0.78531

Epoch 00213: val_categorical_accuracy did not improve from 0.78531

Epoch 00214: val_categorical_accuracy did not improve from 0.78531

Epoch 00215: val_categorical_accuracy did not improve from 0.78531

Epoch 00216: val_categorical_accuracy did not improve from 0.78531

Epoch 00217: val_categorical_accuracy did not improve from 0.78531

Epoch 00218: val_categorical_accuracy did not improve from 0.78531

Epoch 00219: val_categorical_accuracy did not improve from 0.78531

Epoch 00220: val_categorical_accuracy did not improve from 0.78531

Epoch 00221: val_categorical_accuracy did not improve from 0.78531

Epoch 00222: val_categorical_accuracy did not improve from 0.78531

Epoch 00223: val_categorical_accuracy improved from 0.78531 to 0.78739, saving model to ..\..\Trained Models\Transf

(309, 103, 24, 24, 1) (82, 103, 24, 24, 1) (309,) (82,)
Total samples per class: [74, 72, 19, 98, 12, 19, 10, 56, 31], Total number of samples is 391.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 82.
number of samples per class in Ytest: [15 15  4 20  3  4  2 12  7]

Xtrain_transfer => (309, 64)
Xtest_transfer  => (309, 64)
Ytrain => (309, 9)
Ytest  => (82, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_13 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
__________________________________________


Epoch 00045: val_categorical_accuracy did not improve from 0.63415

Epoch 00046: val_categorical_accuracy did not improve from 0.63415

Epoch 00047: val_categorical_accuracy did not improve from 0.63415

Epoch 00048: val_categorical_accuracy did not improve from 0.63415

Epoch 00049: val_categorical_accuracy did not improve from 0.63415

Epoch 00050: val_categorical_accuracy improved from 0.63415 to 0.64634, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_25_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00051: val_categorical_accuracy did not improve from 0.64634

Epoch 00052: val_categorical_accuracy improved from 0.64634 to 0.65854, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_25_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00053: val_categorical_accuracy did not


Epoch 00142: val_categorical_accuracy did not improve from 0.74390

Epoch 00143: val_categorical_accuracy did not improve from 0.74390

Epoch 00144: val_categorical_accuracy did not improve from 0.74390

Epoch 00145: val_categorical_accuracy did not improve from 0.74390

Epoch 00146: val_categorical_accuracy did not improve from 0.74390

Epoch 00147: val_categorical_accuracy did not improve from 0.74390

Epoch 00148: val_categorical_accuracy did not improve from 0.74390

Epoch 00149: val_categorical_accuracy did not improve from 0.74390

Epoch 00150: val_categorical_accuracy improved from 0.74390 to 0.75610, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_25_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00151: val_categorical_accuracy did not improve from 0.75610

Epoch 00152: val_categorical_accuracy did not improve from 0.75610

Epoch 00153: val_categorical_accuracy did not 


Epoch 00257: val_categorical_accuracy did not improve from 0.76829

Epoch 00258: val_categorical_accuracy did not improve from 0.76829

Epoch 00259: val_categorical_accuracy did not improve from 0.76829

Epoch 00260: val_categorical_accuracy improved from 0.76829 to 0.78049, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_25_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00261: val_categorical_accuracy did not improve from 0.78049

Epoch 00262: val_categorical_accuracy did not improve from 0.78049

Epoch 00263: val_categorical_accuracy did not improve from 0.78049

Epoch 00264: val_categorical_accuracy did not improve from 0.78049

Epoch 00265: val_categorical_accuracy did not improve from 0.78049

Epoch 00266: val_categorical_accuracy did not improve from 0.78049

Epoch 00267: val_categorical_accuracy did not improve from 0.78049

Epoch 00268: val_categorical_accuracy did not 

(505, 103, 24, 24, 1) (130, 103, 24, 24, 1) (505,) (130,)
Total samples per class: [115, 139, 30, 133, 22, 44, 17, 96, 39], Total number of samples is 635.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 130.
number of samples per class in Ytest: [23 28  6 27  5  9  4 20  8]

Xtrain_transfer => (505, 64)
Xtest_transfer  => (505, 64)
Ytrain => (505, 9)
Ytest  => (130, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_14 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
___________________________________


Epoch 00056: val_categorical_accuracy did not improve from 0.56923

Epoch 00057: val_categorical_accuracy did not improve from 0.56923

Epoch 00058: val_categorical_accuracy did not improve from 0.56923

Epoch 00059: val_categorical_accuracy improved from 0.56923 to 0.57692, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_50_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00060: val_categorical_accuracy did not improve from 0.57692

Epoch 00061: val_categorical_accuracy did not improve from 0.57692

Epoch 00062: val_categorical_accuracy did not improve from 0.57692

Epoch 00063: val_categorical_accuracy improved from 0.57692 to 0.59231, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_50_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00064: val_categorical_accuracy did not


Epoch 00157: val_categorical_accuracy did not improve from 0.66923

Epoch 00158: val_categorical_accuracy did not improve from 0.66923

Epoch 00159: val_categorical_accuracy did not improve from 0.66923

Epoch 00160: val_categorical_accuracy did not improve from 0.66923

Epoch 00161: val_categorical_accuracy did not improve from 0.66923

Epoch 00162: val_categorical_accuracy did not improve from 0.66923

Epoch 00163: val_categorical_accuracy did not improve from 0.66923

Epoch 00164: val_categorical_accuracy did not improve from 0.66923

Epoch 00165: val_categorical_accuracy did not improve from 0.66923

Epoch 00166: val_categorical_accuracy did not improve from 0.66923

Epoch 00167: val_categorical_accuracy did not improve from 0.66923

Epoch 00168: val_categorical_accuracy did not improve from 0.66923

Epoch 00169: val_categorical_accuracy did not improve from 0.66923

Epoch 00170: val_categorical_accuracy did not improve from 0.66923

Epoch 00171: val_categorical_accuracy did not i


Epoch 00276: val_categorical_accuracy did not improve from 0.67692

Epoch 00277: val_categorical_accuracy did not improve from 0.67692

Epoch 00278: val_categorical_accuracy did not improve from 0.67692

Epoch 00279: val_categorical_accuracy did not improve from 0.67692

Epoch 00280: val_categorical_accuracy did not improve from 0.67692

Epoch 00281: val_categorical_accuracy did not improve from 0.67692

Epoch 00282: val_categorical_accuracy did not improve from 0.67692

Epoch 00283: val_categorical_accuracy did not improve from 0.67692

Epoch 00284: val_categorical_accuracy did not improve from 0.67692

Epoch 00285: val_categorical_accuracy did not improve from 0.67692

Epoch 00286: val_categorical_accuracy did not improve from 0.67692

Epoch 00287: val_categorical_accuracy did not improve from 0.67692

Epoch 00288: val_categorical_accuracy did not improve from 0.67692

Epoch 00289: val_categorical_accuracy did not improve from 0.67692

Epoch 00290: val_categorical_accuracy did not i

(1206, 103, 24, 24, 1) (304, 103, 24, 24, 1) (1206,) (304,)
Total samples per class: [264, 425, 74, 244, 48, 139, 45, 203, 68], Total number of samples is 1510.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 304.
number of samples per class in Ytest: [53 85 15 49 10 28  9 41 14]

Xtrain_transfer => (1206, 64)
Xtest_transfer  => (1206, 64)
Ytrain => (1206, 9)
Ytest  => (304, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_15 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
___________________________

Epoch 00054: val_categorical_accuracy did not improve from 0.53618

Epoch 00055: val_categorical_accuracy improved from 0.53618 to 0.58882, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00056: val_categorical_accuracy did not improve from 0.58882

Epoch 00057: val_categorical_accuracy did not improve from 0.58882

Epoch 00058: val_categorical_accuracy did not improve from 0.58882

Epoch 00059: val_categorical_accuracy improved from 0.58882 to 0.59868, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00060: val_categorical_accuracy did not improve from 0.59868

Epoch 00061: val_categorical_accuracy did not improve from 0.59868

Epoch 00062: val_categorical_accuracy did not 


Epoch 00145: val_categorical_accuracy did not improve from 0.67105

Epoch 00146: val_categorical_accuracy did not improve from 0.67105

Epoch 00147: val_categorical_accuracy did not improve from 0.67105

Epoch 00148: val_categorical_accuracy did not improve from 0.67105

Epoch 00149: val_categorical_accuracy did not improve from 0.67105

Epoch 00150: val_categorical_accuracy did not improve from 0.67105

Epoch 00151: val_categorical_accuracy did not improve from 0.67105

Epoch 00152: val_categorical_accuracy did not improve from 0.67105

Epoch 00153: val_categorical_accuracy did not improve from 0.67105

Epoch 00154: val_categorical_accuracy did not improve from 0.67105

Epoch 00155: val_categorical_accuracy did not improve from 0.67105

Epoch 00156: val_categorical_accuracy did not improve from 0.67105

Epoch 00157: val_categorical_accuracy improved from 0.67105 to 0.68750, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers


Epoch 00258: val_categorical_accuracy improved from 0.71382 to 0.73026, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_75_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00259: val_categorical_accuracy did not improve from 0.73026

Epoch 00260: val_categorical_accuracy did not improve from 0.73026

Epoch 00261: val_categorical_accuracy did not improve from 0.73026

Epoch 00262: val_categorical_accuracy did not improve from 0.73026

Epoch 00263: val_categorical_accuracy did not improve from 0.73026

Epoch 00264: val_categorical_accuracy did not improve from 0.73026

Epoch 00265: val_categorical_accuracy did not improve from 0.73026

Epoch 00266: val_categorical_accuracy did not improve from 0.73026

Epoch 00267: val_categorical_accuracy did not improve from 0.73026

Epoch 00268: val_categorical_accuracy did not improve from 0.73026

Epoch 00269: val_categorical_accuracy did not 

(13491, 103, 24, 24, 1) (3377, 103, 24, 24, 1) (13491,) (3377,)
Total samples per class: [2838, 6243, 775, 1409, 636, 2174, 603, 1758, 432], Total number of samples is 16868.

unique classes in Ytest: [1 2 3 4 5 6 7 8 9], Total number of samples in Ytest is 3377.
number of samples per class in Ytest: [ 568 1249  155  282  128  435  121  352   87]

Xtrain_transfer => (13491, 64)
Xtest_transfer  => (13491, 64)
Ytrain => (13491, 9)
Ytest  => (3377, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_16 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable 


Epoch 00038: val_categorical_accuracy did not improve from 0.73083

Epoch 00039: val_categorical_accuracy improved from 0.73083 to 0.73497, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00040: val_categorical_accuracy did not improve from 0.73497

Epoch 00041: val_categorical_accuracy improved from 0.73497 to 0.73645, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00042: val_categorical_accuracy improved from 0.73645 to 0.73853, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00043: val_categorical_accuracy did no


Epoch 00105: val_categorical_accuracy did not improve from 0.77969

Epoch 00106: val_categorical_accuracy did not improve from 0.77969

Epoch 00107: val_categorical_accuracy did not improve from 0.77969

Epoch 00108: val_categorical_accuracy improved from 0.77969 to 0.78354, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00109: val_categorical_accuracy did not improve from 0.78354

Epoch 00110: val_categorical_accuracy did not improve from 0.78354

Epoch 00111: val_categorical_accuracy did not improve from 0.78354

Epoch 00112: val_categorical_accuracy did not improve from 0.78354

Epoch 00113: val_categorical_accuracy did not improve from 0.78354

Epoch 00114: val_categorical_accuracy did not improve from 0.78354

Epoch 00115: val_categorical_accuracy did not improve from 0.78354

Epoch 00116: val_categorical_accuracy did not 


Epoch 00193: val_categorical_accuracy did not improve from 0.80397

Epoch 00194: val_categorical_accuracy did not improve from 0.80397

Epoch 00195: val_categorical_accuracy did not improve from 0.80397

Epoch 00196: val_categorical_accuracy improved from 0.80397 to 0.80486, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_95_percent.h5

Epoch 00197: val_categorical_accuracy did not improve from 0.80486

Epoch 00198: val_categorical_accuracy did not improve from 0.80486

Epoch 00199: val_categorical_accuracy did not improve from 0.80486

Epoch 00200: val_categorical_accuracy did not improve from 0.80486

Epoch 00201: val_categorical_accuracy did not improve from 0.80486

Epoch 00202: val_categorical_accuracy improved from 0.80486 to 0.80574, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layer


Epoch 00281: val_categorical_accuracy did not improve from 0.81167

Epoch 00282: val_categorical_accuracy did not improve from 0.81167

Epoch 00283: val_categorical_accuracy did not improve from 0.81167

Epoch 00284: val_categorical_accuracy did not improve from 0.81167

Epoch 00285: val_categorical_accuracy did not improve from 0.81167

Epoch 00286: val_categorical_accuracy did not improve from 0.81167

Epoch 00287: val_categorical_accuracy did not improve from 0.81167

Epoch 00288: val_categorical_accuracy did not improve from 0.81167

Epoch 00289: val_categorical_accuracy did not improve from 0.81167

Epoch 00290: val_categorical_accuracy did not improve from 0.81167

Epoch 00291: val_categorical_accuracy did not improve from 0.81167

Epoch 00292: val_categorical_accuracy improved from 0.81167 to 0.81344, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Pavia\Fully_Connected_Layers_for_Pavia_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap

In [5]:
Acc_Tbl

0         1         2         3         4
0    Test Accuracy  Pavia_25  Pavia_50  Pavia_75  Pavia_95
1  Indian_Pines_50   69.5122   71.5385   70.0658   83.2692
2  Indian_Pines_75   70.7317   76.1538   73.3553   83.4172
3  Indian_Pines_85   71.9512   66.1538     68.75   78.2943
4  Indian_Pines_95   71.9512   66.1538   69.4079   81.1667