# Indian Pines to Indian Pines

In [1]:
from Transfer_Model_Utils import *
import scipy.io as sio

In [2]:
uIndian_pines = sio.loadmat('..\\..\\Indian Pines\\Indian_pines_corrected.mat')
gt_uIndian_pines = sio.loadmat('..\\..\\Indian Pines\\Indian_pines_gt.mat')
data_IN = uIndian_pines['indian_pines_corrected']
gt_IN = gt_uIndian_pines['indian_pines_gt']
print(data_IN.shape, gt_IN.shape)
data_IN = np.moveaxis(data_IN, 2, 0)
print(data_IN.shape, gt_IN.shape)

(145, 145, 200) (145, 145)
(200, 145, 145) (145, 145)


In [3]:
values,counts = np.unique(gt_IN, return_counts=True)
print(values,counts)
range_of_class = list(values)
if 0 in range_of_class:
    range_of_class.pop(0)
range_of_class

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16] [10776    46  1428   830   237   483   730    28   478    20   972  2455
   593   205  1265   386    93]


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

In [4]:
Acc_Tbl = Transfer(overlap_ratio_List_for_Target = [50, 75, 85, 95],
                   overlap_ratio_List_for_Source = [50, 75, 85, 95],
                   epochs_list = [300, 300, 300, 300],
                   batch_size_list = [16, 32, 64, 128],
                   range_of_class = range_of_class,
                   Cube_size = 25,
                   Data = data_IN,
                   Gt = gt_IN,
                   Train_Test_split = 80,
                   channel = 103,
                   Source_data_name = 'Indian_Pines', 
                   Target_data_name = 'Indian_Pines',
                   Verbosity = 0)

                 0                1                2                3  \
0    Test Accuracy  Indian_Pines_50  Indian_Pines_75  Indian_Pines_85   
1  Indian_Pines_50             None             None             None   
2  Indian_Pines_75             None             None             None   
3  Indian_Pines_85             None             None             None   
4  Indian_Pines_95             None             None             None   

                 4  
0  Indian_Pines_95  
1             None  
2             None  
3             None  
4             None  


= Source Model with overlap ratio of 50% will be transfered to Target Data with overlap ratio of 50%, Source Model shown below =


Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 103, 24, 24, 0                                   

(75, 103, 24, 24, 1) (22, 103, 24, 24, 1) (75,) (22,)
Total samples per class: [0, 15, 8, 0, 7, 10, 0, 4, 0, 12, 24, 5, 0, 12, 0, 0], Total number of samples is 97.

unique classes in Ytest: [ 2  3  5  6  8 10 11 12 14], Total number of samples in Ytest is 22.
number of samples per class in Ytest: [3 2 2 2 1 3 5 1 3]

Xtrain_transfer => (75, 64)
Xtest_transfer  => (75, 64)
Ytrain => (75, 9)
Ytest  => (22, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
_______________________________


Epoch 00103: val_categorical_accuracy did not improve from 0.45455

Epoch 00104: val_categorical_accuracy did not improve from 0.45455

Epoch 00105: val_categorical_accuracy did not improve from 0.45455

Epoch 00106: val_categorical_accuracy did not improve from 0.45455

Epoch 00107: val_categorical_accuracy did not improve from 0.45455

Epoch 00108: val_categorical_accuracy did not improve from 0.45455

Epoch 00109: val_categorical_accuracy did not improve from 0.45455

Epoch 00110: val_categorical_accuracy did not improve from 0.45455

Epoch 00111: val_categorical_accuracy did not improve from 0.45455

Epoch 00112: val_categorical_accuracy did not improve from 0.45455

Epoch 00113: val_categorical_accuracy did not improve from 0.45455

Epoch 00114: val_categorical_accuracy did not improve from 0.45455

Epoch 00115: val_categorical_accuracy did not improve from 0.45455

Epoch 00116: val_categorical_accuracy did not improve from 0.45455

Epoch 00117: val_categorical_accuracy did not i


Epoch 00230: val_categorical_accuracy did not improve from 0.45455

Epoch 00231: val_categorical_accuracy did not improve from 0.45455

Epoch 00232: val_categorical_accuracy did not improve from 0.45455

Epoch 00233: val_categorical_accuracy did not improve from 0.45455

Epoch 00234: val_categorical_accuracy did not improve from 0.45455

Epoch 00235: val_categorical_accuracy did not improve from 0.45455

Epoch 00236: val_categorical_accuracy did not improve from 0.45455

Epoch 00237: val_categorical_accuracy did not improve from 0.45455

Epoch 00238: val_categorical_accuracy did not improve from 0.45455

Epoch 00239: val_categorical_accuracy did not improve from 0.45455

Epoch 00240: val_categorical_accuracy did not improve from 0.45455

Epoch 00241: val_categorical_accuracy did not improve from 0.45455

Epoch 00242: val_categorical_accuracy did not improve from 0.45455

Epoch 00243: val_categorical_accuracy did not improve from 0.45455

Epoch 00244: val_categorical_accuracy did not i

(224, 103, 24, 24, 1) (61, 103, 24, 24, 1) (224,) (61,)
Total samples per class: [0, 49, 14, 5, 13, 26, 0, 10, 0, 30, 71, 17, 9, 31, 5, 5], Total number of samples is 285.

unique classes in Ytest: [ 2  3  4  5  6  8 10 11 12 13 14 15 16], Total number of samples in Ytest is 61.
number of samples per class in Ytest: [10  3  1  3  6  2  6 15  4  2  7  1  1]

Xtrain_transfer => (224, 64)
Xtest_transfer  => (224, 64)
Ytrain => (224, 13)
Ytest  => (61, 13)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc13 (Dense)                 (None, 13)                3341      
Total params: 19,981
Trainable params: 19,981
Non-traina


Epoch 00071: val_categorical_accuracy did not improve from 0.49180

Epoch 00072: val_categorical_accuracy did not improve from 0.49180

Epoch 00073: val_categorical_accuracy did not improve from 0.49180

Epoch 00074: val_categorical_accuracy did not improve from 0.49180

Epoch 00075: val_categorical_accuracy did not improve from 0.49180

Epoch 00076: val_categorical_accuracy did not improve from 0.49180

Epoch 00077: val_categorical_accuracy did not improve from 0.49180

Epoch 00078: val_categorical_accuracy did not improve from 0.49180

Epoch 00079: val_categorical_accuracy did not improve from 0.49180

Epoch 00080: val_categorical_accuracy did not improve from 0.49180

Epoch 00081: val_categorical_accuracy did not improve from 0.49180

Epoch 00082: val_categorical_accuracy did not improve from 0.49180

Epoch 00083: val_categorical_accuracy did not improve from 0.49180

Epoch 00084: val_categorical_accuracy did not improve from 0.49180

Epoch 00085: val_categorical_accuracy did not i


Epoch 00185: val_categorical_accuracy did not improve from 0.57377

Epoch 00186: val_categorical_accuracy did not improve from 0.57377

Epoch 00187: val_categorical_accuracy did not improve from 0.57377

Epoch 00188: val_categorical_accuracy did not improve from 0.57377

Epoch 00189: val_categorical_accuracy did not improve from 0.57377

Epoch 00190: val_categorical_accuracy did not improve from 0.57377

Epoch 00191: val_categorical_accuracy did not improve from 0.57377

Epoch 00192: val_categorical_accuracy did not improve from 0.57377

Epoch 00193: val_categorical_accuracy did not improve from 0.57377

Epoch 00194: val_categorical_accuracy did not improve from 0.57377

Epoch 00195: val_categorical_accuracy did not improve from 0.57377

Epoch 00196: val_categorical_accuracy did not improve from 0.57377

Epoch 00197: val_categorical_accuracy did not improve from 0.57377

Epoch 00198: val_categorical_accuracy did not improve from 0.57377

Epoch 00199: val_categorical_accuracy did not i



= Source Model with overlap ratio of 50% will be transfered to Target Data with overlap ratio of 85%, Source Model shown below =


Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_1[0][0]                    
__________________________________________________________________________________________________
bn_conv_0 (BatchNormalization)  (None, 48, 11, 11, 3 128         conv_0[0][0]                     
__________________________________________________________________________________________________
activation (Activation)         (None, 48, 11, 11, 3 0      

(639, 103, 24, 24, 1) (169, 103, 24, 24, 1) (639,) (169,)
Total samples per class: [6, 135, 36, 11, 33, 77, 4, 29, 4, 83, 216, 43, 21, 89, 11, 10], Total number of samples is 808.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 169.
number of samples per class in Ytest: [ 2 27  8  3  7 16  1  6  1 17 44  9  5 18  3  2]

Xtrain_transfer => (639, 64)
Xtest_transfer  => (639, 64)
Ytrain => (639, 16)
Ytest  => (169, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainab


Epoch 00047: val_categorical_accuracy did not improve from 0.54438

Epoch 00048: val_categorical_accuracy did not improve from 0.54438

Epoch 00049: val_categorical_accuracy did not improve from 0.54438

Epoch 00050: val_categorical_accuracy did not improve from 0.54438

Epoch 00051: val_categorical_accuracy did not improve from 0.54438

Epoch 00052: val_categorical_accuracy did not improve from 0.54438

Epoch 00053: val_categorical_accuracy improved from 0.54438 to 0.55030, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_85_With_source_data_as_Indian_Pines_overlap_ratio_50_percent.h5

Epoch 00054: val_categorical_accuracy did not improve from 0.55030

Epoch 00055: val_categorical_accuracy improved from 0.55030 to 0.55621, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_85_With_source


Epoch 00148: val_categorical_accuracy did not improve from 0.60355

Epoch 00149: val_categorical_accuracy did not improve from 0.60355

Epoch 00150: val_categorical_accuracy did not improve from 0.60355

Epoch 00151: val_categorical_accuracy did not improve from 0.60355

Epoch 00152: val_categorical_accuracy did not improve from 0.60355

Epoch 00153: val_categorical_accuracy did not improve from 0.60355

Epoch 00154: val_categorical_accuracy did not improve from 0.60355

Epoch 00155: val_categorical_accuracy did not improve from 0.60355

Epoch 00156: val_categorical_accuracy did not improve from 0.60355

Epoch 00157: val_categorical_accuracy did not improve from 0.60355

Epoch 00158: val_categorical_accuracy did not improve from 0.60355

Epoch 00159: val_categorical_accuracy did not improve from 0.60355

Epoch 00160: val_categorical_accuracy did not improve from 0.60355

Epoch 00161: val_categorical_accuracy did not improve from 0.60355

Epoch 00162: val_categorical_accuracy did not i


Epoch 00270: val_categorical_accuracy did not improve from 0.60355

Epoch 00271: val_categorical_accuracy did not improve from 0.60355

Epoch 00272: val_categorical_accuracy did not improve from 0.60355

Epoch 00273: val_categorical_accuracy did not improve from 0.60355

Epoch 00274: val_categorical_accuracy did not improve from 0.60355

Epoch 00275: val_categorical_accuracy did not improve from 0.60355

Epoch 00276: val_categorical_accuracy did not improve from 0.60355

Epoch 00277: val_categorical_accuracy did not improve from 0.60355

Epoch 00278: val_categorical_accuracy did not improve from 0.60355

Epoch 00279: val_categorical_accuracy did not improve from 0.60355

Epoch 00280: val_categorical_accuracy did not improve from 0.60355

Epoch 00281: val_categorical_accuracy did not improve from 0.60355

Epoch 00282: val_categorical_accuracy did not improve from 0.60355

Epoch 00283: val_categorical_accuracy did not improve from 0.60355

Epoch 00284: val_categorical_accuracy did not i

(3109, 103, 24, 24, 1) (785, 103, 24, 24, 1) (3109,) (785,)
Total samples per class: [24, 668, 177, 45, 137, 365, 14, 141, 10, 408, 1067, 181, 101, 465, 46, 45], Total number of samples is 3894.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 785.
number of samples per class in Ytest: [  5 134  36   9  28  73   3  29   2  82 214  37  21  93  10   9]

Xtrain_transfer => (3109, 64)
Xtest_transfer  => (3109, 64)
Ytrain => (3109, 16)
Ytest  => (785, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112 


Epoch 00045: val_categorical_accuracy did not improve from 0.62803

Epoch 00046: val_categorical_accuracy did not improve from 0.62803

Epoch 00047: val_categorical_accuracy did not improve from 0.62803

Epoch 00048: val_categorical_accuracy did not improve from 0.62803

Epoch 00049: val_categorical_accuracy did not improve from 0.62803

Epoch 00050: val_categorical_accuracy did not improve from 0.62803

Epoch 00051: val_categorical_accuracy did not improve from 0.62803

Epoch 00052: val_categorical_accuracy did not improve from 0.62803

Epoch 00053: val_categorical_accuracy did not improve from 0.62803

Epoch 00054: val_categorical_accuracy did not improve from 0.62803

Epoch 00055: val_categorical_accuracy did not improve from 0.62803

Epoch 00056: val_categorical_accuracy did not improve from 0.62803

Epoch 00057: val_categorical_accuracy did not improve from 0.62803

Epoch 00058: val_categorical_accuracy did not improve from 0.62803

Epoch 00059: val_categorical_accuracy did not i


Epoch 00150: val_categorical_accuracy did not improve from 0.63949

Epoch 00151: val_categorical_accuracy did not improve from 0.63949

Epoch 00152: val_categorical_accuracy did not improve from 0.63949

Epoch 00153: val_categorical_accuracy did not improve from 0.63949

Epoch 00154: val_categorical_accuracy did not improve from 0.63949

Epoch 00155: val_categorical_accuracy did not improve from 0.63949

Epoch 00156: val_categorical_accuracy did not improve from 0.63949

Epoch 00157: val_categorical_accuracy did not improve from 0.63949

Epoch 00158: val_categorical_accuracy did not improve from 0.63949

Epoch 00159: val_categorical_accuracy did not improve from 0.63949

Epoch 00160: val_categorical_accuracy did not improve from 0.63949

Epoch 00161: val_categorical_accuracy did not improve from 0.63949

Epoch 00162: val_categorical_accuracy did not improve from 0.63949

Epoch 00163: val_categorical_accuracy did not improve from 0.63949

Epoch 00164: val_categorical_accuracy did not i


Epoch 00264: val_categorical_accuracy did not improve from 0.64586

Epoch 00265: val_categorical_accuracy did not improve from 0.64586

Epoch 00266: val_categorical_accuracy did not improve from 0.64586

Epoch 00267: val_categorical_accuracy did not improve from 0.64586

Epoch 00268: val_categorical_accuracy did not improve from 0.64586

Epoch 00269: val_categorical_accuracy did not improve from 0.64586

Epoch 00270: val_categorical_accuracy did not improve from 0.64586

Epoch 00271: val_categorical_accuracy did not improve from 0.64586

Epoch 00272: val_categorical_accuracy did not improve from 0.64586

Epoch 00273: val_categorical_accuracy did not improve from 0.64586

Epoch 00274: val_categorical_accuracy did not improve from 0.64586

Epoch 00275: val_categorical_accuracy did not improve from 0.64586

Epoch 00276: val_categorical_accuracy did not improve from 0.64586

Epoch 00277: val_categorical_accuracy did not improve from 0.64586

Epoch 00278: val_categorical_accuracy did not i

(75, 103, 24, 24, 1) (22, 103, 24, 24, 1) (75,) (22,)
Total samples per class: [0, 15, 8, 0, 7, 10, 0, 4, 0, 12, 24, 5, 0, 12, 0, 0], Total number of samples is 97.

unique classes in Ytest: [ 2  3  5  6  8 10 11 12 14], Total number of samples in Ytest is 22.
number of samples per class in Ytest: [3 2 2 2 1 3 5 1 3]

Xtrain_transfer => (75, 64)
Xtest_transfer  => (75, 64)
Ytrain => (75, 9)
Ytest  => (22, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
_______________________________


Epoch 00089: val_categorical_accuracy did not improve from 0.45455

Epoch 00090: val_categorical_accuracy did not improve from 0.45455

Epoch 00091: val_categorical_accuracy did not improve from 0.45455

Epoch 00092: val_categorical_accuracy did not improve from 0.45455

Epoch 00093: val_categorical_accuracy did not improve from 0.45455

Epoch 00094: val_categorical_accuracy did not improve from 0.45455

Epoch 00095: val_categorical_accuracy did not improve from 0.45455

Epoch 00096: val_categorical_accuracy did not improve from 0.45455

Epoch 00097: val_categorical_accuracy did not improve from 0.45455

Epoch 00098: val_categorical_accuracy did not improve from 0.45455

Epoch 00099: val_categorical_accuracy did not improve from 0.45455

Epoch 00100: val_categorical_accuracy did not improve from 0.45455

Epoch 00101: val_categorical_accuracy did not improve from 0.45455

Epoch 00102: val_categorical_accuracy did not improve from 0.45455

Epoch 00103: val_categorical_accuracy did not i


Epoch 00212: val_categorical_accuracy did not improve from 0.45455

Epoch 00213: val_categorical_accuracy did not improve from 0.45455

Epoch 00214: val_categorical_accuracy did not improve from 0.45455

Epoch 00215: val_categorical_accuracy did not improve from 0.45455

Epoch 00216: val_categorical_accuracy did not improve from 0.45455

Epoch 00217: val_categorical_accuracy did not improve from 0.45455

Epoch 00218: val_categorical_accuracy did not improve from 0.45455

Epoch 00219: val_categorical_accuracy did not improve from 0.45455

Epoch 00220: val_categorical_accuracy did not improve from 0.45455

Epoch 00221: val_categorical_accuracy did not improve from 0.45455

Epoch 00222: val_categorical_accuracy did not improve from 0.45455

Epoch 00223: val_categorical_accuracy did not improve from 0.45455

Epoch 00224: val_categorical_accuracy did not improve from 0.45455

Epoch 00225: val_categorical_accuracy did not improve from 0.45455

Epoch 00226: val_categorical_accuracy did not i

(224, 103, 24, 24, 1) (61, 103, 24, 24, 1) (224,) (61,)
Total samples per class: [0, 49, 14, 5, 13, 26, 0, 10, 0, 30, 71, 17, 9, 31, 5, 5], Total number of samples is 285.

unique classes in Ytest: [ 2  3  4  5  6  8 10 11 12 13 14 15 16], Total number of samples in Ytest is 61.
number of samples per class in Ytest: [10  3  1  3  6  2  6 15  4  2  7  1  1]

Xtrain_transfer => (224, 64)
Xtest_transfer  => (224, 64)
Ytrain => (224, 13)
Ytest  => (61, 13)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc13 (Dense)                 (None, 13)                3341      
Total params: 19,981
Trainable params: 19,981
Non-traina


Epoch 00093: val_categorical_accuracy did not improve from 0.55738

Epoch 00094: val_categorical_accuracy did not improve from 0.55738

Epoch 00095: val_categorical_accuracy did not improve from 0.55738

Epoch 00096: val_categorical_accuracy did not improve from 0.55738

Epoch 00097: val_categorical_accuracy did not improve from 0.55738

Epoch 00098: val_categorical_accuracy did not improve from 0.55738

Epoch 00099: val_categorical_accuracy did not improve from 0.55738

Epoch 00100: val_categorical_accuracy did not improve from 0.55738

Epoch 00101: val_categorical_accuracy did not improve from 0.55738

Epoch 00102: val_categorical_accuracy did not improve from 0.55738

Epoch 00103: val_categorical_accuracy did not improve from 0.55738

Epoch 00104: val_categorical_accuracy did not improve from 0.55738

Epoch 00105: val_categorical_accuracy did not improve from 0.55738

Epoch 00106: val_categorical_accuracy did not improve from 0.55738

Epoch 00107: val_categorical_accuracy did not i

Epoch 00219: val_categorical_accuracy did not improve from 0.55738

Epoch 00220: val_categorical_accuracy did not improve from 0.55738

Epoch 00221: val_categorical_accuracy did not improve from 0.55738

Epoch 00222: val_categorical_accuracy did not improve from 0.55738

Epoch 00223: val_categorical_accuracy did not improve from 0.55738

Epoch 00224: val_categorical_accuracy did not improve from 0.55738

Epoch 00225: val_categorical_accuracy did not improve from 0.55738

Epoch 00226: val_categorical_accuracy did not improve from 0.55738

Epoch 00227: val_categorical_accuracy did not improve from 0.55738

Epoch 00228: val_categorical_accuracy did not improve from 0.55738

Epoch 00229: val_categorical_accuracy did not improve from 0.55738

Epoch 00230: val_categorical_accuracy did not improve from 0.55738

Epoch 00231: val_categorical_accuracy did not improve from 0.55738

Epoch 00232: val_categorical_accuracy did not improve from 0.55738

Epoch 00233: val_categorical_accuracy did not im

(639, 103, 24, 24, 1) (169, 103, 24, 24, 1) (639,) (169,)
Total samples per class: [6, 135, 36, 11, 33, 77, 4, 29, 4, 83, 216, 43, 21, 89, 11, 10], Total number of samples is 808.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 169.
number of samples per class in Ytest: [ 2 27  8  3  7 16  1  6  1 17 44  9  5 18  3  2]

Xtrain_transfer => (639, 64)
Xtest_transfer  => (639, 64)
Ytrain => (639, 16)
Ytest  => (169, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainab


Epoch 00062: val_categorical_accuracy improved from 0.43787 to 0.44970, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_85_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00063: val_categorical_accuracy did not improve from 0.44970

Epoch 00064: val_categorical_accuracy did not improve from 0.44970

Epoch 00065: val_categorical_accuracy improved from 0.44970 to 0.45562, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_85_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00066: val_categorical_accuracy did not improve from 0.45562

Epoch 00067: val_categorical_accuracy did not improve from 0.45562

Epoch 00068: val_categorical_accuracy improved from 0.45562 to 0.46154, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Onl


Epoch 00163: val_categorical_accuracy did not improve from 0.48521

Epoch 00164: val_categorical_accuracy did not improve from 0.48521

Epoch 00165: val_categorical_accuracy did not improve from 0.48521

Epoch 00166: val_categorical_accuracy did not improve from 0.48521

Epoch 00167: val_categorical_accuracy did not improve from 0.48521

Epoch 00168: val_categorical_accuracy did not improve from 0.48521

Epoch 00169: val_categorical_accuracy did not improve from 0.48521

Epoch 00170: val_categorical_accuracy did not improve from 0.48521

Epoch 00171: val_categorical_accuracy did not improve from 0.48521

Epoch 00172: val_categorical_accuracy did not improve from 0.48521

Epoch 00173: val_categorical_accuracy did not improve from 0.48521

Epoch 00174: val_categorical_accuracy did not improve from 0.48521

Epoch 00175: val_categorical_accuracy did not improve from 0.48521

Epoch 00176: val_categorical_accuracy did not improve from 0.48521

Epoch 00177: val_categorical_accuracy did not i


Epoch 00267: val_categorical_accuracy did not improve from 0.53254

Epoch 00268: val_categorical_accuracy did not improve from 0.53254

Epoch 00269: val_categorical_accuracy did not improve from 0.53254

Epoch 00270: val_categorical_accuracy did not improve from 0.53254

Epoch 00271: val_categorical_accuracy did not improve from 0.53254

Epoch 00272: val_categorical_accuracy did not improve from 0.53254

Epoch 00273: val_categorical_accuracy did not improve from 0.53254

Epoch 00274: val_categorical_accuracy did not improve from 0.53254

Epoch 00275: val_categorical_accuracy did not improve from 0.53254

Epoch 00276: val_categorical_accuracy did not improve from 0.53254

Epoch 00277: val_categorical_accuracy did not improve from 0.53254

Epoch 00278: val_categorical_accuracy did not improve from 0.53254

Epoch 00279: val_categorical_accuracy did not improve from 0.53254

Epoch 00280: val_categorical_accuracy did not improve from 0.53254

Epoch 00281: val_categorical_accuracy did not i

(3109, 103, 24, 24, 1) (785, 103, 24, 24, 1) (3109,) (785,)
Total samples per class: [24, 668, 177, 45, 137, 365, 14, 141, 10, 408, 1067, 181, 101, 465, 46, 45], Total number of samples is 3894.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 785.
number of samples per class in Ytest: [  5 134  36   9  28  73   3  29   2  82 214  37  21  93  10   9]

Xtrain_transfer => (3109, 64)
Xtest_transfer  => (3109, 64)
Ytrain => (3109, 16)
Ytest  => (785, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112 


Epoch 00047: val_categorical_accuracy did not improve from 0.58471

Epoch 00048: val_categorical_accuracy did not improve from 0.58471

Epoch 00049: val_categorical_accuracy did not improve from 0.58471

Epoch 00050: val_categorical_accuracy did not improve from 0.58471

Epoch 00051: val_categorical_accuracy improved from 0.58471 to 0.58726, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00052: val_categorical_accuracy did not improve from 0.58726

Epoch 00053: val_categorical_accuracy improved from 0.58726 to 0.60000, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00054: val_categorical_accuracy did not improve from 0.60000

Epoch 00055: val_


Epoch 00128: val_categorical_accuracy did not improve from 0.63567

Epoch 00129: val_categorical_accuracy did not improve from 0.63567

Epoch 00130: val_categorical_accuracy did not improve from 0.63567

Epoch 00131: val_categorical_accuracy did not improve from 0.63567

Epoch 00132: val_categorical_accuracy did not improve from 0.63567

Epoch 00133: val_categorical_accuracy did not improve from 0.63567

Epoch 00134: val_categorical_accuracy did not improve from 0.63567

Epoch 00135: val_categorical_accuracy did not improve from 0.63567

Epoch 00136: val_categorical_accuracy did not improve from 0.63567

Epoch 00137: val_categorical_accuracy improved from 0.63567 to 0.63694, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_75_percent.h5

Epoch 00138: val_categorical_accuracy did not improve from 0.63694

Epoch 00139: val_categorical_acc


Epoch 00225: val_categorical_accuracy did not improve from 0.65350

Epoch 00226: val_categorical_accuracy did not improve from 0.65350

Epoch 00227: val_categorical_accuracy did not improve from 0.65350

Epoch 00228: val_categorical_accuracy did not improve from 0.65350

Epoch 00229: val_categorical_accuracy did not improve from 0.65350

Epoch 00230: val_categorical_accuracy did not improve from 0.65350

Epoch 00231: val_categorical_accuracy did not improve from 0.65350

Epoch 00232: val_categorical_accuracy did not improve from 0.65350

Epoch 00233: val_categorical_accuracy did not improve from 0.65350

Epoch 00234: val_categorical_accuracy did not improve from 0.65350

Epoch 00235: val_categorical_accuracy did not improve from 0.65350

Epoch 00236: val_categorical_accuracy did not improve from 0.65350

Epoch 00237: val_categorical_accuracy did not improve from 0.65350

Epoch 00238: val_categorical_accuracy did not improve from 0.65350

Epoch 00239: val_categorical_accuracy did not i

(75, 103, 24, 24, 1) (22, 103, 24, 24, 1) (75,) (22,)
Total samples per class: [0, 15, 8, 0, 7, 10, 0, 4, 0, 12, 24, 5, 0, 12, 0, 0], Total number of samples is 97.

unique classes in Ytest: [ 2  3  5  6  8 10 11 12 14], Total number of samples in Ytest is 22.
number of samples per class in Ytest: [3 2 2 2 1 3 5 1 3]

Xtrain_transfer => (75, 64)
Xtest_transfer  => (75, 64)
Ytrain => (75, 9)
Ytest  => (22, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
_______________________________


Epoch 00075: val_categorical_accuracy did not improve from 0.68182

Epoch 00076: val_categorical_accuracy did not improve from 0.68182

Epoch 00077: val_categorical_accuracy did not improve from 0.68182

Epoch 00078: val_categorical_accuracy did not improve from 0.68182

Epoch 00079: val_categorical_accuracy did not improve from 0.68182

Epoch 00080: val_categorical_accuracy did not improve from 0.68182

Epoch 00081: val_categorical_accuracy did not improve from 0.68182

Epoch 00082: val_categorical_accuracy did not improve from 0.68182

Epoch 00083: val_categorical_accuracy did not improve from 0.68182

Epoch 00084: val_categorical_accuracy did not improve from 0.68182

Epoch 00085: val_categorical_accuracy did not improve from 0.68182

Epoch 00086: val_categorical_accuracy did not improve from 0.68182

Epoch 00087: val_categorical_accuracy did not improve from 0.68182

Epoch 00088: val_categorical_accuracy did not improve from 0.68182

Epoch 00089: val_categorical_accuracy did not i


Epoch 00203: val_categorical_accuracy did not improve from 0.68182

Epoch 00204: val_categorical_accuracy did not improve from 0.68182

Epoch 00205: val_categorical_accuracy did not improve from 0.68182

Epoch 00206: val_categorical_accuracy did not improve from 0.68182

Epoch 00207: val_categorical_accuracy did not improve from 0.68182

Epoch 00208: val_categorical_accuracy did not improve from 0.68182

Epoch 00209: val_categorical_accuracy did not improve from 0.68182

Epoch 00210: val_categorical_accuracy did not improve from 0.68182

Epoch 00211: val_categorical_accuracy did not improve from 0.68182

Epoch 00212: val_categorical_accuracy did not improve from 0.68182

Epoch 00213: val_categorical_accuracy did not improve from 0.68182

Epoch 00214: val_categorical_accuracy did not improve from 0.68182

Epoch 00215: val_categorical_accuracy did not improve from 0.68182

Epoch 00216: val_categorical_accuracy did not improve from 0.68182

Epoch 00217: val_categorical_accuracy did not i

(224, 103, 24, 24, 1) (61, 103, 24, 24, 1) (224,) (61,)
Total samples per class: [0, 49, 14, 5, 13, 26, 0, 10, 0, 30, 71, 17, 9, 31, 5, 5], Total number of samples is 285.

unique classes in Ytest: [ 2  3  4  5  6  8 10 11 12 13 14 15 16], Total number of samples in Ytest is 61.
number of samples per class in Ytest: [10  3  1  3  6  2  6 15  4  2  7  1  1]

Xtrain_transfer => (224, 64)
Xtest_transfer  => (224, 64)
Ytrain => (224, 13)
Ytest  => (61, 13)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc13 (Dense)                 (None, 13)                3341      
Total params: 19,981
Trainable params: 19,981
Non-traina

Epoch 00066: val_categorical_accuracy did not improve from 0.70492

Epoch 00067: val_categorical_accuracy did not improve from 0.70492

Epoch 00068: val_categorical_accuracy did not improve from 0.70492

Epoch 00069: val_categorical_accuracy did not improve from 0.70492

Epoch 00070: val_categorical_accuracy did not improve from 0.70492

Epoch 00071: val_categorical_accuracy did not improve from 0.70492

Epoch 00072: val_categorical_accuracy did not improve from 0.70492

Epoch 00073: val_categorical_accuracy did not improve from 0.70492

Epoch 00074: val_categorical_accuracy did not improve from 0.70492

Epoch 00075: val_categorical_accuracy did not improve from 0.70492

Epoch 00076: val_categorical_accuracy did not improve from 0.70492

Epoch 00077: val_categorical_accuracy did not improve from 0.70492

Epoch 00078: val_categorical_accuracy did not improve from 0.70492

Epoch 00079: val_categorical_accuracy did not improve from 0.70492

Epoch 00080: val_categorical_accuracy did not im


Epoch 00182: val_categorical_accuracy did not improve from 0.75410

Epoch 00183: val_categorical_accuracy did not improve from 0.75410

Epoch 00184: val_categorical_accuracy did not improve from 0.75410

Epoch 00185: val_categorical_accuracy did not improve from 0.75410

Epoch 00186: val_categorical_accuracy did not improve from 0.75410

Epoch 00187: val_categorical_accuracy did not improve from 0.75410

Epoch 00188: val_categorical_accuracy did not improve from 0.75410

Epoch 00189: val_categorical_accuracy did not improve from 0.75410

Epoch 00190: val_categorical_accuracy did not improve from 0.75410

Epoch 00191: val_categorical_accuracy did not improve from 0.75410

Epoch 00192: val_categorical_accuracy did not improve from 0.75410

Epoch 00193: val_categorical_accuracy did not improve from 0.75410

Epoch 00194: val_categorical_accuracy did not improve from 0.75410

Epoch 00195: val_categorical_accuracy did not improve from 0.75410

Epoch 00196: val_categorical_accuracy did not i

Test Accuracy = 0.75409836
61/61 [==============================] - 0s 4ms/sample

============ Confusion_matrix for data with source overlap ratio of 85 and target overlap ratio of  75 is as below ============

[[ 8  0  0  1  0  0  0  1  0  0  0  0  0]
 [ 0  3  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  5  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  3  2  0  0  0  0  0]
 [ 0  0  0  1  0  0  0 13  0  1  0  0  0]
 [ 4  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  7  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  0]]
[10  3  1  3  6  2  6 15  4  2  7  1  1]


= Source Model with overlap ratio of 85% will be transfered to Target Data with overlap ratio of 85%, Source Model shown below =


Model: "model_2"
__________________________________________________

(639, 103, 24, 24, 1) (169, 103, 24, 24, 1) (639,) (169,)
Total samples per class: [6, 135, 36, 11, 33, 77, 4, 29, 4, 83, 216, 43, 21, 89, 11, 10], Total number of samples is 808.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 169.
number of samples per class in Ytest: [ 2 27  8  3  7 16  1  6  1 17 44  9  5 18  3  2]

Xtrain_transfer => (639, 64)
Xtest_transfer  => (639, 64)
Ytrain => (639, 16)
Ytest  => (169, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_11 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainab


Epoch 00079: val_categorical_accuracy did not improve from 0.69822

Epoch 00080: val_categorical_accuracy did not improve from 0.69822

Epoch 00081: val_categorical_accuracy did not improve from 0.69822

Epoch 00082: val_categorical_accuracy did not improve from 0.69822

Epoch 00083: val_categorical_accuracy did not improve from 0.69822

Epoch 00084: val_categorical_accuracy did not improve from 0.69822

Epoch 00085: val_categorical_accuracy did not improve from 0.69822

Epoch 00086: val_categorical_accuracy did not improve from 0.69822

Epoch 00087: val_categorical_accuracy did not improve from 0.69822

Epoch 00088: val_categorical_accuracy did not improve from 0.69822

Epoch 00089: val_categorical_accuracy did not improve from 0.69822

Epoch 00090: val_categorical_accuracy did not improve from 0.69822

Epoch 00091: val_categorical_accuracy did not improve from 0.69822

Epoch 00092: val_categorical_accuracy did not improve from 0.69822

Epoch 00093: val_categorical_accuracy did not i


Epoch 00202: val_categorical_accuracy did not improve from 0.70414

Epoch 00203: val_categorical_accuracy did not improve from 0.70414

Epoch 00204: val_categorical_accuracy did not improve from 0.70414

Epoch 00205: val_categorical_accuracy did not improve from 0.70414

Epoch 00206: val_categorical_accuracy did not improve from 0.70414

Epoch 00207: val_categorical_accuracy did not improve from 0.70414

Epoch 00208: val_categorical_accuracy did not improve from 0.70414

Epoch 00209: val_categorical_accuracy did not improve from 0.70414

Epoch 00210: val_categorical_accuracy did not improve from 0.70414

Epoch 00211: val_categorical_accuracy did not improve from 0.70414

Epoch 00212: val_categorical_accuracy did not improve from 0.70414

Epoch 00213: val_categorical_accuracy did not improve from 0.70414

Epoch 00214: val_categorical_accuracy did not improve from 0.70414

Epoch 00215: val_categorical_accuracy did not improve from 0.70414

Epoch 00216: val_categorical_accuracy did not i



= Source Model with overlap ratio of 85% will be transfered to Target Data with overlap ratio of 95%, Source Model shown below =


Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_3[0][0]                    
__________________________________________________________________________________________________
bn_conv_0 (BatchNormalization)  (None, 48, 11, 11, 3 128         conv_0[0][0]                     
__________________________________________________________________________________________________
activation_2 (Activation)       (None, 48, 11, 11, 3 0    

(3109, 103, 24, 24, 1) (785, 103, 24, 24, 1) (3109,) (785,)
Total samples per class: [24, 668, 177, 45, 137, 365, 14, 141, 10, 408, 1067, 181, 101, 465, 46, 45], Total number of samples is 3894.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 785.
number of samples per class in Ytest: [  5 134  36   9  28  73   3  29   2  82 214  37  21  93  10   9]

Xtrain_transfer => (3109, 64)
Xtest_transfer  => (3109, 64)
Ytrain => (3109, 16)
Ytest  => (785, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_12 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112 


Epoch 00060: val_categorical_accuracy did not improve from 0.72739

Epoch 00061: val_categorical_accuracy did not improve from 0.72739

Epoch 00062: val_categorical_accuracy did not improve from 0.72739

Epoch 00063: val_categorical_accuracy did not improve from 0.72739

Epoch 00064: val_categorical_accuracy did not improve from 0.72739

Epoch 00065: val_categorical_accuracy did not improve from 0.72739

Epoch 00066: val_categorical_accuracy did not improve from 0.72739

Epoch 00067: val_categorical_accuracy did not improve from 0.72739

Epoch 00068: val_categorical_accuracy did not improve from 0.72739

Epoch 00069: val_categorical_accuracy did not improve from 0.72739

Epoch 00070: val_categorical_accuracy did not improve from 0.72739

Epoch 00071: val_categorical_accuracy did not improve from 0.72739

Epoch 00072: val_categorical_accuracy did not improve from 0.72739

Epoch 00073: val_categorical_accuracy improved from 0.72739 to 0.72866, saving model to ..\..\Trained Models\Transf


Epoch 00162: val_categorical_accuracy did not improve from 0.73503

Epoch 00163: val_categorical_accuracy did not improve from 0.73503

Epoch 00164: val_categorical_accuracy did not improve from 0.73503

Epoch 00165: val_categorical_accuracy improved from 0.73503 to 0.73631, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_85_percent.h5

Epoch 00166: val_categorical_accuracy did not improve from 0.73631

Epoch 00167: val_categorical_accuracy did not improve from 0.73631

Epoch 00168: val_categorical_accuracy did not improve from 0.73631

Epoch 00169: val_categorical_accuracy did not improve from 0.73631

Epoch 00170: val_categorical_accuracy did not improve from 0.73631

Epoch 00171: val_categorical_accuracy did not improve from 0.73631

Epoch 00172: val_categorical_accuracy did not improve from 0.73631

Epoch 00173: val_categorical_acc


Epoch 00267: val_categorical_accuracy did not improve from 0.74522

Epoch 00268: val_categorical_accuracy did not improve from 0.74522

Epoch 00269: val_categorical_accuracy did not improve from 0.74522

Epoch 00270: val_categorical_accuracy did not improve from 0.74522

Epoch 00271: val_categorical_accuracy did not improve from 0.74522

Epoch 00272: val_categorical_accuracy did not improve from 0.74522

Epoch 00273: val_categorical_accuracy did not improve from 0.74522

Epoch 00274: val_categorical_accuracy did not improve from 0.74522

Epoch 00275: val_categorical_accuracy improved from 0.74522 to 0.74650, saving model to ..\..\Trained Models\Transfered_Models\Fully_Connected_Layers_Only\Indian_Pines\Fully_Connected_Layers_for_Indian_Pines_overlap_ratio_95_With_source_data_as_Indian_Pines_overlap_ratio_85_percent.h5

Epoch 00276: val_categorical_accuracy did not improve from 0.74650

Epoch 00277: val_categorical_accuracy did not improve from 0.74650

Epoch 00278: val_categorical_acc

(75, 103, 24, 24, 1) (22, 103, 24, 24, 1) (75,) (22,)
Total samples per class: [0, 15, 8, 0, 7, 10, 0, 4, 0, 12, 24, 5, 0, 12, 0, 0], Total number of samples is 97.

unique classes in Ytest: [ 2  3  5  6  8 10 11 12 14], Total number of samples in Ytest is 22.
number of samples per class in Ytest: [3 2 2 2 1 3 5 1 3]

Xtrain_transfer => (75, 64)
Xtest_transfer  => (75, 64)
Ytrain => (75, 9)
Ytest  => (22, 9)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_13 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc9 (Dense)                  (None, 9)                 2313      
Total params: 18,953
Trainable params: 18,953
Non-trainable params: 0
_______________________________


Epoch 00079: val_categorical_accuracy did not improve from 0.59091

Epoch 00080: val_categorical_accuracy did not improve from 0.59091

Epoch 00081: val_categorical_accuracy did not improve from 0.59091

Epoch 00082: val_categorical_accuracy did not improve from 0.59091

Epoch 00083: val_categorical_accuracy did not improve from 0.59091

Epoch 00084: val_categorical_accuracy did not improve from 0.59091

Epoch 00085: val_categorical_accuracy did not improve from 0.59091

Epoch 00086: val_categorical_accuracy did not improve from 0.59091

Epoch 00087: val_categorical_accuracy did not improve from 0.59091

Epoch 00088: val_categorical_accuracy did not improve from 0.59091

Epoch 00089: val_categorical_accuracy did not improve from 0.59091

Epoch 00090: val_categorical_accuracy did not improve from 0.59091

Epoch 00091: val_categorical_accuracy did not improve from 0.59091

Epoch 00092: val_categorical_accuracy did not improve from 0.59091

Epoch 00093: val_categorical_accuracy did not i


Epoch 00203: val_categorical_accuracy did not improve from 0.59091

Epoch 00204: val_categorical_accuracy did not improve from 0.59091

Epoch 00205: val_categorical_accuracy did not improve from 0.59091

Epoch 00206: val_categorical_accuracy did not improve from 0.59091

Epoch 00207: val_categorical_accuracy did not improve from 0.59091

Epoch 00208: val_categorical_accuracy did not improve from 0.59091

Epoch 00209: val_categorical_accuracy did not improve from 0.59091

Epoch 00210: val_categorical_accuracy did not improve from 0.59091

Epoch 00211: val_categorical_accuracy did not improve from 0.59091

Epoch 00212: val_categorical_accuracy did not improve from 0.59091

Epoch 00213: val_categorical_accuracy did not improve from 0.59091

Epoch 00214: val_categorical_accuracy did not improve from 0.59091

Epoch 00215: val_categorical_accuracy did not improve from 0.59091

Epoch 00216: val_categorical_accuracy did not improve from 0.59091

Epoch 00217: val_categorical_accuracy did not i

(224, 103, 24, 24, 1) (61, 103, 24, 24, 1) (224,) (61,)
Total samples per class: [0, 49, 14, 5, 13, 26, 0, 10, 0, 30, 71, 17, 9, 31, 5, 5], Total number of samples is 285.

unique classes in Ytest: [ 2  3  4  5  6  8 10 11 12 13 14 15 16], Total number of samples in Ytest is 61.
number of samples per class in Ytest: [10  3  1  3  6  2  6 15  4  2  7  1  1]

Xtrain_transfer => (224, 64)
Xtest_transfer  => (224, 64)
Ytrain => (224, 13)
Ytest  => (61, 13)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_14 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc13 (Dense)                 (None, 13)                3341      
Total params: 19,981
Trainable params: 19,981
Non-traina


Epoch 00066: val_categorical_accuracy did not improve from 0.72131

Epoch 00067: val_categorical_accuracy did not improve from 0.72131

Epoch 00068: val_categorical_accuracy did not improve from 0.72131

Epoch 00069: val_categorical_accuracy did not improve from 0.72131

Epoch 00070: val_categorical_accuracy did not improve from 0.72131

Epoch 00071: val_categorical_accuracy did not improve from 0.72131

Epoch 00072: val_categorical_accuracy did not improve from 0.72131

Epoch 00073: val_categorical_accuracy did not improve from 0.72131

Epoch 00074: val_categorical_accuracy did not improve from 0.72131

Epoch 00075: val_categorical_accuracy did not improve from 0.72131

Epoch 00076: val_categorical_accuracy did not improve from 0.72131

Epoch 00077: val_categorical_accuracy did not improve from 0.72131

Epoch 00078: val_categorical_accuracy did not improve from 0.72131

Epoch 00079: val_categorical_accuracy did not improve from 0.72131

Epoch 00080: val_categorical_accuracy did not i


Epoch 00186: val_categorical_accuracy did not improve from 0.73770

Epoch 00187: val_categorical_accuracy did not improve from 0.73770

Epoch 00188: val_categorical_accuracy did not improve from 0.73770

Epoch 00189: val_categorical_accuracy did not improve from 0.73770

Epoch 00190: val_categorical_accuracy did not improve from 0.73770

Epoch 00191: val_categorical_accuracy did not improve from 0.73770

Epoch 00192: val_categorical_accuracy did not improve from 0.73770

Epoch 00193: val_categorical_accuracy did not improve from 0.73770

Epoch 00194: val_categorical_accuracy did not improve from 0.73770

Epoch 00195: val_categorical_accuracy did not improve from 0.73770

Epoch 00196: val_categorical_accuracy did not improve from 0.73770

Epoch 00197: val_categorical_accuracy did not improve from 0.73770

Epoch 00198: val_categorical_accuracy did not improve from 0.73770

Epoch 00199: val_categorical_accuracy did not improve from 0.73770

Epoch 00200: val_categorical_accuracy did not i



= Source Model with overlap ratio of 95% will be transfered to Target Data with overlap ratio of 85%, Source Model shown below =


Model: "model_3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_4 (InputLayer)            [(None, 103, 24, 24, 0                                            
__________________________________________________________________________________________________
conv_0 (Conv3D)                 (None, 48, 11, 11, 3 2336        input_4[0][0]                    
__________________________________________________________________________________________________
bn_conv_0 (BatchNormalization)  (None, 48, 11, 11, 3 128         conv_0[0][0]                     
__________________________________________________________________________________________________
activation_3 (Activation)       (None, 48, 11, 11, 3 0    

(639, 103, 24, 24, 1) (169, 103, 24, 24, 1) (639,) (169,)
Total samples per class: [6, 135, 36, 11, 33, 77, 4, 29, 4, 83, 216, 43, 21, 89, 11, 10], Total number of samples is 808.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 169.
number of samples per class in Ytest: [ 2 27  8  3  7 16  1  6  1 17 44  9  5 18  3  2]

Xtrain_transfer => (639, 64)
Xtest_transfer  => (639, 64)
Ytrain => (639, 16)
Ytest  => (169, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_15 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112      
Total params: 20,752
Trainab


Epoch 00084: val_categorical_accuracy did not improve from 0.73964

Epoch 00085: val_categorical_accuracy did not improve from 0.73964

Epoch 00086: val_categorical_accuracy did not improve from 0.73964

Epoch 00087: val_categorical_accuracy did not improve from 0.73964

Epoch 00088: val_categorical_accuracy did not improve from 0.73964

Epoch 00089: val_categorical_accuracy did not improve from 0.73964

Epoch 00090: val_categorical_accuracy did not improve from 0.73964

Epoch 00091: val_categorical_accuracy did not improve from 0.73964

Epoch 00092: val_categorical_accuracy did not improve from 0.73964

Epoch 00093: val_categorical_accuracy did not improve from 0.73964

Epoch 00094: val_categorical_accuracy did not improve from 0.73964

Epoch 00095: val_categorical_accuracy did not improve from 0.73964

Epoch 00096: val_categorical_accuracy did not improve from 0.73964

Epoch 00097: val_categorical_accuracy did not improve from 0.73964

Epoch 00098: val_categorical_accuracy did not i


Epoch 00206: val_categorical_accuracy did not improve from 0.74556

Epoch 00207: val_categorical_accuracy did not improve from 0.74556

Epoch 00208: val_categorical_accuracy did not improve from 0.74556

Epoch 00209: val_categorical_accuracy did not improve from 0.74556

Epoch 00210: val_categorical_accuracy did not improve from 0.74556

Epoch 00211: val_categorical_accuracy did not improve from 0.74556

Epoch 00212: val_categorical_accuracy did not improve from 0.74556

Epoch 00213: val_categorical_accuracy did not improve from 0.74556

Epoch 00214: val_categorical_accuracy did not improve from 0.74556

Epoch 00215: val_categorical_accuracy did not improve from 0.74556

Epoch 00216: val_categorical_accuracy did not improve from 0.74556

Epoch 00217: val_categorical_accuracy did not improve from 0.74556

Epoch 00218: val_categorical_accuracy did not improve from 0.74556

Epoch 00219: val_categorical_accuracy did not improve from 0.74556

Epoch 00220: val_categorical_accuracy did not i

(3109, 103, 24, 24, 1) (785, 103, 24, 24, 1) (3109,) (785,)
Total samples per class: [24, 668, 177, 45, 137, 365, 14, 141, 10, 408, 1067, 181, 101, 465, 46, 45], Total number of samples is 3894.

unique classes in Ytest: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16], Total number of samples in Ytest is 785.
number of samples per class in Ytest: [  5 134  36   9  28  73   3  29   2  82 214  37  21  93  10   9]

Xtrain_transfer => (3109, 64)
Xtest_transfer  => (3109, 64)
Ytrain => (3109, 16)
Ytest  => (785, 16)

Model: "model_transfer"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_16 (InputLayer)        [(None, 64)]              0         
_________________________________________________________________
fc_256 (Dense)               (None, 256)               16640     
_________________________________________________________________
fc16 (Dense)                 (None, 16)                4112 


Epoch 00058: val_categorical_accuracy did not improve from 0.75669

Epoch 00059: val_categorical_accuracy did not improve from 0.75669

Epoch 00060: val_categorical_accuracy did not improve from 0.75669

Epoch 00061: val_categorical_accuracy did not improve from 0.75669

Epoch 00062: val_categorical_accuracy did not improve from 0.75669

Epoch 00063: val_categorical_accuracy did not improve from 0.75669

Epoch 00064: val_categorical_accuracy did not improve from 0.75669

Epoch 00065: val_categorical_accuracy did not improve from 0.75669

Epoch 00066: val_categorical_accuracy did not improve from 0.75669

Epoch 00067: val_categorical_accuracy did not improve from 0.75669

Epoch 00068: val_categorical_accuracy did not improve from 0.75669

Epoch 00069: val_categorical_accuracy did not improve from 0.75669

Epoch 00070: val_categorical_accuracy did not improve from 0.75669

Epoch 00071: val_categorical_accuracy did not improve from 0.75669

Epoch 00072: val_categorical_accuracy did not i


Epoch 00175: val_categorical_accuracy did not improve from 0.75924

Epoch 00176: val_categorical_accuracy did not improve from 0.75924

Epoch 00177: val_categorical_accuracy did not improve from 0.75924

Epoch 00178: val_categorical_accuracy did not improve from 0.75924

Epoch 00179: val_categorical_accuracy did not improve from 0.75924

Epoch 00180: val_categorical_accuracy did not improve from 0.75924

Epoch 00181: val_categorical_accuracy did not improve from 0.75924

Epoch 00182: val_categorical_accuracy did not improve from 0.75924

Epoch 00183: val_categorical_accuracy did not improve from 0.75924

Epoch 00184: val_categorical_accuracy did not improve from 0.75924

Epoch 00185: val_categorical_accuracy did not improve from 0.75924

Epoch 00186: val_categorical_accuracy did not improve from 0.75924

Epoch 00187: val_categorical_accuracy did not improve from 0.75924

Epoch 00188: val_categorical_accuracy did not improve from 0.75924

Epoch 00189: val_categorical_accuracy did not i


Epoch 00295: val_categorical_accuracy did not improve from 0.76051

Epoch 00296: val_categorical_accuracy did not improve from 0.76051

Epoch 00297: val_categorical_accuracy did not improve from 0.76051

Epoch 00298: val_categorical_accuracy did not improve from 0.76051

Epoch 00299: val_categorical_accuracy did not improve from 0.76051

Epoch 00300: val_categorical_accuracy did not improve from 0.76051
785/785 [==============================] - 0s 60us/sample - loss: 0.8904 - categorical_accuracy: 0.7592
Test Accuracy = 0.7592357
785/785 [==============================] - 0s 532us/sample

============ Confusion_matrix for data with source overlap ratio of 95 and target overlap ratio of  95 is as below ============

[[  4   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0]
 [  0 107   0   1   6   1   0   0   0   0  18   1   0   0   0   0]
 [  0   0   7   0   0   0   0   0   0   0  28   0   0   1   0   0]
 [  0   6   0   3   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0

In [5]:
Acc_Tbl

0                1                2                3  \
0    Test Accuracy  Indian_Pines_50  Indian_Pines_75  Indian_Pines_85   
1  Indian_Pines_50          45.4545          55.7377          59.1716   
2  Indian_Pines_75          45.4545           52.459          54.4379   
3  Indian_Pines_85          63.6364          75.4098          70.4142   
4  Indian_Pines_95          63.6364          72.1311          74.5562   

                 4  
0  Indian_Pines_95  
1           64.586  
2          64.4586  
3          74.5223  
4          75.9236